# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-29 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20161029_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='duration',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
