# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-03 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
