# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_clip_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dimension',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
