# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0018_auto_20170926_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='org_file',
            field=models.FileField(blank=True, null=True, upload_to='newslens/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='dimension',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
