# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sawtooth_sdk/protobuf/state_context.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sawtooth_sdk.protobuf import events_pb2 as sawtooth__sdk_dot_protobuf_dot_events__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sawtooth_sdk/protobuf/state_context.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n)sawtooth_sdk/protobuf/state_context.proto\x1a\"sawtooth_sdk/protobuf/events.proto\"&\n\x05\x45ntry\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\":\n\x11TpStateGetRequest\x12\x12\n\ncontext_id\x18\x01 \x01(\t\x12\x11\n\taddresses\x18\x02 \x03(\t\"\x84\x01\n\x12TpStateGetResponse\x12\x17\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x06.Entry\x12*\n\x06status\x18\x02 \x01(\x0e\x32\x1a.TpStateGetResponse.Status\")\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\x17\n\x13\x41UTHORIZATION_ERROR\x10\x01\"@\n\x11TpStateSetRequest\x12\x12\n\ncontext_id\x18\x01 \x01(\t\x12\x17\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\x06.Entry\"~\n\x12TpStateSetResponse\x12\x11\n\taddresses\x18\x01 \x03(\t\x12*\n\x06status\x18\x02 \x01(\x0e\x32\x1a.TpStateSetResponse.Status\")\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\x17\n\x13\x41UTHORIZATION_ERROR\x10\x01\"=\n\x14TpStateDeleteRequest\x12\x12\n\ncontext_id\x18\x01 \x01(\t\x12\x11\n\taddresses\x18\x02 \x03(\t\"\x84\x01\n\x15TpStateDeleteResponse\x12\x11\n\taddresses\x18\x01 \x03(\t\x12-\n\x06status\x18\x02 \x01(\x0e\x32\x1d.TpStateDeleteResponse.Status\")\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\x17\n\x13\x41UTHORIZATION_ERROR\x10\x01\"N\n\x17TpAddReceiptDataRequest\x12\x12\n\ncontext_id\x18\x01 \x01(\t\x12\x11\n\tdata_type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"i\n\x18TpAddReceiptDataResponse\x12\x30\n\x06status\x18\x02 \x01(\x0e\x32 .TpAddReceiptDataResponse.Status\"\x1b\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\">\n\x11TpAddEventRequest\x12\x12\n\ncontext_id\x18\x01 \x01(\t\x12\x15\n\x05\x65vent\x18\x02 \x01(\x0b\x32\x06.Event\"]\n\x12TpAddEventResponse\x12*\n\x06status\x18\x02 \x01(\x0e\x32\x1a.TpAddEventResponse.Status\"\x1b\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x42,\n\x15sawtooth.sdk.protobufP\x01Z\x11state_context_pb2b\x06proto3')
  ,
  dependencies=[sawtooth__sdk_dot_protobuf_dot_events__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TPSTATEGETRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='TpStateGetResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTHORIZATION_ERROR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=273,
  serialized_end=314,
)
_sym_db.RegisterEnumDescriptor(_TPSTATEGETRESPONSE_STATUS)

_TPSTATESETRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='TpStateSetResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTHORIZATION_ERROR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=273,
  serialized_end=314,
)
_sym_db.RegisterEnumDescriptor(_TPSTATESETRESPONSE_STATUS)

_TPSTATEDELETERESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='TpStateDeleteResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTHORIZATION_ERROR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=273,
  serialized_end=314,
)
_sym_db.RegisterEnumDescriptor(_TPSTATEDELETERESPONSE_STATUS)

_TPADDRECEIPTDATARESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='TpAddReceiptDataResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=866,
  serialized_end=893,
)
_sym_db.RegisterEnumDescriptor(_TPADDRECEIPTDATARESPONSE_STATUS)

_TPADDEVENTRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='TpAddEventResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=866,
  serialized_end=893,
)
_sym_db.RegisterEnumDescriptor(_TPADDEVENTRESPONSE_STATUS)


_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='Entry.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='Entry.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=119,
)


_TPSTATEGETREQUEST = _descriptor.Descriptor(
  name='TpStateGetRequest',
  full_name='TpStateGetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='context_id', full_name='TpStateGetRequest.context_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='addresses', full_name='TpStateGetRequest.addresses', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=179,
)


_TPSTATEGETRESPONSE = _descriptor.Descriptor(
  name='TpStateGetResponse',
  full_name='TpStateGetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='TpStateGetResponse.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='TpStateGetResponse.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TPSTATEGETRESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=314,
)


_TPSTATESETREQUEST = _descriptor.Descriptor(
  name='TpStateSetRequest',
  full_name='TpStateSetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='context_id', full_name='TpStateSetRequest.context_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entries', full_name='TpStateSetRequest.entries', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=380,
)


_TPSTATESETRESPONSE = _descriptor.Descriptor(
  name='TpStateSetResponse',
  full_name='TpStateSetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='addresses', full_name='TpStateSetResponse.addresses', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='TpStateSetResponse.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TPSTATESETRESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=382,
  serialized_end=508,
)


_TPSTATEDELETEREQUEST = _descriptor.Descriptor(
  name='TpStateDeleteRequest',
  full_name='TpStateDeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='context_id', full_name='TpStateDeleteRequest.context_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='addresses', full_name='TpStateDeleteRequest.addresses', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=510,
  serialized_end=571,
)


_TPSTATEDELETERESPONSE = _descriptor.Descriptor(
  name='TpStateDeleteResponse',
  full_name='TpStateDeleteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='addresses', full_name='TpStateDeleteResponse.addresses', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='TpStateDeleteResponse.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TPSTATEDELETERESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=574,
  serialized_end=706,
)


_TPADDRECEIPTDATAREQUEST = _descriptor.Descriptor(
  name='TpAddReceiptDataRequest',
  full_name='TpAddReceiptDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='context_id', full_name='TpAddReceiptDataRequest.context_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_type', full_name='TpAddReceiptDataRequest.data_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='TpAddReceiptDataRequest.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=708,
  serialized_end=786,
)


_TPADDRECEIPTDATARESPONSE = _descriptor.Descriptor(
  name='TpAddReceiptDataResponse',
  full_name='TpAddReceiptDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='TpAddReceiptDataResponse.status', index=0,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TPADDRECEIPTDATARESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=788,
  serialized_end=893,
)


_TPADDEVENTREQUEST = _descriptor.Descriptor(
  name='TpAddEventRequest',
  full_name='TpAddEventRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='context_id', full_name='TpAddEventRequest.context_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event', full_name='TpAddEventRequest.event', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=895,
  serialized_end=957,
)


_TPADDEVENTRESPONSE = _descriptor.Descriptor(
  name='TpAddEventResponse',
  full_name='TpAddEventResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='TpAddEventResponse.status', index=0,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TPADDEVENTRESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=959,
  serialized_end=1052,
)

_TPSTATEGETRESPONSE.fields_by_name['entries'].message_type = _ENTRY
_TPSTATEGETRESPONSE.fields_by_name['status'].enum_type = _TPSTATEGETRESPONSE_STATUS
_TPSTATEGETRESPONSE_STATUS.containing_type = _TPSTATEGETRESPONSE
_TPSTATESETREQUEST.fields_by_name['entries'].message_type = _ENTRY
_TPSTATESETRESPONSE.fields_by_name['status'].enum_type = _TPSTATESETRESPONSE_STATUS
_TPSTATESETRESPONSE_STATUS.containing_type = _TPSTATESETRESPONSE
_TPSTATEDELETERESPONSE.fields_by_name['status'].enum_type = _TPSTATEDELETERESPONSE_STATUS
_TPSTATEDELETERESPONSE_STATUS.containing_type = _TPSTATEDELETERESPONSE
_TPADDRECEIPTDATARESPONSE.fields_by_name['status'].enum_type = _TPADDRECEIPTDATARESPONSE_STATUS
_TPADDRECEIPTDATARESPONSE_STATUS.containing_type = _TPADDRECEIPTDATARESPONSE
_TPADDEVENTREQUEST.fields_by_name['event'].message_type = sawtooth__sdk_dot_protobuf_dot_events__pb2._EVENT
_TPADDEVENTRESPONSE.fields_by_name['status'].enum_type = _TPADDEVENTRESPONSE_STATUS
_TPADDEVENTRESPONSE_STATUS.containing_type = _TPADDEVENTRESPONSE
DESCRIPTOR.message_types_by_name['Entry'] = _ENTRY
DESCRIPTOR.message_types_by_name['TpStateGetRequest'] = _TPSTATEGETREQUEST
DESCRIPTOR.message_types_by_name['TpStateGetResponse'] = _TPSTATEGETRESPONSE
DESCRIPTOR.message_types_by_name['TpStateSetRequest'] = _TPSTATESETREQUEST
DESCRIPTOR.message_types_by_name['TpStateSetResponse'] = _TPSTATESETRESPONSE
DESCRIPTOR.message_types_by_name['TpStateDeleteRequest'] = _TPSTATEDELETEREQUEST
DESCRIPTOR.message_types_by_name['TpStateDeleteResponse'] = _TPSTATEDELETERESPONSE
DESCRIPTOR.message_types_by_name['TpAddReceiptDataRequest'] = _TPADDRECEIPTDATAREQUEST
DESCRIPTOR.message_types_by_name['TpAddReceiptDataResponse'] = _TPADDRECEIPTDATARESPONSE
DESCRIPTOR.message_types_by_name['TpAddEventRequest'] = _TPADDEVENTREQUEST
DESCRIPTOR.message_types_by_name['TpAddEventResponse'] = _TPADDEVENTRESPONSE

Entry = _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), dict(
  DESCRIPTOR = _ENTRY,
  __module__ = 'sawtooth_sdk.protobuf.state_context_pb2'
  # @@protoc_insertion_point(class_scope:Entry)
  ))
_sym_db.RegisterMessage(Entry)

TpStateGetRequest = _reflection.GeneratedProtocolMessageType('TpStateGetRequest', (_message.Message,), dict(
  DESCRIPTOR = _TPSTATEGETREQUEST,
  __module__ = 'sawtooth_sdk.protobuf.state_context_pb2'
  # @@protoc_insertion_point(class_scope:TpStateGetRequest)
  ))
_sym_db.RegisterMessage(TpStateGetRequest)

TpStateGetResponse = _reflection.GeneratedProtocolMessageType('TpStateGetResponse', (_message.Message,), dict(
  DESCRIPTOR = _TPSTATEGETRESPONSE,
  __module__ = 'sawtooth_sdk.protobuf.state_context_pb2'
  # @@protoc_insertion_point(class_scope:TpStateGetResponse)
  ))
_sym_db.RegisterMessage(TpStateGetResponse)

TpStateSetRequest = _reflection.GeneratedProtocolMessageType('TpStateSetRequest', (_message.Message,), dict(
  DESCRIPTOR = _TPSTATESETREQUEST,
  __module__ = 'sawtooth_sdk.protobuf.state_context_pb2'
  # @@protoc_insertion_point(class_scope:TpStateSetRequest)
  ))
_sym_db.RegisterMessage(TpStateSetRequest)

TpStateSetResponse = _reflection.GeneratedProtocolMessageType('TpStateSetResponse', (_message.Message,), dict(
  DESCRIPTOR = _TPSTATESETRESPONSE,
  __module__ = 'sawtooth_sdk.protobuf.state_context_pb2'
  # @@protoc_insertion_point(class_scope:TpStateSetResponse)
  ))
_sym_db.RegisterMessage(TpStateSetResponse)

TpStateDeleteRequest = _reflection.GeneratedProtocolMessageType('TpStateDeleteRequest', (_message.Message,), dict(
  DESCRIPTOR = _TPSTATEDELETEREQUEST,
  __module__ = 'sawtooth_sdk.protobuf.state_context_pb2'
  # @@protoc_insertion_point(class_scope:TpStateDeleteRequest)
  ))
_sym_db.RegisterMessage(TpStateDeleteRequest)

TpStateDeleteResponse = _reflection.GeneratedProtocolMessageType('TpStateDeleteResponse', (_message.Message,), dict(
  DESCRIPTOR = _TPSTATEDELETERESPONSE,
  __module__ = 'sawtooth_sdk.protobuf.state_context_pb2'
  # @@protoc_insertion_point(class_scope:TpStateDeleteResponse)
  ))
_sym_db.RegisterMessage(TpStateDeleteResponse)

TpAddReceiptDataRequest = _reflection.GeneratedProtocolMessageType('TpAddReceiptDataRequest', (_message.Message,), dict(
  DESCRIPTOR = _TPADDRECEIPTDATAREQUEST,
  __module__ = 'sawtooth_sdk.protobuf.state_context_pb2'
  # @@protoc_insertion_point(class_scope:TpAddReceiptDataRequest)
  ))
_sym_db.RegisterMessage(TpAddReceiptDataRequest)

TpAddReceiptDataResponse = _reflection.GeneratedProtocolMessageType('TpAddReceiptDataResponse', (_message.Message,), dict(
  DESCRIPTOR = _TPADDRECEIPTDATARESPONSE,
  __module__ = 'sawtooth_sdk.protobuf.state_context_pb2'
  # @@protoc_insertion_point(class_scope:TpAddReceiptDataResponse)
  ))
_sym_db.RegisterMessage(TpAddReceiptDataResponse)

TpAddEventRequest = _reflection.GeneratedProtocolMessageType('TpAddEventRequest', (_message.Message,), dict(
  DESCRIPTOR = _TPADDEVENTREQUEST,
  __module__ = 'sawtooth_sdk.protobuf.state_context_pb2'
  # @@protoc_insertion_point(class_scope:TpAddEventRequest)
  ))
_sym_db.RegisterMessage(TpAddEventRequest)

TpAddEventResponse = _reflection.GeneratedProtocolMessageType('TpAddEventResponse', (_message.Message,), dict(
  DESCRIPTOR = _TPADDEVENTRESPONSE,
  __module__ = 'sawtooth_sdk.protobuf.state_context_pb2'
  # @@protoc_insertion_point(class_scope:TpAddEventResponse)
  ))
_sym_db.RegisterMessage(TpAddEventResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\025sawtooth.sdk.protobufP\001Z\021state_context_pb2'))
# @@protoc_insertion_point(module_scope)
