# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sawtooth_sdk/protobuf/txn_receipt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sawtooth_sdk.protobuf import state_delta_pb2 as sawtooth__sdk_dot_protobuf_dot_state__delta__pb2
from sawtooth_sdk.protobuf import events_pb2 as sawtooth__sdk_dot_protobuf_dot_events__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sawtooth_sdk/protobuf/txn_receipt.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\'sawtooth_sdk/protobuf/txn_receipt.proto\x1a\'sawtooth_sdk/protobuf/state_delta.proto\x1a\"sawtooth_sdk/protobuf/events.proto\"\xba\x01\n\x12TransactionReceipt\x12#\n\rstate_changes\x18\x01 \x03(\x0b\x32\x0c.StateChange\x12\x16\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x06.Event\x12&\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x18.TransactionReceipt.Data\x12\x16\n\x0etransaction_id\x18\x04 \x01(\t\x1a\'\n\x04\x44\x61ta\x12\x11\n\tdata_type\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"2\n\x17\x43lientReceiptGetRequest\x12\x17\n\x0ftransaction_ids\x18\x01 \x03(\t\"\xaa\x01\n\x18\x43lientReceiptGetResponse\x12\x30\n\x06status\x18\x01 \x01(\x0e\x32 .ClientReceiptGetResponse.Status\x12%\n\x08receipts\x18\x02 \x03(\x0b\x32\x13.TransactionReceipt\"5\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\x12\n\x0eINTERNAL_ERROR\x10\x01\x12\x0f\n\x0bNO_RESOURCE\x10\x04\x42*\n\x15sawtooth.sdk.protobufP\x01Z\x0ftxn_receipt_pb2b\x06proto3')
  ,
  dependencies=[sawtooth__sdk_dot_protobuf_dot_state__delta__pb2.DESCRIPTOR,sawtooth__sdk_dot_protobuf_dot_events__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CLIENTRECEIPTGETRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='ClientReceiptGetResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_ERROR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_RESOURCE', index=2, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=479,
  serialized_end=532,
)
_sym_db.RegisterEnumDescriptor(_CLIENTRECEIPTGETRESPONSE_STATUS)


_TRANSACTIONRECEIPT_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='TransactionReceipt.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_type', full_name='TransactionReceipt.Data.data_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='TransactionReceipt.Data.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=307,
)

_TRANSACTIONRECEIPT = _descriptor.Descriptor(
  name='TransactionReceipt',
  full_name='TransactionReceipt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state_changes', full_name='TransactionReceipt.state_changes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='events', full_name='TransactionReceipt.events', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='TransactionReceipt.data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transaction_id', full_name='TransactionReceipt.transaction_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TRANSACTIONRECEIPT_DATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=307,
)


_CLIENTRECEIPTGETREQUEST = _descriptor.Descriptor(
  name='ClientReceiptGetRequest',
  full_name='ClientReceiptGetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transaction_ids', full_name='ClientReceiptGetRequest.transaction_ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=359,
)


_CLIENTRECEIPTGETRESPONSE = _descriptor.Descriptor(
  name='ClientReceiptGetResponse',
  full_name='ClientReceiptGetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ClientReceiptGetResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='receipts', full_name='ClientReceiptGetResponse.receipts', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CLIENTRECEIPTGETRESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=532,
)

_TRANSACTIONRECEIPT_DATA.containing_type = _TRANSACTIONRECEIPT
_TRANSACTIONRECEIPT.fields_by_name['state_changes'].message_type = sawtooth__sdk_dot_protobuf_dot_state__delta__pb2._STATECHANGE
_TRANSACTIONRECEIPT.fields_by_name['events'].message_type = sawtooth__sdk_dot_protobuf_dot_events__pb2._EVENT
_TRANSACTIONRECEIPT.fields_by_name['data'].message_type = _TRANSACTIONRECEIPT_DATA
_CLIENTRECEIPTGETRESPONSE.fields_by_name['status'].enum_type = _CLIENTRECEIPTGETRESPONSE_STATUS
_CLIENTRECEIPTGETRESPONSE.fields_by_name['receipts'].message_type = _TRANSACTIONRECEIPT
_CLIENTRECEIPTGETRESPONSE_STATUS.containing_type = _CLIENTRECEIPTGETRESPONSE
DESCRIPTOR.message_types_by_name['TransactionReceipt'] = _TRANSACTIONRECEIPT
DESCRIPTOR.message_types_by_name['ClientReceiptGetRequest'] = _CLIENTRECEIPTGETREQUEST
DESCRIPTOR.message_types_by_name['ClientReceiptGetResponse'] = _CLIENTRECEIPTGETRESPONSE

TransactionReceipt = _reflection.GeneratedProtocolMessageType('TransactionReceipt', (_message.Message,), dict(

  Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
    DESCRIPTOR = _TRANSACTIONRECEIPT_DATA,
    __module__ = 'sawtooth_sdk.protobuf.txn_receipt_pb2'
    # @@protoc_insertion_point(class_scope:TransactionReceipt.Data)
    ))
  ,
  DESCRIPTOR = _TRANSACTIONRECEIPT,
  __module__ = 'sawtooth_sdk.protobuf.txn_receipt_pb2'
  # @@protoc_insertion_point(class_scope:TransactionReceipt)
  ))
_sym_db.RegisterMessage(TransactionReceipt)
_sym_db.RegisterMessage(TransactionReceipt.Data)

ClientReceiptGetRequest = _reflection.GeneratedProtocolMessageType('ClientReceiptGetRequest', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTRECEIPTGETREQUEST,
  __module__ = 'sawtooth_sdk.protobuf.txn_receipt_pb2'
  # @@protoc_insertion_point(class_scope:ClientReceiptGetRequest)
  ))
_sym_db.RegisterMessage(ClientReceiptGetRequest)

ClientReceiptGetResponse = _reflection.GeneratedProtocolMessageType('ClientReceiptGetResponse', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTRECEIPTGETRESPONSE,
  __module__ = 'sawtooth_sdk.protobuf.txn_receipt_pb2'
  # @@protoc_insertion_point(class_scope:ClientReceiptGetResponse)
  ))
_sym_db.RegisterMessage(ClientReceiptGetResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\025sawtooth.sdk.protobufP\001Z\017txn_receipt_pb2'))
# @@protoc_insertion_point(module_scope)
