
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-19T17:01:29-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "58d3927f153d60a406d925f9eb74bcee6fd56117",
 "version": "0.11.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
