import six
from ipywidgets import Widget, DOMWidget, widget_serialization, Color, register
from traitlets import (
    Unicode, Int, CInt, Instance, ForwardDeclaredInstance, This, Enum,
    Tuple, List, Dict, Float, CFloat, Bool, Union, Any,
    )

from .._base.Three import ThreeWidget
from ..enums import *
from ..traits import *

from .._base.Three import ThreeWidget


@register
class Interpolant(ThreeWidget):
    """Interpolant

    Autogenerated by generate-wrappers.js
    Date: Fri Dec 15 2017 14:52:39 GMT+0100 (W. Europe Standard Time)
    See https://threejs.org/docs/#api/math/Interpolant
    """

    def __init__(self, **kwargs):
        super(Interpolant, self).__init__(**kwargs)

    _model_name = Unicode('InterpolantModel').tag(sync=True)


if six.PY3:
    import inspect
    # Include explicit signature since the metaclass screws it up
    Interpolant.__signature__ = inspect.signature(Interpolant.__init__)
