# coding: utf-8

"""
    3blades API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.auth_token_data import AuthTokenData


class TestAuthTokenData(unittest.TestCase):
    """ AuthTokenData unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthTokenData(self):
        """
        Test AuthTokenData
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.auth_token_data.AuthTokenData()
        pass


if __name__ == '__main__':
    unittest.main()
