formatters:
    MultiLineFormatter:
        '()': probe.log.MultiLineFormatter
        format: '%(asctime)s.%(msecs).03d %(process)+5s %(levelname)-8s %(filename)s:%(lineno)d:%(funcName)s(): %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

filters:
    FilterNotD:
        '()': probe.log.NotLevelFilter
        levels: [DEBUG]
    FilterWIC:
        '()': probe.log.LevelFilter
        levels: [WARNING, INFO, CRITICAL]
    FilterNotWIC:
        '()': probe.log.NotLevelFilter
        levels: [WARNING, INFO, CRITICAL]
    FilterWEC:
        '()': probe.log.LevelFilter
        levels: [WARNING, ERROR, CRITICAL]

handlers:
    null:
        class: logging.NullHandler
    file:
        class: logging.FileHandler
        formatter: MultiLineFormatter
        mode: w
        filename: cloud.log
    consoleAll:
        class: logging.StreamHandler
        formatter: MultiLineFormatter
        stream: ext://sys.stderr
    consoleErrors:
        filters: ['FilterWEC']
        class: logging.StreamHandler
        formatter: MultiLineFormatter
        stream: ext://sys.stderr
    consoleNotDebug:
        filters: ['FilterNotD']
        class: logging.StreamHandler
        formatter: MultiLineFormatter
        stream: ext://sys.stderr

loggers:
  probe.cloud.rdir_watcher:
      handlers: [consoleAll, file]
      propagate: False
      level: DEBUG
  probe.cloud.cloud:
      handlers: [consoleAll, file]
      propagate: False
      level: DEBUG
  paramiko:
      handlers: [consoleAll, file]
      propagate: False
      level: WARNING

root:
    handlers: [consoleAll, file]
    propagate: False
