# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: beam_provision_api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='beam_provision_api.proto',
  package='org.apache.beam.fn.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x18\x62\x65\x61m_provision_api.proto\x12\x15org.apache.beam.fn.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x19\n\x17GetProvisionInfoRequest\"N\n\x18GetProvisionInfoResponse\x12\x32\n\x04info\x18\x01 \x01(\x0b\x32$.org.apache.beam.fn.v1.ProvisionInfo\"d\n\rProvisionInfo\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x10\n\x08job_name\x18\x02 \x01(\t\x12\x31\n\x10pipeline_options\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct2\x87\x01\n\x10ProvisionService\x12s\n\x10GetProvisionInfo\x12..org.apache.beam.fn.v1.GetProvisionInfoRequest\x1a/.org.apache.beam.fn.v1.GetProvisionInfoResponseB%\n\x15org.apache.beam.fn.v1B\x0cProvisionApib\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_GETPROVISIONINFOREQUEST = _descriptor.Descriptor(
  name='GetProvisionInfoRequest',
  full_name='org.apache.beam.fn.v1.GetProvisionInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=106,
)


_GETPROVISIONINFORESPONSE = _descriptor.Descriptor(
  name='GetProvisionInfoResponse',
  full_name='org.apache.beam.fn.v1.GetProvisionInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='org.apache.beam.fn.v1.GetProvisionInfoResponse.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=186,
)


_PROVISIONINFO = _descriptor.Descriptor(
  name='ProvisionInfo',
  full_name='org.apache.beam.fn.v1.ProvisionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='org.apache.beam.fn.v1.ProvisionInfo.job_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='job_name', full_name='org.apache.beam.fn.v1.ProvisionInfo.job_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pipeline_options', full_name='org.apache.beam.fn.v1.ProvisionInfo.pipeline_options', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=288,
)

_GETPROVISIONINFORESPONSE.fields_by_name['info'].message_type = _PROVISIONINFO
_PROVISIONINFO.fields_by_name['pipeline_options'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['GetProvisionInfoRequest'] = _GETPROVISIONINFOREQUEST
DESCRIPTOR.message_types_by_name['GetProvisionInfoResponse'] = _GETPROVISIONINFORESPONSE
DESCRIPTOR.message_types_by_name['ProvisionInfo'] = _PROVISIONINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetProvisionInfoRequest = _reflection.GeneratedProtocolMessageType('GetProvisionInfoRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETPROVISIONINFOREQUEST,
  __module__ = 'beam_provision_api_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.beam.fn.v1.GetProvisionInfoRequest)
  ))
_sym_db.RegisterMessage(GetProvisionInfoRequest)

GetProvisionInfoResponse = _reflection.GeneratedProtocolMessageType('GetProvisionInfoResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETPROVISIONINFORESPONSE,
  __module__ = 'beam_provision_api_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.beam.fn.v1.GetProvisionInfoResponse)
  ))
_sym_db.RegisterMessage(GetProvisionInfoResponse)

ProvisionInfo = _reflection.GeneratedProtocolMessageType('ProvisionInfo', (_message.Message,), dict(
  DESCRIPTOR = _PROVISIONINFO,
  __module__ = 'beam_provision_api_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.beam.fn.v1.ProvisionInfo)
  ))
_sym_db.RegisterMessage(ProvisionInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\025org.apache.beam.fn.v1B\014ProvisionApi'))

_PROVISIONSERVICE = _descriptor.ServiceDescriptor(
  name='ProvisionService',
  full_name='org.apache.beam.fn.v1.ProvisionService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=291,
  serialized_end=426,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProvisionInfo',
    full_name='org.apache.beam.fn.v1.ProvisionService.GetProvisionInfo',
    index=0,
    containing_service=None,
    input_type=_GETPROVISIONINFOREQUEST,
    output_type=_GETPROVISIONINFORESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROVISIONSERVICE)

DESCRIPTOR.services_by_name['ProvisionService'] = _PROVISIONSERVICE

# @@protoc_insertion_point(module_scope)
