
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-23T14:30:07+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "1194150f47e6f4df7bbd4c9d92d6f5b7ce4fdae4",
 "version": "v0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
