language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -U pip wheel tox-travis twine
script:
- tox
deploy:
  provider: pypi
  user: mdomke
  distributions: "sdist bdist_wheel"
  password:
    secure: Vz4M3bWHw1M4IGqS3XURQDtzeaSBCTwwcBvuUbS37t9JYyZhMXmmxGRuVimCdK9uqHUHcFAzHauKIUhoL2MojxnLdPYrpGDY9yeoSeYfh5YKt9s7QFxjYcg8XngLem7zm8C43BW45wgdUafJbqeThbGAsr3mZv82de9iJOoZG8ceBVoxMavw12eLOamLE4ptAkdrMLKil9smRl1PxJUAGifzdhj80fsKZeo3tl9h4KaqFPQdBxwnI0T168bQ32JW4OOV4qgkIdPO2lbYJT/iX19EjyGD3/no5A0m/Y+ScrKum+Rke16ZAXx/+yllzqu3ES89rrIaRxM3fZNIS5Rc/SoWpQhU00O+kIziQtABOSw12LZ59hrmbF4/zdvCggvsKfutCdM3sBOb+bq1HoW/xFKqkkJRUFYaPS7LhutFkehdUJTfvkBIBcSLcrQRXo+QiO8S1qDsVNqSaYx2B0kjxuIA+bkYwOtrbybm9SKOulxvFOi0YE8yhU6CMss21fDgAHvvcEmzvfN2Ihn8hqhPLV6dFtG0jzSqDAslgfLM++cS3qd1onDpThse8cuWRKOald1+Bf3/Bc52qCuyLR5oUFa5QcZfCdyqizhMdL0D/aUXORN/9OGxUIn0fXDMB1/YdyOAFLsqKuoOsLCgo6K6NDMX4GeTA629CAEZADonXvM=
  on:
    tags: true
    all_branches: true
    repo: mdomke/pytest-mongodb
