# coding: utf-8

"""
    3blades API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class UserData(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'username': 'str',
        'email': 'str',
        'first_name': 'str',
        'last_name': 'str',
        'password': 'str',
        'profile': 'UserProfile'
    }

    attribute_map = {
        'username': 'username',
        'email': 'email',
        'first_name': 'first_name',
        'last_name': 'last_name',
        'password': 'password',
        'profile': 'profile'
    }

    def __init__(self, username=None, email=None, first_name=None, last_name=None, password=None, profile=None):
        """
        UserData - a model defined in Swagger
        """

        self._username = None
        self._email = None
        self._first_name = None
        self._last_name = None
        self._password = None
        self._profile = None

        self.username = username
        if email is not None:
          self.email = email
        if first_name is not None:
          self.first_name = first_name
        if last_name is not None:
          self.last_name = last_name
        self.password = password
        self.profile = profile

    @property
    def username(self):
        """
        Gets the username of this UserData.
        Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.

        :return: The username of this UserData.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """
        Sets the username of this UserData.
        Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.

        :param username: The username of this UserData.
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")

        self._username = username

    @property
    def email(self):
        """
        Gets the email of this UserData.
        User email.

        :return: The email of this UserData.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """
        Sets the email of this UserData.
        User email.

        :param email: The email of this UserData.
        :type: str
        """

        self._email = email

    @property
    def first_name(self):
        """
        Gets the first_name of this UserData.
        User first name.

        :return: The first_name of this UserData.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """
        Sets the first_name of this UserData.
        User first name.

        :param first_name: The first_name of this UserData.
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """
        Gets the last_name of this UserData.
        User last name.

        :return: The last_name of this UserData.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """
        Sets the last_name of this UserData.
        User last name.

        :param last_name: The last_name of this UserData.
        :type: str
        """

        self._last_name = last_name

    @property
    def password(self):
        """
        Gets the password of this UserData.
        User password.

        :return: The password of this UserData.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """
        Sets the password of this UserData.
        User password.

        :param password: The password of this UserData.
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")

        self._password = password

    @property
    def profile(self):
        """
        Gets the profile of this UserData.
        User profile information is required, although attribute values may be empty.

        :return: The profile of this UserData.
        :rtype: UserProfile
        """
        return self._profile

    @profile.setter
    def profile(self, profile):
        """
        Sets the profile of this UserData.
        User profile information is required, although attribute values may be empty.

        :param profile: The profile of this UserData.
        :type: UserProfile
        """
        if profile is None:
            raise ValueError("Invalid value for `profile`, must not be `None`")

        self._profile = profile

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, UserData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
