
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-13T15:58:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5dc91bd8696e239a9eac37c2b6e71766878a32bc",
 "version": "0.0.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
