
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-30T13:37:17+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a408ba229ea8a724b693df7c647683db251a8fa9",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
