# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-29 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20161029_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('file', models.FileField(upload_to='newslens/clip')),
                ('thumbnail', models.ImageField(upload_to='newslens/clips/thumbnail')),
                ('wav', models.FileField(upload_to='newslens/wav')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='clip',
            unique_together=set([('video', 'start_time', 'end_time')]),
        ),
    ]
