# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-29 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_clip_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second', models.IntegerField()),
                ('thumbnail', models.ImageField(upload_to='newslens/images')),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Clip')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set([('clip', 'second')]),
        ),
    ]
