# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-03 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20161101_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
