# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_remove_clip_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
