# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_auto_20161106_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
