# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_auto_20170803_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='labels',
            field=models.ManyToManyField(blank=True, to='video.Label'),
        ),
    ]
