# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-23 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0016_auto_20170917_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='labels',
            field=models.ManyToManyField(blank=True, to='video.Label'),
        ),
    ]
