# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0019_auto_20170928_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
