# coding: utf-8

"""
    style-api

    This is a API document for Stylens Service

    OpenAPI spec version: 0.0.1
    Contact: master@bluehack.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.box_array import BoxArray


class TestBoxArray(unittest.TestCase):
    """ BoxArray unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBoxArray(self):
        """
        Test BoxArray
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.box_array.BoxArray()
        pass


if __name__ == '__main__':
    unittest.main()
