sudo: false
language: python
install:
      - pip install tox 
script:
      - tox
matrix:
    include:
        - env: TOXENV=py27
        - env: TOXENV=pep8
        - env: TOXENV=py27-pytest
        - env: TOXENV=gnocchi
        - env: TOXENV=placement
        - python: 3.4
          env: TOXENV=py34
        - python: pypy
          env: TOXENV=pypy
        - python: pypy3
          env: TOXENV=pypy3
        - python: 3.5
          env: TOXENV=py35
        - python: 3.5
          env: TOXENV=py35-pytest
        - python: 3.5
          env: TOXENV=py35-failskip
        - python: 3.5
          env: TOXENV=py35-limit
        - python: 3.5
          env: TOXENV=py35-prefix
        - python: 3.6
          env: TOXENV=py36
        - python: 3.6
          env: TOXENV=py36-pytest
    allow_failures:
        - env: TOXENV=gnocchi
        - env: TOXENV=placement

notifications:
      irc: "chat.freenode.net#gabbi"
