# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp_push_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationreceipt',
            name='payload',
            field=models.TextField(default=''),
        ),
    ]
