
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-11T19:30:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "91fef62b8a29875f3bc25e05bfb9a35f02928725",
 "version": "4.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
