# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_code', models.CharField(max_length=16, verbose_name='АВС/DEF')),
                ('from_code', models.CharField(max_length=16, verbose_name='От')),
                ('to_code', models.CharField(max_length=16, verbose_name='До')),
                ('block_size', models.PositiveIntegerField(verbose_name='Емкость')),
                ('operator', models.CharField(max_length=255, verbose_name='Оператор')),
                ('region', models.CharField(max_length=255, verbose_name='Регион')),
                ('phone_type', models.CharField(choices=[('def', 'def')], max_length=16, verbose_name='Тип кода')),
            ],
        ),
    ]
