# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rossvyaz', '0002_auto_20170615_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecode',
            name='mnc',
            field=models.CharField(default='0', max_length=32, verbose_name='Mobile Network Code'),
            preserve_default=False,
        ),
    ]