sudo: false
language: python
os: linux
python:
- 2.7
- 3.4
- 3.5
- &mainstream_python 3.6
- pypy2.7-5.8.0
- pypy3.5-5.8.0
install:
- &upgrade_python_toolset pip install --upgrade pip setuptools wheel
- pip install tox-travis
- pip install coveralls
script: tox
after_success:
- coveralls

jobs:
  fast_finish: true
  include:
  - stage: Static analisys
    python: *mainstream_python
    services: skip
    install:
    - *upgrade_python_toolset
    - pip install tox
    script:
    - tox -e pylint,bandit
    after_success: skip

  - stage: Code style check
    python: *mainstream_python
    services: skip
    install:
    - *upgrade_python_toolset
    - pip install tox
    script:
    - tox -e pep8,pep257
    after_success: skip

  - stage: deploy
    # This prevents job from appearing in test plan unless commit is tagged:
    if: tag IS present
    python: *mainstream_python
    services:
    - docker
    install:
    - *upgrade_python_toolset
    script:
    - ./tools/run_docker.sh "Advanced_Descriptors"
    before_deploy:
    - pip install -r build_requirements.txt
    deploy:
    - provider: pypi
      # `skip_cleanup: true` is required to preserve binary wheels, built
      # inside of manylinux1 docker container during `script` step above.
      skip_cleanup: true
      user: penguinolog
      password:
        secure:
      on:
        tags: true
        distributions: sdist
      skip_upload_docs: true

cache: pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
