
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-19T10:25:22+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9d06afa517fc4b779ae60927ae5a14a7ac919da3",
 "version": "1.1.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
