import six
from ipywidgets import Widget, DOMWidget, widget_serialization, Color, register
from traitlets import (
    Unicode, Int, CInt, Instance, ForwardDeclaredInstance, This, Enum,
    Tuple, List, Dict, Float, CFloat, Bool, Union, Any,
    )

from ..._base.Three import ThreeWidget
from ...enums import *
from ...traits import *

from ..._base.Three import ThreeWidget


@register
class QuadraticBezierCurve3(ThreeWidget):
    """QuadraticBezierCurve3

    Autogenerated by generate-wrappers.js
    Date: Fri Dec 15 2017 14:09:57 GMT+0100 (W. Europe Standard Time)
    See https://threejs.org/docs/#api/extras/curves/QuadraticBezierCurve3
    """

    def __init__(self, **kwargs):
        super(QuadraticBezierCurve3, self).__init__(**kwargs)

    _model_name = Unicode('QuadraticBezierCurve3Model').tag(sync=True)


if six.PY3:
    import inspect
    # Include explicit signature since the metaclass screws it up
    QuadraticBezierCurve3.__signature__ = inspect.signature(QuadraticBezierCurve3.__init__)
