
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-01T19:47:06-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "aa223cb37e67cad43ff3caeac219cae7f5f9db97",
 "version": "0.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
