
# _parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DEF ELSE FRONTISCLEAR IF IFELSE INT LBRACE LEFTISCLEAR LPAREN MARKERSPRESENT MOVE NOMARKERSPRESENT NOT PICKMARKER PUTMARKER RBRACE REPEAT RIGHTISCLEAR RPAREN RUN SEMI TURNLEFT TURNRIGHT WHILEprog : DEF RUN LPAREN RPAREN LBRACE stmt RBRACEstmt : while\n                | repeat\n                | stmt_stmt\n                | action\n                | if\n                | ifelse\n        stmt_stmt : stmt SEMI stmt\n        if : IF LPAREN cond RPAREN LBRACE stmt RBRACE\n        ifelse : IFELSE LPAREN cond RPAREN LBRACE stmt RBRACE ELSE LBRACE stmt RBRACE\n        while : WHILE LPAREN cond RPAREN LBRACE stmt RBRACE\n        repeat : REPEAT LPAREN cste RPAREN LBRACE stmt RBRACE\n        cond : cond_without_not\n                | NOT cond_without_not\n        cond_without_not : FRONTISCLEAR LPAREN RPAREN\n                            | LEFTISCLEAR LPAREN RPAREN\n                            | RIGHTISCLEAR LPAREN RPAREN\n                            | MARKERSPRESENT LPAREN RPAREN \n                            | NOMARKERSPRESENT LPAREN RPAREN\n        action : MOVE LPAREN RPAREN\n                  | TURNRIGHT LPAREN RPAREN\n                  | TURNLEFT LPAREN RPAREN\n                  | PICKMARKER LPAREN RPAREN\n                  | PUTMARKER LPAREN RPAREN\n        cste : INT\n        '
    
_lr_action_items = {'DEF':([0,],[2,]),'$end':([1,23,],[0,-1,]),'RUN':([2,],[3,]),'LPAREN':([3,14,15,16,17,18,19,20,21,22,38,39,40,41,42,],[4,25,26,27,28,29,30,31,32,33,54,55,56,57,58,]),'RPAREN':([4,27,28,29,30,31,35,36,43,44,50,51,53,54,55,56,57,58,63,64,65,66,67,],[5,45,46,47,48,49,52,-13,59,-25,60,61,-14,63,64,65,66,67,-15,-16,-17,-18,-19,]),'LBRACE':([5,52,59,60,61,79,],[6,62,68,69,70,80,]),'WHILE':([6,24,62,68,69,70,80,],[14,14,14,14,14,14,14,]),'REPEAT':([6,24,62,68,69,70,80,],[15,15,15,15,15,15,15,]),'MOVE':([6,24,62,68,69,70,80,],[16,16,16,16,16,16,16,]),'TURNRIGHT':([6,24,62,68,69,70,80,],[17,17,17,17,17,17,17,]),'TURNLEFT':([6,24,62,68,69,70,80,],[18,18,18,18,18,18,18,]),'PICKMARKER':([6,24,62,68,69,70,80,],[19,19,19,19,19,19,19,]),'PUTMARKER':([6,24,62,68,69,70,80,],[20,20,20,20,20,20,20,]),'IF':([6,24,62,68,69,70,80,],[21,21,21,21,21,21,21,]),'IFELSE':([6,24,62,68,69,70,80,],[22,22,22,22,22,22,22,]),'RBRACE':([7,8,9,10,11,12,13,34,45,46,47,48,49,71,72,73,74,75,76,77,81,82,],[23,-2,-3,-4,-5,-6,-7,-8,-20,-21,-22,-23,-24,75,76,77,78,-11,-12,-9,82,-10,]),'SEMI':([7,8,9,10,11,12,13,34,45,46,47,48,49,71,72,73,74,75,76,77,81,82,],[24,-2,-3,-4,-5,-6,-7,24,-20,-21,-22,-23,-24,24,24,24,24,-11,-12,-9,24,-10,]),'NOT':([25,32,33,],[37,37,37,]),'FRONTISCLEAR':([25,32,33,37,],[38,38,38,38,]),'LEFTISCLEAR':([25,32,33,37,],[39,39,39,39,]),'RIGHTISCLEAR':([25,32,33,37,],[40,40,40,40,]),'MARKERSPRESENT':([25,32,33,37,],[41,41,41,41,]),'NOMARKERSPRESENT':([25,32,33,37,],[42,42,42,42,]),'INT':([26,],[44,]),'ELSE':([78,],[79,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'prog':([0,],[1,]),'stmt':([6,24,62,68,69,70,80,],[7,34,71,72,73,74,81,]),'while':([6,24,62,68,69,70,80,],[8,8,8,8,8,8,8,]),'repeat':([6,24,62,68,69,70,80,],[9,9,9,9,9,9,9,]),'stmt_stmt':([6,24,62,68,69,70,80,],[10,10,10,10,10,10,10,]),'action':([6,24,62,68,69,70,80,],[11,11,11,11,11,11,11,]),'if':([6,24,62,68,69,70,80,],[12,12,12,12,12,12,12,]),'ifelse':([6,24,62,68,69,70,80,],[13,13,13,13,13,13,13,]),'cond':([25,32,33,],[35,50,51,]),'cond_without_not':([25,32,33,37,],[36,36,36,53,]),'cste':([26,],[43,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> prog","S'",1,None,None,None),
  ('prog -> DEF RUN LPAREN RPAREN LBRACE stmt RBRACE','prog',7,'p_prog','parser.py',110),
  ('stmt -> while','stmt',1,'p_stmt','parser.py',115),
  ('stmt -> repeat','stmt',1,'p_stmt','parser.py',116),
  ('stmt -> stmt_stmt','stmt',1,'p_stmt','parser.py',117),
  ('stmt -> action','stmt',1,'p_stmt','parser.py',118),
  ('stmt -> if','stmt',1,'p_stmt','parser.py',119),
  ('stmt -> ifelse','stmt',1,'p_stmt','parser.py',120),
  ('stmt_stmt -> stmt SEMI stmt','stmt_stmt',3,'p_stmt_stmt','parser.py',126),
  ('if -> IF LPAREN cond RPAREN LBRACE stmt RBRACE','if',7,'p_if','parser.py',134),
  ('ifelse -> IFELSE LPAREN cond RPAREN LBRACE stmt RBRACE ELSE LBRACE stmt RBRACE','ifelse',11,'p_ifelse','parser.py',140),
  ('while -> WHILE LPAREN cond RPAREN LBRACE stmt RBRACE','while',7,'p_while','parser.py',146),
  ('repeat -> REPEAT LPAREN cste RPAREN LBRACE stmt RBRACE','repeat',7,'p_repeat','parser.py',155),
  ('cond -> cond_without_not','cond',1,'p_cond','parser.py',164),
  ('cond -> NOT cond_without_not','cond',2,'p_cond','parser.py',165),
  ('cond_without_not -> FRONTISCLEAR LPAREN RPAREN','cond_without_not',3,'p_cond_without_not','parser.py',175),
  ('cond_without_not -> LEFTISCLEAR LPAREN RPAREN','cond_without_not',3,'p_cond_without_not','parser.py',176),
  ('cond_without_not -> RIGHTISCLEAR LPAREN RPAREN','cond_without_not',3,'p_cond_without_not','parser.py',177),
  ('cond_without_not -> MARKERSPRESENT LPAREN RPAREN','cond_without_not',3,'p_cond_without_not','parser.py',178),
  ('cond_without_not -> NOMARKERSPRESENT LPAREN RPAREN','cond_without_not',3,'p_cond_without_not','parser.py',179),
  ('action -> MOVE LPAREN RPAREN','action',3,'p_action','parser.py',185),
  ('action -> TURNRIGHT LPAREN RPAREN','action',3,'p_action','parser.py',186),
  ('action -> TURNLEFT LPAREN RPAREN','action',3,'p_action','parser.py',187),
  ('action -> PICKMARKER LPAREN RPAREN','action',3,'p_action','parser.py',188),
  ('action -> PUTMARKER LPAREN RPAREN','action',3,'p_action','parser.py',189),
  ('cste -> INT','cste',1,'p_cste','parser.py',197),
]
