# coding: utf-8

"""
    3blades API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ServerActionError(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'non_field_errors': 'list[str]',
        'id': 'list[str]',
        'name': 'list[str]',
        'operation': 'list[str]'
    }

    attribute_map = {
        'non_field_errors': 'non_field_errors',
        'id': 'id',
        'name': 'name',
        'operation': 'operation'
    }

    def __init__(self, non_field_errors=None, id=None, name=None, operation=None):
        """
        ServerActionError - a model defined in Swagger
        """

        self._non_field_errors = None
        self._id = None
        self._name = None
        self._operation = None

        if non_field_errors is not None:
          self.non_field_errors = non_field_errors
        if id is not None:
          self.id = id
        if name is not None:
          self.name = name
        if operation is not None:
          self.operation = operation

    @property
    def non_field_errors(self):
        """
        Gets the non_field_errors of this ServerActionError.
        Errors not connected to any field.

        :return: The non_field_errors of this ServerActionError.
        :rtype: list[str]
        """
        return self._non_field_errors

    @non_field_errors.setter
    def non_field_errors(self, non_field_errors):
        """
        Sets the non_field_errors of this ServerActionError.
        Errors not connected to any field.

        :param non_field_errors: The non_field_errors of this ServerActionError.
        :type: list[str]
        """

        self._non_field_errors = non_field_errors

    @property
    def id(self):
        """
        Gets the id of this ServerActionError.
        Id field errors.

        :return: The id of this ServerActionError.
        :rtype: list[str]
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ServerActionError.
        Id field errors.

        :param id: The id of this ServerActionError.
        :type: list[str]
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this ServerActionError.
        Name field errors.

        :return: The name of this ServerActionError.
        :rtype: list[str]
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ServerActionError.
        Name field errors.

        :param name: The name of this ServerActionError.
        :type: list[str]
        """

        self._name = name

    @property
    def operation(self):
        """
        Gets the operation of this ServerActionError.
        Operation field errors.

        :return: The operation of this ServerActionError.
        :rtype: list[str]
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """
        Sets the operation of this ServerActionError.
        Operation field errors.

        :param operation: The operation of this ServerActionError.
        :type: list[str]
        """

        self._operation = operation

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ServerActionError):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
