
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-05T16:48:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "86c94357f13fd2f0b4eea0cf82a24d5b86c961fb",
 "version": "0.1.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
