
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-19T15:34:31-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "03f55e0d9dd0c080f5772eae47bb492795ce6cfa",
 "version": "0.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
