sudo: false
language: python
python:
    - "2.7"
#    - "3.3"  # End-of-life September 2017
    - "3.4"
    - "3.5"
    - "3.6"
#    - "3.7"  # Planned for 2018-06
install: pip install tox-travis
script: tox
