# coding: utf-8
# Generated by setup.py for PyCBC on 2017-12-20 18:04:38 +0000.

version = '1.9.0'
date = '2017-12-20 16:25:46 +0000'
release = True
last_release = '1.9.0'

git_hash = '13b15d57905fad9157ded7c7e48de70bc5eb2e30'
git_branch = 'None'
git_tag = 'v1.9.0'
git_author = 'Tito Dal Canton <tito@dalcanton.it>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Travis CI User <travis@example.org>'
git_build_date = '2017-12-20 18:04:38 +0000'
git_verbose_msg = """Branch: None
Tag: v1.9.0
Id: 13b15d57905fad9157ded7c7e48de70bc5eb2e30
Builder: Travis CI User <travis@example.org>
Build date: 2017-12-20 18:04:38 +0000
Repository status is CLEAN: All modifications committed"""
from pycbc._version import *
