# Generated by Django 2.0 on 2017-12-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, unique=True, verbose_name='Hostname')),
                ('description', models.CharField(blank=True, max_length=32, null=True, verbose_name='Description')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('update_key', models.CharField(blank=True, max_length=36, verbose_name='Update Key')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='Update Time')),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
            },
        ),
    ]
