
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-11-25T00:31:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d8af5c08710c2ca30f26db2d10b05ca0e6c745cc",
 "version": "0.2.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
