# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('diafo', '0004_auto_20171126_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='view_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
