# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('diafo', '0006_auto_20171126_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filledform',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
