---
  NeutronBGPVPN.create_and_list_routers_associations:
    -
      args: {}
      runner:
        type: "constant"
        times: 10
        concurrency: 2
      context:
        users:
          tenants: 1
          users_per_tenant: 1
        router: {}
      sla:
        failure_rate:
          max: 0
