# coding: utf-8

"""
    bl-db-product

    This is a API document for Product DB

    OpenAPI spec version: 0.1.0
    Contact: master@bluehack.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class GetVersionResponseData(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'version_name': 'str',
        'created_at': 'str'
    }

    attribute_map = {
        'id': 'id',
        'version_name': 'version_name',
        'created_at': 'created_at'
    }

    def __init__(self, id=None, version_name=None, created_at=None):
        """
        GetVersionResponseData - a model defined in Swagger
        """

        self._id = None
        self._version_name = None
        self._created_at = None

        if id is not None:
          self.id = id
        if version_name is not None:
          self.version_name = version_name
        if created_at is not None:
          self.created_at = created_at

    @property
    def id(self):
        """
        Gets the id of this GetVersionResponseData.

        :return: The id of this GetVersionResponseData.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this GetVersionResponseData.

        :param id: The id of this GetVersionResponseData.
        :type: str
        """

        self._id = id

    @property
    def version_name(self):
        """
        Gets the version_name of this GetVersionResponseData.

        :return: The version_name of this GetVersionResponseData.
        :rtype: str
        """
        return self._version_name

    @version_name.setter
    def version_name(self, version_name):
        """
        Sets the version_name of this GetVersionResponseData.

        :param version_name: The version_name of this GetVersionResponseData.
        :type: str
        """

        self._version_name = version_name

    @property
    def created_at(self):
        """
        Gets the created_at of this GetVersionResponseData.

        :return: The created_at of this GetVersionResponseData.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """
        Sets the created_at of this GetVersionResponseData.

        :param created_at: The created_at of this GetVersionResponseData.
        :type: str
        """

        self._created_at = created_at

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, GetVersionResponseData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
