# coding: utf-8

"""
    3blades API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ServerStatisticsData(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'non_field_errors': 'list[str]',
        'id': 'list[str]',
        'start': 'list[str]',
        'stop': 'list[str]',
        'size': 'list[str]'
    }

    attribute_map = {
        'non_field_errors': 'non_field_errors',
        'id': 'id',
        'start': 'start',
        'stop': 'stop',
        'size': 'size'
    }

    def __init__(self, non_field_errors=None, id=None, start=None, stop=None, size=None):
        """
        ServerStatisticsData - a model defined in Swagger
        """

        self._non_field_errors = None
        self._id = None
        self._start = None
        self._stop = None
        self._size = None

        if non_field_errors is not None:
          self.non_field_errors = non_field_errors
        if id is not None:
          self.id = id
        if start is not None:
          self.start = start
        if stop is not None:
          self.stop = stop
        if size is not None:
          self.size = size

    @property
    def non_field_errors(self):
        """
        Gets the non_field_errors of this ServerStatisticsData.
        Errors not connected to any field.

        :return: The non_field_errors of this ServerStatisticsData.
        :rtype: list[str]
        """
        return self._non_field_errors

    @non_field_errors.setter
    def non_field_errors(self, non_field_errors):
        """
        Sets the non_field_errors of this ServerStatisticsData.
        Errors not connected to any field.

        :param non_field_errors: The non_field_errors of this ServerStatisticsData.
        :type: list[str]
        """

        self._non_field_errors = non_field_errors

    @property
    def id(self):
        """
        Gets the id of this ServerStatisticsData.
        id field errors.

        :return: The id of this ServerStatisticsData.
        :rtype: list[str]
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ServerStatisticsData.
        id field errors.

        :param id: The id of this ServerStatisticsData.
        :type: list[str]
        """

        self._id = id

    @property
    def start(self):
        """
        Gets the start of this ServerStatisticsData.
        start field errors.

        :return: The start of this ServerStatisticsData.
        :rtype: list[str]
        """
        return self._start

    @start.setter
    def start(self, start):
        """
        Sets the start of this ServerStatisticsData.
        start field errors.

        :param start: The start of this ServerStatisticsData.
        :type: list[str]
        """

        self._start = start

    @property
    def stop(self):
        """
        Gets the stop of this ServerStatisticsData.
        stop field errors.

        :return: The stop of this ServerStatisticsData.
        :rtype: list[str]
        """
        return self._stop

    @stop.setter
    def stop(self, stop):
        """
        Sets the stop of this ServerStatisticsData.
        stop field errors.

        :param stop: The stop of this ServerStatisticsData.
        :type: list[str]
        """

        self._stop = stop

    @property
    def size(self):
        """
        Gets the size of this ServerStatisticsData.
        size field errors.

        :return: The size of this ServerStatisticsData.
        :rtype: list[str]
        """
        return self._size

    @size.setter
    def size(self, size):
        """
        Sets the size of this ServerStatisticsData.
        size field errors.

        :param size: The size of this ServerStatisticsData.
        :type: list[str]
        """

        self._size = size

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ServerStatisticsData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
