
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-06T21:23:26-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1bbdd3501a99711994a3e6764a7acde98ab3c4c4",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
