dist: trusty
sudo: false
cache:
  directories:
  - "$HOME/.cache/pip"
language: python
matrix:
  include:
  - python: '3.6'
    env: TOXENV=py36
install:
- pip install tox
script:
- tox
notifications:
  email: false
deploy:
  provider: pypi
  user: spotify_alf
  password:
    secure: GBz7gpUayfnCJOrh/AVKKodzEIyBjMBjksKCm13siDqIKcoIUSLyE7boUKsh46XnT9kyIahmnLsWxutkl+dMAW/jt4fW0lowYz4VpLkE0geq326Jqw2zNWRw58CSAzTuBUpeRsvo/AxDozMc4REXLafc+ThjkiZhTkQHx3lxNnodDwJlYmKo2FTdGXgBfxZLWjtlAEToP1hXGK/CmYUNvAIhCYQB5bXITGXCdUeCfI8tNQdjT8EJPcB9roCLqNJCKoKlPQBj+echYSd2J0KZav69as8lP/BMNNRt2Ke0gsGoWTCfBHCHNBknecFN29Ls65jxp/uMlvgJ1vQ4q6gZhgJuXwNw0lKytgwG6x/i+CO2yeQbowTxc3sjWzsHhcOREh7K6QwUesDjs8xv8LDRmrYyYXyFeOmpILZThX13OUNIpapr2yPU9nXNrMVP0Xd+LE6dxlemKIcR/FsNM9BTwrpD6yKIPd+sBIUnYUpahehoLlNi2X99GqcSZ7gVaTrDAZ+9yODYK12EskpTpOC4oiIKjDVW8oaU+wk+T+yrX90ChBr6ad3coWCVlEVfonFJoqV8tFP6OaLWh091hN3i+GUGuDlsxRv0GHrd87B9/9WVfXC6MBZE6PjCBWDyDCm9yLDsMmXoMRCJUmZx0cpzFwZOizzHAYmMQmDFkPPaWtA=
  on:
    tags: true
  distributions: sdist bdist_wheel
