
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-01T14:22:09+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d04069dbfb6a4b3ee4b335de37d72163d86ec850",
 "version": "0.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
