# -*- coding: utf-8 -*-

# repeat every...
REPEAT_DAILY = 'd'
REPEAT_WEEKLY = 'w'
REPEAT_MONTHLY = 'm'
REPEAT_YEARLY = 'y'


# stop condition
STOPCOND_NEVER = 'n'
STOPCOND_BYCOUNT = 'b'
STOPCOND_BYENDDATE = 'd'

# invoice date
INVDATE_CREATEDATE = '01'
INVDATE_1ST_DAY_OF_PREVMONTH = '02'
INVDATE_1ST_WORKDAY_PREVMONTH = '03'
INVDATE_LAST_WORKDAY_PREVMONTH = '04'
INVDATE_1ST_CURRENT_MONTH = '05'
INVDATE_LAST_DAY_PREVMONTH = '06'
INVDATE_1ST_WORKDAY_CURRMONTH = '07'
INVDATE_LAST_DAY_CURRMONTH = '08'
INVDATE_LAST_WORKDAY_CURRMONTH = '09'
INVDATE_LAST_DAY_CURRYEAR = '10'
INVDATE_LAST_WORKDAY_CURRYEAR = '11'
INVDATE_LAST_DAY_PREVYEAR = '12'
INVDATE_LAST_WORKDAY_PREVYEAR = '13'
INVDATE_CREATEDATE_MINUS1 = '14'
INVDATE_CREATEDATE_MINUS2 = '15'
INVDATE_CREATEDATE_MINUS3 = '16'
INVDATE_CREATEDATE_MINUS4 = '17'
