language: python
python:
  - "3.5"
  - "3.5-dev"
  - "nightly"
install:
  - "sudo apt-get -qq update"
  - "sudo apt-get -y install libsdl1.2-dev"
  - "pip install -r requirements/tests.txt"
  - "pip install ."
script: py.test
