database:
    type: gs
    apiKey: AIzaSyCLQbp5X2B4SWzBw-sz9rUnGHNSdMl0Yx8
    authDomain: "studio-ed756.firebaseapp.com"
    bucket: "studioml-meta"

    guest: true
    use_email_auth: false
    projectId: studio-ed756



storage:
    #type: s3
    #bucket: "studioml-artifacts"
    type: gcloud
    bucket: studio-ed756.appspot.com

   

queue: local

saveWorkspaceFrequency: 1m
verbose: error

cloud:
    type: google
    zone: us-central1-f

    cpus: 2
    ram:  3g
    hdd:  10g
    gpus: 0

sleep_time: 1
worker_timeout: 30

optimizer:
    cmaes_config:
        popsize: 100
        sigma0: 0.25
        load_best_only: false
    load_checkpoint_file:
    visualization: true
    result_dir: "~/Desktop/"
    checkpoint_interval: 0
    termination_criterion:
        generation: 5
        fitness: 999
        skip_gen_thres: 1.0
        skip_gen_timeout: 30
