language: python

python:
  - "3.5"
  - "3.6"

addons:
  apt:
    sources:
    # travis runs ubuntu 14.04 which ships with protobuf 2.5.
    # Python 3 support wasn't included until 2.6
    - sourceline: ppa:5-james-t/protobuf-ppa
    packages:
    - protobuf-compiler
    - python-protobuf
    - libprotobuf-dev

install:
  - protoc -I . -I /usr/include --python_out . ./demoparser/protobufs/*.proto
  - pip install cython tox-travis

script: tox

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      script: tox -e lint
