# coding: utf-8

"""
    bl-db-product

    This is a API document for Product DB

    OpenAPI spec version: 0.0.1
    Contact: master@bluehack.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class UpdateProductResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'product_id': 'str',
        'modified_count': 'int',
        'created_count': 'int',
        'message': 'str'
    }

    attribute_map = {
        'product_id': 'product_id',
        'modified_count': 'modified_count',
        'created_count': 'created_count',
        'message': 'message'
    }

    def __init__(self, product_id=None, modified_count=None, created_count=None, message=None):
        """
        UpdateProductResponse - a model defined in Swagger
        """

        self._product_id = None
        self._modified_count = None
        self._created_count = None
        self._message = None

        if product_id is not None:
          self.product_id = product_id
        if modified_count is not None:
          self.modified_count = modified_count
        if created_count is not None:
          self.created_count = created_count
        if message is not None:
          self.message = message

    @property
    def product_id(self):
        """
        Gets the product_id of this UpdateProductResponse.

        :return: The product_id of this UpdateProductResponse.
        :rtype: str
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id):
        """
        Sets the product_id of this UpdateProductResponse.

        :param product_id: The product_id of this UpdateProductResponse.
        :type: str
        """

        self._product_id = product_id

    @property
    def modified_count(self):
        """
        Gets the modified_count of this UpdateProductResponse.

        :return: The modified_count of this UpdateProductResponse.
        :rtype: int
        """
        return self._modified_count

    @modified_count.setter
    def modified_count(self, modified_count):
        """
        Sets the modified_count of this UpdateProductResponse.

        :param modified_count: The modified_count of this UpdateProductResponse.
        :type: int
        """

        self._modified_count = modified_count

    @property
    def created_count(self):
        """
        Gets the created_count of this UpdateProductResponse.

        :return: The created_count of this UpdateProductResponse.
        :rtype: int
        """
        return self._created_count

    @created_count.setter
    def created_count(self, created_count):
        """
        Sets the created_count of this UpdateProductResponse.

        :param created_count: The created_count of this UpdateProductResponse.
        :type: int
        """

        self._created_count = created_count

    @property
    def message(self):
        """
        Gets the message of this UpdateProductResponse.

        :return: The message of this UpdateProductResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """
        Sets the message of this UpdateProductResponse.

        :param message: The message of this UpdateProductResponse.
        :type: str
        """

        self._message = message

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, UpdateProductResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
