client_config_backend: settings
client_config:
  client_id: 477804483820-dtfgvn126k57ke7ogbdjj7lkkif520o4.apps.googleusercontent.com
  client_secret: sOpWCDWzskkxDZKktCIHTPfW

save_credentials: True
save_credentials_backend: file
save_credentials_file: gdrive_credentials.txt

get_refresh_token: False