---
- name: "Get topology output data"
  rundb:
    conn_str: "{{ rundb_conn }}"
    operation: get
    table: "{{ target }}"
    key: "outputs"
    run_id: "{{ orig_run_id }}"
  register: topo_output

- name: "set topo_output_resources fact"
  set_fact:
    topo_output_resources: "{{ topo_output.output[0]['resources'] }}"

- name: debug topo_output_resources
  debug:
    var: topo_output_resources

- name: "init job_ids"
  set_fact:
    job_ids: []

- name: "build job_id list"
  set_fact:
    job_ids: "{{ job_ids + [ 'J:' + fact_item['id'] ] }}"
  with_items: "{{ topo_output_resources }}"
  loop_control:
    loop_var: fact_item

#- name: job_ids
#  debug:
#    var: job_ids

- name: "make ids a dict"
  set_fact:
    just_ids: {"ids": "{{ job_ids }}"}

- name: "combine dicts"
  set_fact:
   combined:  "{{ recipeset | combine(just_ids) }}"
  with_items:
    - "{{ res_grp['recipesets'] }}"
  loop_control:
    loop_var: recipeset

- name: combined
  debug:
    var: combined

- name: "teardown beaker systems"
  bkr_server:
    recipesets: "[ {{ combined }} ]"
    state: absent
    job_group: "{{ res_grp['job_group'] | default('') }}"
