matrix:
  include:
    - os: linux
      env: SCRIPT=ubuntu
      services: docker
    - os: linux
      env: SCRIPT=debian
      services: docker
    - os: linux
      env: SCRIPT=fedora
      services: docker
    - os: osx
      env: SCRIPT=osx

script:
  - $TRAVIS_BUILD_DIR/.travis/${SCRIPT}.sh
