
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-23T21:35:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "dd3870e8ee370a295f2d09b7782835a8d61369b5",
 "version": "0.1.41"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
