
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "615100fe5d04be987eb68056c5cbe3c1551a7b3d",
 "version": "3.0.0b3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
