# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toktokkie/ui/qt/qt_designer/tv_series_renamer.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TVSeriesRenamer(object):
    def setupUi(self, TVSeriesRenamer):
        TVSeriesRenamer.setObjectName("TVSeriesRenamer")
        TVSeriesRenamer.resize(486, 348)
        self.centralwidget = QtWidgets.QWidget(TVSeriesRenamer)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.browse_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_button.sizePolicy().hasHeightForWidth())
        self.browse_button.setSizePolicy(sizePolicy)
        self.browse_button.setObjectName("browse_button")
        self.gridLayout.addWidget(self.browse_button, 0, 0, 1, 1)
        self.rename_list = QtWidgets.QTreeWidget(self.centralwidget)
        self.rename_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.rename_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.rename_list.setObjectName("rename_list")
        self.gridLayout.addWidget(self.rename_list, 2, 0, 1, 8)
        self.selection_remover_button = QtWidgets.QPushButton(self.centralwidget)
        self.selection_remover_button.setMaximumSize(QtCore.QSize(156, 16777215))
        self.selection_remover_button.setObjectName("selection_remover_button")
        self.gridLayout.addWidget(self.selection_remover_button, 3, 6, 1, 2)
        self.meta_warning_label = QtWidgets.QLabel(self.centralwidget)
        self.meta_warning_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.meta_warning_label.setWordWrap(True)
        self.meta_warning_label.setObjectName("meta_warning_label")
        self.gridLayout.addWidget(self.meta_warning_label, 3, 0, 1, 5)
        self.scheme_selector = QtWidgets.QComboBox(self.centralwidget)
        self.scheme_selector.setMinimumSize(QtCore.QSize(200, 0))
        self.scheme_selector.setObjectName("scheme_selector")
        self.gridLayout.addWidget(self.scheme_selector, 1, 1, 1, 4)
        self.directory_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.directory_entry.setObjectName("directory_entry")
        self.gridLayout.addWidget(self.directory_entry, 0, 1, 1, 7)
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_button.sizePolicy().hasHeightForWidth())
        self.cancel_button.setSizePolicy(sizePolicy)
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout.addWidget(self.cancel_button, 1, 6, 1, 1)
        self.recursive_check = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recursive_check.sizePolicy().hasHeightForWidth())
        self.recursive_check.setSizePolicy(sizePolicy)
        self.recursive_check.setObjectName("recursive_check")
        self.gridLayout.addWidget(self.recursive_check, 1, 0, 1, 1)
        self.confirm_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirm_button.sizePolicy().hasHeightForWidth())
        self.confirm_button.setSizePolicy(sizePolicy)
        self.confirm_button.setObjectName("confirm_button")
        self.gridLayout.addWidget(self.confirm_button, 1, 7, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 5, 1, 1)
        TVSeriesRenamer.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TVSeriesRenamer)
        self.statusbar.setObjectName("statusbar")
        TVSeriesRenamer.setStatusBar(self.statusbar)

        self.retranslateUi(TVSeriesRenamer)
        QtCore.QMetaObject.connectSlotsByName(TVSeriesRenamer)

    def retranslateUi(self, TVSeriesRenamer):
        _translate = QtCore.QCoreApplication.translate
        TVSeriesRenamer.setWindowTitle(_translate("TVSeriesRenamer", "TV Series Renamer"))
        self.browse_button.setToolTip(_translate("TVSeriesRenamer", "<html><head/><body><p>Browse for a directory on your PC</p></body></html>"))
        self.browse_button.setText(_translate("TVSeriesRenamer", "Browse"))
        self.rename_list.headerItem().setText(0, _translate("TVSeriesRenamer", "Old Name"))
        self.rename_list.headerItem().setText(1, _translate("TVSeriesRenamer", "New Name"))
        self.selection_remover_button.setToolTip(_translate("TVSeriesRenamer", "<html><head/><body><p>Removes all selected entries from the list</p></body></html>"))
        self.selection_remover_button.setText(_translate("TVSeriesRenamer", "Remove Selection"))
        self.meta_warning_label.setText(_translate("TVSeriesRenamer", "<html><head/><body><p><span style=\" color:#ff0000;\">Warning: Selected Directory does not contain any .meta subdirectories with type \'tv_series\'</span></p></body></html>"))
        self.scheme_selector.setToolTip(_translate("TVSeriesRenamer", "<html><head/><body><p>The naming scheme used for renaming the episodes</p></body></html>"))
        self.directory_entry.setToolTip(_translate("TVSeriesRenamer", "<html><head/><body><p>The Path to the directory is specified here</p></body></html>"))
        self.cancel_button.setToolTip(_translate("TVSeriesRenamer", "<html><head/><body><p>Resets all input fields.</p></body></html>"))
        self.cancel_button.setText(_translate("TVSeriesRenamer", "Cancel"))
        self.recursive_check.setToolTip(_translate("TVSeriesRenamer", "<html><head/><body><p>If checked, all directories below the selected directory are taken into consideration.</p></body></html>"))
        self.recursive_check.setText(_translate("TVSeriesRenamer", "Recursive"))
        self.confirm_button.setToolTip(_translate("TVSeriesRenamer", "<html><head/><body><p>Starts renaming the files in the list below.</p></body></html>"))
        self.confirm_button.setText(_translate("TVSeriesRenamer", "Confirm"))

