# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toktokkie/ui/qt/qt_designer/light_novel_config.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LightNovelConfig(object):
    def setupUi(self, LightNovelConfig):
        LightNovelConfig.setObjectName("LightNovelConfig")
        LightNovelConfig.resize(989, 700)
        self.gridLayout = QtWidgets.QGridLayout(LightNovelConfig)
        self.gridLayout.setObjectName("gridLayout")
        self.series_name_edit = QtWidgets.QLineEdit(LightNovelConfig)
        self.series_name_edit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.series_name_edit.sizePolicy().hasHeightForWidth())
        self.series_name_edit.setSizePolicy(sizePolicy)
        self.series_name_edit.setMinimumSize(QtCore.QSize(134, 0))
        self.series_name_edit.setFrame(False)
        self.series_name_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.series_name_edit.setObjectName("series_name_edit")
        self.gridLayout.addWidget(self.series_name_edit, 1, 0, 1, 1)
        self.folder_icon_label = QtWidgets.QLabel(LightNovelConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folder_icon_label.sizePolicy().hasHeightForWidth())
        self.folder_icon_label.setSizePolicy(sizePolicy)
        self.folder_icon_label.setMaximumSize(QtCore.QSize(420, 600))
        self.folder_icon_label.setText("")
        self.folder_icon_label.setPixmap(QtGui.QPixmap("../../../../../../../Downloads/main.jpg"))
        self.folder_icon_label.setScaledContents(True)
        self.folder_icon_label.setAlignment(QtCore.Qt.AlignCenter)
        self.folder_icon_label.setObjectName("folder_icon_label")
        self.gridLayout.addWidget(self.folder_icon_label, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(LightNovelConfig)
        self.frame.setEnabled(True)
        self.frame.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.media_type_combo_box = QtWidgets.QComboBox(self.frame)
        self.media_type_combo_box.setObjectName("media_type_combo_box")
        self.gridLayout_2.addWidget(self.media_type_combo_box, 0, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 8, 0, 1, 1)
        self.author_edit = QtWidgets.QLineEdit(self.frame)
        self.author_edit.setText("")
        self.author_edit.setObjectName("author_edit")
        self.gridLayout_2.addWidget(self.author_edit, 2, 1, 1, 2)
        self.isbn_edit = QtWidgets.QLineEdit(self.frame)
        self.isbn_edit.setText("")
        self.isbn_edit.setObjectName("isbn_edit")
        self.gridLayout_2.addWidget(self.isbn_edit, 4, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.novelupdates_url_button = QtWidgets.QPushButton(self.frame)
        self.novelupdates_url_button.setObjectName("novelupdates_url_button")
        self.gridLayout_2.addWidget(self.novelupdates_url_button, 7, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 7, 0, 1, 1)
        self.official_translation_check = QtWidgets.QCheckBox(self.frame)
        self.official_translation_check.setObjectName("official_translation_check")
        self.gridLayout_2.addWidget(self.official_translation_check, 5, 0, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 4, 0, 1, 1)
        self.myanimelist_url_button = QtWidgets.QPushButton(self.frame)
        self.myanimelist_url_button.setObjectName("myanimelist_url_button")
        self.gridLayout_2.addWidget(self.myanimelist_url_button, 6, 2, 1, 1)
        self.myanimelist_url_edit = QtWidgets.QLineEdit(self.frame)
        self.myanimelist_url_edit.setObjectName("myanimelist_url_edit")
        self.gridLayout_2.addWidget(self.myanimelist_url_edit, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.status_label = QtWidgets.QLabel(self.frame_2)
        self.status_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_label.setText("")
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setObjectName("status_label")
        self.gridLayout_3.addWidget(self.status_label, 1, 1, 1, 1)
        self.published_label = QtWidgets.QLabel(self.frame_2)
        self.published_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.published_label.setText("")
        self.published_label.setAlignment(QtCore.Qt.AlignCenter)
        self.published_label.setObjectName("published_label")
        self.gridLayout_3.addWidget(self.published_label, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 6, 0, 1, 1)
        self.fully_translated_label = QtWidgets.QLabel(self.frame_2)
        self.fully_translated_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fully_translated_label.setText("")
        self.fully_translated_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fully_translated_label.setWordWrap(False)
        self.fully_translated_label.setObjectName("fully_translated_label")
        self.gridLayout_3.addWidget(self.fully_translated_label, 6, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.volume_count_label = QtWidgets.QLabel(self.frame_2)
        self.volume_count_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.volume_count_label.setText("")
        self.volume_count_label.setAlignment(QtCore.Qt.AlignCenter)
        self.volume_count_label.setObjectName("volume_count_label")
        self.gridLayout_3.addWidget(self.volume_count_label, 0, 1, 1, 1)
        self.mal_score_label = QtWidgets.QLabel(self.frame_2)
        self.mal_score_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mal_score_label.setText("")
        self.mal_score_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mal_score_label.setObjectName("mal_score_label")
        self.gridLayout_3.addWidget(self.mal_score_label, 7, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 8, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 4, 0, 1, 1)
        self.genres_label = QtWidgets.QLabel(self.frame_2)
        self.genres_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.genres_label.setText("")
        self.genres_label.setAlignment(QtCore.Qt.AlignCenter)
        self.genres_label.setWordWrap(True)
        self.genres_label.setObjectName("genres_label")
        self.gridLayout_3.addWidget(self.genres_label, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 7, 0, 1, 1)
        self.mal_ranking_label = QtWidgets.QLabel(self.frame_2)
        self.mal_ranking_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mal_ranking_label.setText("")
        self.mal_ranking_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mal_ranking_label.setObjectName("mal_ranking_label")
        self.gridLayout_3.addWidget(self.mal_ranking_label, 8, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 5, 0, 1, 1)
        self.licensed_label = QtWidgets.QLabel(self.frame_2)
        self.licensed_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.licensed_label.setText("")
        self.licensed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.licensed_label.setObjectName("licensed_label")
        self.gridLayout_3.addWidget(self.licensed_label, 5, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 9, 0, 1, 3)
        self.tags_edit = QtWidgets.QLineEdit(self.frame)
        self.tags_edit.setText("")
        self.tags_edit.setObjectName("tags_edit")
        self.gridLayout_2.addWidget(self.tags_edit, 1, 1, 1, 2)
        self.novelupdates_url_edit = QtWidgets.QLineEdit(self.frame)
        self.novelupdates_url_edit.setObjectName("novelupdates_url_edit")
        self.gridLayout_2.addWidget(self.novelupdates_url_edit, 7, 1, 1, 1)
        self.confirm_changes_button = QtWidgets.QPushButton(self.frame)
        self.confirm_changes_button.setObjectName("confirm_changes_button")
        self.gridLayout_2.addWidget(self.confirm_changes_button, 10, 0, 1, 3)
        self.illustrator_edit = QtWidgets.QLineEdit(self.frame)
        self.illustrator_edit.setObjectName("illustrator_edit")
        self.gridLayout_2.addWidget(self.illustrator_edit, 3, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 1, 7, 1)
        self.open_directory_button = QtWidgets.QPushButton(LightNovelConfig)
        self.open_directory_button.setObjectName("open_directory_button")
        self.gridLayout.addWidget(self.open_directory_button, 5, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 0, 1, 1)

        self.retranslateUi(LightNovelConfig)
        QtCore.QMetaObject.connectSlotsByName(LightNovelConfig)
        LightNovelConfig.setTabOrder(self.series_name_edit, self.media_type_combo_box)
        LightNovelConfig.setTabOrder(self.media_type_combo_box, self.tags_edit)
        LightNovelConfig.setTabOrder(self.tags_edit, self.author_edit)
        LightNovelConfig.setTabOrder(self.author_edit, self.isbn_edit)
        LightNovelConfig.setTabOrder(self.isbn_edit, self.official_translation_check)
        LightNovelConfig.setTabOrder(self.official_translation_check, self.myanimelist_url_edit)
        LightNovelConfig.setTabOrder(self.myanimelist_url_edit, self.myanimelist_url_button)
        LightNovelConfig.setTabOrder(self.myanimelist_url_button, self.novelupdates_url_edit)
        LightNovelConfig.setTabOrder(self.novelupdates_url_edit, self.novelupdates_url_button)
        LightNovelConfig.setTabOrder(self.novelupdates_url_button, self.confirm_changes_button)
        LightNovelConfig.setTabOrder(self.confirm_changes_button, self.open_directory_button)

    def retranslateUi(self, LightNovelConfig):
        _translate = QtCore.QCoreApplication.translate
        LightNovelConfig.setWindowTitle(_translate("LightNovelConfig", "Form"))
        self.series_name_edit.setText(_translate("LightNovelConfig", "Series Name"))
        self.label.setText(_translate("LightNovelConfig", "myanimelist.net"))
        self.label_3.setText(_translate("LightNovelConfig", "Tags"))
        self.novelupdates_url_button.setText(_translate("LightNovelConfig", "Go"))
        self.label_2.setText(_translate("LightNovelConfig", "novelupdates.com"))
        self.official_translation_check.setText(_translate("LightNovelConfig", "Official Translation?"))
        self.label_7.setText(_translate("LightNovelConfig", "ISBN"))
        self.myanimelist_url_button.setText(_translate("LightNovelConfig", "Go"))
        self.label_4.setText(_translate("LightNovelConfig", "Media Type"))
        self.label_6.setText(_translate("LightNovelConfig", "Author"))
        self.label_17.setText(_translate("LightNovelConfig", "Volumes"))
        self.label_16.setText(_translate("LightNovelConfig", "Fully Translated"))
        self.label_10.setText(_translate("LightNovelConfig", "Published"))
        self.label_20.setText(_translate("LightNovelConfig", "myanimelist.net Ranking"))
        self.label_18.setText(_translate("LightNovelConfig", "Genres"))
        self.label_8.setText(_translate("LightNovelConfig", "Status"))
        self.label_19.setText(_translate("LightNovelConfig", "myanimelist.net Score"))
        self.label_14.setText(_translate("LightNovelConfig", "Licensed"))
        self.confirm_changes_button.setText(_translate("LightNovelConfig", "Confirm Changes"))
        self.label_5.setText(_translate("LightNovelConfig", "Illustrator"))
        self.open_directory_button.setText(_translate("LightNovelConfig", "Open Directory"))

