
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7cfcd88a56a9b61330ba247dd28e30dd2e505fcd",
 "version": "1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
