#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

extras_require = \
{":python_version < '3.5'": ['typing']}

setup(name='logbind',
      version='2017.11.7',
      description='logbind',
      author='Caleb Hattingh',
      author_email='caleb.hattingh@gmail.com',
      url='https://github.com/cjrh/logbind',
      py_modules=['logbind'],
      extras_require=extras_require,
     )
