# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-24 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_import', '0017_auto_20171124_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ymlimportproperty',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterUniqueTogether(
            name='ymlimportproperty',
            unique_together=set([('category', 'title')]),
        ),
    ]
