---
- name: "Gather facts"
  setup:
    filter: ansible_*

- name: "declaring output vars"
  set_fact:
    topology_outputs_libvirt_nodes: []

- name: "Initiating libvirt resource group"
  include: provision_resource_group.yml res_grp={{ item }}
  with_items:
    - "{{ libvirt_res_grps }}"
  register: resource_grps_output
