
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-02T17:15:33-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "37b4b7cc32ff3984647bb2a2b726513ae3921951",
 "version": "1.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
