
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "058578113c7814a1c70ea19916d7c8dd8d311d05",
 "version": "0.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
