# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_simple_auth', '0002_auto_20170802_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
