language: python
python:
- 3.5
- 3.6
install:
- pip install pytest pytest-cov
script:
- py.test --cov test_skeleton --cov-report term-missing --tb=native
notifications:
  slack:
    secure: mMQ+rRTo7/ieqTMicQ8jPnmFnLog0efYqA0yRIpAJ+fYhUppI4eb95fEvHGxlTiYiBrM7eKYyh6DHOn6rcUOcWAXsqOKiDhMJOAGMvJ+sk6dGcsmLomxCdqJIT6F0LmbcaccEtzh72sb3KjCKTqDZcbVFPxHuRiPwqFWsvtIHo6htgjN1dsF7DEitIC58Vp7f9wgPz5ERXlambHhffsFoQLNeRN9OO3gv7MKLN1+EEEmxQqVh4v8Vriovpwdfb64ZgukDqjfWyqo4yCrgP328CjvDf1q3vnJ1xo9EuNND5sB8v3r87uqzCrou5XS8YKNl0i2431rh9tIg6ROCKka5tbxLWIDMMBEKWZIJ8bH6kWDuBYg72WHK2jXzg/HuQBSd3OOFHEfVyQ4e8ViRMNO46p+qyHCsUur9PvAjh2yGNuyOqxxiFIIHkGOcKU+PQnBOzhyLbNk9dLQZRcbcxwml/s5YHdiONlQ4BDzjj3NR2Jvl8BGPjRCFFcgr16LtYqRjd16cTVFmKxS6heisXkMUwu7IoFc19GoHdI/gbl+84Y8dsWT82kwVBnnKZdqfzO97T9dTU8mmBvW7SOTe5QYzrCIrNCUWjXkhIzFC6ctEjbkA6sjmhvYaUbvfX9gSNkc0XhauaxlYtlJ4FAqDNT1AVMRQo7U9eccL+zMj74Mcpk=
deploy:
  provider: pypi
  user: jerry-pypi
  password:
    secure: D/jcyHA1ytj2B3qU4YnStlpj69DtLw1NuLLL9DJfctg+ylex71hphzEPuh0GurxSCFTI7z5wyP+joRDIPvIec1+zRDADjZYd3aTMRv6RdUfkTenEcMHBm0bwfo727n241lXVpMmlA5ufMQaXimZJtkhsoj2T95ncqd8DUInENxs3WLtdQQJhMGPhIj2CTTsBKQX4xDW2TYOBZ9A7g1ZwOrwuZRdKkG1nqJHTPd57OmvAOCLNorT6k3bJjmxYby1B2mG5TYo+29kKWdY6KIKH4dvRHKA93YAA5t5nYfB6knX2N1n/fXs+zPt2lEvm440+WMbdeTahU7hOYqElbSjTRv2D/TujtLxoFgNMjBKPXgJc21dLaNZiLPmy4qrtIw1H+jy9YZWAgkzv3YbeTYkRttJgUe8iqml/e8Y1+ATpFPmZE9BB4KW2AGWsxyBX8/75xx8171AKkE/RGhqf1KEjSDqpugkfr7IGKshMDpTAxpQBhN3YSSxf+v5WBYbP6Si8CwfbDEP/j1ub4xSc8jt6bdUr2QJokKcEy+b9L94797dqI7IaSs+6EiUk8QPlkUrokBXR+nKhTnJx56/UYAIfSDZPE8tEvHyXg4fL1Ox7p63ASkkZbI++ex88euxRSpjIhcKYZGeNXhGegmzd+S/s00cjZzKSnGesTeOj7TeoAfs=
  on:
    tags: true
    python: 3.6

