
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-01-03T07:02:07-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "892d2daf41fc3e6960517d1c7881051ef7ab9f9a",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
