
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-25T23:49:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0d36570eab42fe6e9352047af7da878afa75b57e",
 "version": "0.1.67"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
