
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-11-28T17:10:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "905479df1b28b41cb9cebc06c12f01f1bbc4f252",
 "version": "0.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
