
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-11T11:19:37+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "620ece55b27ead06c647ba1a3da5ffc54734ece6",
 "version": "0.52"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
