---
# This playbook will initiate provisioning for the oVirt resources groups.
- name: "DEBUG:: oVirt resource group list"
  debug:
    msg: "Currently Provisioning/Deprovisioning the resources under list ovirt_res_grps {{ ovirt_res_grps }}"

- name: "Declaring output vars"
  set_fact:
    topology_outputs_ovirt_vms: []

- name: "Initiating Provisioning/Deprovisioning of resources oVirt resource group"
  include: provision_resource_group.yml res_grp={{ item }}
  with_items:
    - "{{ ovirt_res_grps }}"
  register: resource_grps_output
