# The RabbitMQ host. Defaults to localhost. Optional.
#rabbit-host: localhost

# The RabbitMQ port. Defaults to 5672. Optional.
#rabbit-port: 5672

# Reverse caching proxy address. May be a domain name, IP address and also a
# port. Defaults to localhost. Optional.
#proxy-address: localhost

# If proxy handles multiple domains then proxy-address is typically
# localhost. Setting the domain sends an extra header identifying the correct
# site. Optional.
#domain: my.site.com

# Debug logging. This can be expensive.
#logfile: /tmp/purge.log
