
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-17T15:24:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "154f1490b5f14bcdf5614b9fd68cda657c93bc51",
 "version": "0.1.58"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
