language: python

python:
  - "2.7"

before_install:
  - pip install .
  - pip install twine --upgrade

script:
  - python -m benchpress.testing

deploy:
  provider: pypi
  user: $TWINE_USERNAME
  password: $TWINE_PASSWORD

deploy:
  provider: script
  script: python setup.py sdist && twine upload --help && echo $TWINE_USERNAME && twine upload dist/*
  on:
    branch: master
