
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-11-23T18:41:51+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c2c5a84c669888b00716365d5ef27dfa4cbb685b",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
