
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-01-04T11:18:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6b1ee7704baf68ecf01b24d9a879f07e71a181b2",
 "version": "1.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
