
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-13T18:08:13+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e7357257e228e52c1ff57da7fada72bc3edadcdf",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
