
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-27T05:19:49+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "95beb26b50f7b20fc837aceb1423b007377cb9ce",
 "version": "0.1.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
