
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-17T05:22:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b4033e16f82324cc93c9e701c0911fa00005d2c4",
 "version": "0.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
