
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-01-03T00:39:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b8ae4d16842e1370a356a85bb66b1fb8f662b34d",
 "version": "0.1.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
