/* Generated by Cython 0.25.1 */

#ifndef __PYX_HAVE__pycalphad__core__eqsolver
#define __PYX_HAVE__pycalphad__core__eqsolver

struct CompositionSetObject;

/* "pycalphad/core/eqsolver.pyx":28
 * cdef double MAX_ENERGY = BIGNUM
 * 
 * cdef public class CompositionSet(object)[type CompositionSetType, object CompositionSetObject]:             # <<<<<<<<<<<<<<
 *     cdef public PhaseRecord phase_record
 *     cdef readonly double[::1] dof, X
 */
struct CompositionSetObject {
  PyObject_HEAD
  struct __pyx_vtabstruct_9pycalphad_4core_8eqsolver_CompositionSet *__pyx_vtab;
  struct PhaseRecordObject *phase_record;
  __Pyx_memviewslice dof;
  __Pyx_memviewslice X;
  __Pyx_memviewslice _dof_2d_view;
  __Pyx_memviewslice _X_2d_view;
  __Pyx_memviewslice mass_grad;
  __Pyx_memviewslice mass_hess;
  double NP;
  double energy;
  __Pyx_memviewslice _energy_2d_view;
  __Pyx_memviewslice grad;
  __Pyx_memviewslice hess;
  __Pyx_memviewslice _prev_dof;
  double _prev_energy;
  __Pyx_memviewslice _prev_grad;
  __Pyx_memviewslice _prev_hess;
  int _first_iteration;
};

#ifndef __PYX_HAVE_API__pycalphad__core__eqsolver

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) CompositionSetType;

#endif /* !__PYX_HAVE_API__pycalphad__core__eqsolver */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initeqsolver(void);
#else
PyMODINIT_FUNC PyInit_eqsolver(void);
#endif

#endif /* !__PYX_HAVE__pycalphad__core__eqsolver */
