
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-20T17:19:05+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "31ae549f0eb6d87c0f9b1ba999a43f6500abbffe",
 "version": "0.1.61"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
