---
- name: "declaring output vars"
  set_fact:
    topology_outputs_dummy: []

#- name: "DEBUG dummy_res_grps"
#  debug:
#    var: dummy_res_grps

- name: "Initiating Provisioning of dummy resource group"
  include: provision_resource_group.yml res_grp={{ item }}
  with_items:
    - "{{ dummy_res_grps }}"
  when: state == "present"

- name: "Initiating Teardown of dummy resource group"
  include: teardown_resource_group.yml res_grp={{ item }}
  with_items:
    - "{{ dummy_res_grps }}"
  when: state == "absent"
