
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-24T21:42:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a202a168cb9bce6549d74b1669e1e2e59b9c6338",
 "version": "0.1.64"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
