# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/intermake/intermake/hosts/frontends/gui_qt/designer/frm_maintenance_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1025, 891)
        Dialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.FRA_TITLE = QtWidgets.QFrame(Dialog)
        self.FRA_TITLE.setObjectName("FRA_TITLE")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.FRA_TITLE)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.TXT_TITLE_2 = QtWidgets.QLabel(self.FRA_TITLE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_TITLE_2.sizePolicy().hasHeightForWidth())
        self.TXT_TITLE_2.setSizePolicy(sizePolicy)
        self.TXT_TITLE_2.setMaximumSize(QtCore.QSize(24, 24))
        self.TXT_TITLE_2.setText("")
        self.TXT_TITLE_2.setPixmap(QtGui.QPixmap(":/images/resource_files/script.svg"))
        self.TXT_TITLE_2.setScaledContents(True)
        self.TXT_TITLE_2.setObjectName("TXT_TITLE_2")
        self.horizontalLayout_3.addWidget(self.TXT_TITLE_2)
        self.TXT_TITLE = QtWidgets.QLabel(self.FRA_TITLE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_TITLE.sizePolicy().hasHeightForWidth())
        self.TXT_TITLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.TXT_TITLE.setFont(font)
        self.TXT_TITLE.setObjectName("TXT_TITLE")
        self.horizontalLayout_3.addWidget(self.TXT_TITLE)
        self.verticalLayout.addWidget(self.FRA_TITLE)
        self.FRA_BASIC = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FRA_BASIC.sizePolicy().hasHeightForWidth())
        self.FRA_BASIC.setSizePolicy(sizePolicy)
        self.FRA_BASIC.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FRA_BASIC.setObjectName("FRA_BASIC")
        self.gridLayout = QtWidgets.QGridLayout(self.FRA_BASIC)
        self.gridLayout.setObjectName("gridLayout")
        self.PRG_BASIC = QtWidgets.QProgressBar(self.FRA_BASIC)
        self.PRG_BASIC.setProperty("value", 24)
        self.PRG_BASIC.setObjectName("PRG_BASIC")
        self.gridLayout.addWidget(self.PRG_BASIC, 1, 0, 1, 1)
        self.LBL_PLEASE_WAIT = QtWidgets.QLabel(self.FRA_BASIC)
        self.LBL_PLEASE_WAIT.setAlignment(QtCore.Qt.AlignCenter)
        self.LBL_PLEASE_WAIT.setObjectName("LBL_PLEASE_WAIT")
        self.gridLayout.addWidget(self.LBL_PLEASE_WAIT, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.FRA_BASIC)
        self.SPL_MAIN = QtWidgets.QSplitter(Dialog)
        self.SPL_MAIN.setOrientation(QtCore.Qt.Vertical)
        self.SPL_MAIN.setObjectName("SPL_MAIN")
        self.FRA_PROGRESS = QtWidgets.QFrame(self.SPL_MAIN)
        self.FRA_PROGRESS.setObjectName("FRA_PROGRESS")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.FRA_PROGRESS)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TXT_ESTIMATE = QtWidgets.QLabel(self.FRA_PROGRESS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_ESTIMATE.sizePolicy().hasHeightForWidth())
        self.TXT_ESTIMATE.setSizePolicy(sizePolicy)
        self.TXT_ESTIMATE.setObjectName("TXT_ESTIMATE")
        self.horizontalLayout.addWidget(self.TXT_ESTIMATE)
        spacerItem = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.BTN_ESTIMATE = QtWidgets.QToolButton(self.FRA_PROGRESS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_ESTIMATE.sizePolicy().hasHeightForWidth())
        self.BTN_ESTIMATE.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/resource_files/dropdown.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_ESTIMATE.setIcon(icon)
        self.BTN_ESTIMATE.setObjectName("BTN_ESTIMATE")
        self.horizontalLayout.addWidget(self.BTN_ESTIMATE)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.BTN_AUTOCLOSE = QtWidgets.QToolButton(self.FRA_PROGRESS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_AUTOCLOSE.sizePolicy().hasHeightForWidth())
        self.BTN_AUTOCLOSE.setSizePolicy(sizePolicy)
        self.BTN_AUTOCLOSE.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/resource_files/automatic.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_AUTOCLOSE.setIcon(icon1)
        self.BTN_AUTOCLOSE.setCheckable(True)
        self.BTN_AUTOCLOSE.setObjectName("BTN_AUTOCLOSE")
        self.horizontalLayout.addWidget(self.BTN_AUTOCLOSE)
        self.BTN_SCROLL = QtWidgets.QToolButton(self.FRA_PROGRESS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_SCROLL.sizePolicy().hasHeightForWidth())
        self.BTN_SCROLL.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/resource_files/autoscroll.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_SCROLL.setIcon(icon2)
        self.BTN_SCROLL.setCheckable(True)
        self.BTN_SCROLL.setObjectName("BTN_SCROLL")
        self.horizontalLayout.addWidget(self.BTN_SCROLL)
        self.BTN_SHOW_PROGRESS = QtWidgets.QToolButton(self.FRA_PROGRESS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_SHOW_PROGRESS.sizePolicy().hasHeightForWidth())
        self.BTN_SHOW_PROGRESS.setSizePolicy(sizePolicy)
        self.BTN_SHOW_PROGRESS.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/resource_files/maximise.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_SHOW_PROGRESS.setIcon(icon3)
        self.BTN_SHOW_PROGRESS.setCheckable(True)
        self.BTN_SHOW_PROGRESS.setObjectName("BTN_SHOW_PROGRESS")
        self.horizontalLayout.addWidget(self.BTN_SHOW_PROGRESS)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.TVW_LOG = QtWidgets.QTreeWidget(self.FRA_PROGRESS)
        self.TVW_LOG.setObjectName("TVW_LOG")
        self.TVW_LOG.headerItem().setText(0, "1")
        self.verticalLayout_2.addWidget(self.TVW_LOG)
        self.FRA_MESSAGES = QtWidgets.QFrame(self.SPL_MAIN)
        self.FRA_MESSAGES.setObjectName("FRA_MESSAGES")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.FRA_MESSAGES)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.TXT_ESTIMATE_2 = QtWidgets.QLabel(self.FRA_MESSAGES)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TXT_ESTIMATE_2.sizePolicy().hasHeightForWidth())
        self.TXT_ESTIMATE_2.setSizePolicy(sizePolicy)
        self.TXT_ESTIMATE_2.setObjectName("TXT_ESTIMATE_2")
        self.horizontalLayout_4.addWidget(self.TXT_ESTIMATE_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.BTN_SCROLL_OUTPUT = QtWidgets.QToolButton(self.FRA_MESSAGES)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_SCROLL_OUTPUT.sizePolicy().hasHeightForWidth())
        self.BTN_SCROLL_OUTPUT.setSizePolicy(sizePolicy)
        self.BTN_SCROLL_OUTPUT.setIcon(icon2)
        self.BTN_SCROLL_OUTPUT.setCheckable(True)
        self.BTN_SCROLL_OUTPUT.setObjectName("BTN_SCROLL_OUTPUT")
        self.horizontalLayout_4.addWidget(self.BTN_SCROLL_OUTPUT)
        self.BTN_SHOW_OUTPUT = QtWidgets.QToolButton(self.FRA_MESSAGES)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_SHOW_OUTPUT.sizePolicy().hasHeightForWidth())
        self.BTN_SHOW_OUTPUT.setSizePolicy(sizePolicy)
        self.BTN_SHOW_OUTPUT.setText("")
        self.BTN_SHOW_OUTPUT.setIcon(icon3)
        self.BTN_SHOW_OUTPUT.setCheckable(True)
        self.BTN_SHOW_OUTPUT.setObjectName("BTN_SHOW_OUTPUT")
        self.horizontalLayout_4.addWidget(self.BTN_SHOW_OUTPUT)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.TXT_MESSAGES = QtWidgets.QTextEdit(self.FRA_MESSAGES)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.TXT_MESSAGES.setFont(font)
        self.TXT_MESSAGES.setStyleSheet("background: black;\n"
"color: white;")
        self.TXT_MESSAGES.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.TXT_MESSAGES.setReadOnly(True)
        self.TXT_MESSAGES.setObjectName("TXT_MESSAGES")
        self.verticalLayout_3.addWidget(self.TXT_MESSAGES)
        self.verticalLayout.addWidget(self.SPL_MAIN)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BTN_DETAILS = QtWidgets.QPushButton(Dialog)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/resource_files/visualise.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_DETAILS.setIcon(icon4)
        self.BTN_DETAILS.setObjectName("BTN_DETAILS")
        self.horizontalLayout_2.addWidget(self.BTN_DETAILS)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.BTN_CANCEL = QtWidgets.QPushButton(Dialog)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/resource_files/checkno.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_CANCEL.setIcon(icon5)
        self.BTN_CANCEL.setAutoDefault(False)
        self.BTN_CANCEL.setObjectName("BTN_CANCEL")
        self.horizontalLayout_2.addWidget(self.BTN_CANCEL)
        self.BTN_CLOSE = QtWidgets.QPushButton(Dialog)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/resource_files/checkyes.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_CLOSE.setIcon(icon6)
        self.BTN_CLOSE.setAutoDefault(False)
        self.BTN_CLOSE.setDefault(True)
        self.BTN_CLOSE.setObjectName("BTN_CLOSE")
        self.horizontalLayout_2.addWidget(self.BTN_CLOSE)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.TXT_TITLE.setText(_translate("Dialog", "Text goes here"))
        self.LBL_PLEASE_WAIT.setText(_translate("Dialog", "<html><head/><body><h1><span style=\" font-family: Times New Roman;\">Please wait</span></h1></body></html>"))
        self.TXT_ESTIMATE.setText(_translate("Dialog", "Text goes here"))
        self.BTN_AUTOCLOSE.setToolTip(_translate("Dialog", "Close window when completed"))
        self.BTN_SCROLL.setToolTip(_translate("Dialog", "Autoscroll to new entries"))
        self.BTN_SHOW_PROGRESS.setToolTip(_translate("Dialog", "Expand view"))
        self.TXT_ESTIMATE_2.setText(_translate("Dialog", "Messages"))
        self.BTN_SCROLL_OUTPUT.setToolTip(_translate("Dialog", "Autoscroll to new entries"))
        self.BTN_SHOW_OUTPUT.setToolTip(_translate("Dialog", "Expand view"))
        self.BTN_DETAILS.setText(_translate("Dialog", "Show details"))
        self.BTN_CANCEL.setText(_translate("Dialog", "Cancel"))
        self.BTN_CLOSE.setText(_translate("Dialog", "Close"))


