# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _itkLabelStatisticsOpeningImageFilterPython.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_itkLabelStatisticsOpeningImageFilterPython')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_itkLabelStatisticsOpeningImageFilterPython')
    _itkLabelStatisticsOpeningImageFilterPython = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_itkLabelStatisticsOpeningImageFilterPython', [dirname(__file__)])
        except ImportError:
            import _itkLabelStatisticsOpeningImageFilterPython
            return _itkLabelStatisticsOpeningImageFilterPython
        try:
            _mod = imp.load_module('_itkLabelStatisticsOpeningImageFilterPython', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _itkLabelStatisticsOpeningImageFilterPython = swig_import_helper()
    del swig_import_helper
else:
    import _itkLabelStatisticsOpeningImageFilterPython
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


import itkImagePython
import stdcomplexPython
import pyBasePython
import itkCovariantVectorPython
import itkVectorPython
import vnl_vectorPython
import vnl_matrixPython
import vnl_vector_refPython
import itkFixedArrayPython
import itkRGBPixelPython
import itkImageRegionPython
import itkIndexPython
import itkOffsetPython
import itkSizePython
import ITKCommonBasePython
import itkMatrixPython
import vnl_matrix_fixedPython
import itkPointPython
import itkSymmetricSecondRankTensorPython
import itkRGBAPixelPython
import itkImageToImageFilterAPython
import itkImageSourcePython
import itkImageSourceCommonPython
import itkVectorImagePython
import itkVariableLengthVectorPython
import itkImageToImageFilterCommonPython

def itkLabelStatisticsOpeningImageFilterIUC3IF3_New():
  return itkLabelStatisticsOpeningImageFilterIUC3IF3.New()


def itkLabelStatisticsOpeningImageFilterIUC3IUC3_New():
  return itkLabelStatisticsOpeningImageFilterIUC3IUC3.New()


def itkLabelStatisticsOpeningImageFilterIUC3ISS3_New():
  return itkLabelStatisticsOpeningImageFilterIUC3ISS3.New()


def itkLabelStatisticsOpeningImageFilterIUC2IF2_New():
  return itkLabelStatisticsOpeningImageFilterIUC2IF2.New()


def itkLabelStatisticsOpeningImageFilterIUC2IUC2_New():
  return itkLabelStatisticsOpeningImageFilterIUC2IUC2.New()


def itkLabelStatisticsOpeningImageFilterIUC2ISS2_New():
  return itkLabelStatisticsOpeningImageFilterIUC2ISS2.New()

class itkLabelStatisticsOpeningImageFilterIUC2IF2(itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    """


    remove the objects according to the value of their statistics
    attribute

    LabelStatisticsOpeningImageFilter removes the objects in a labeled
    image with an attribute value smaller or greater than a threshold
    called Lambda. The attributes are the ones of the
    StatisticsLabelObject.

    Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA
    de Jouy-en-Josas, France.  This implementation was taken from the
    Insight Journal paper:https://hdl.handle.net/1926/584 orhttp://www
    .insight-journal.org/browse/publication/176

    See:   StatisticsLabelObject, BinaryStatisticsOpeningImageFilter,
    LabelShapeOpeningImageFilter

    C++ includes: itkLabelStatisticsOpeningImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__():
        """__New_orig__() -> itkLabelStatisticsOpeningImageFilterIUC2IF2_Pointer"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self):
        """Clone(itkLabelStatisticsOpeningImageFilterIUC2IF2 self) -> itkLabelStatisticsOpeningImageFilterIUC2IF2_Pointer"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_Clone(self)

    InputEqualityComparableCheck = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_InputEqualityComparableCheck
    IntConvertibleToInputCheck = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_IntConvertibleToInputCheck
    InputOStreamWritableCheck = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_InputOStreamWritableCheck

    def SetBackgroundValue(self, _arg):
        """
        SetBackgroundValue(itkLabelStatisticsOpeningImageFilterIUC2IF2 self, unsigned char const _arg)

        Set/Get the
        value used as "background" in the output image. Defaults to
        NumericTraits<PixelType>::NonpositiveMin(). 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_SetBackgroundValue(self, _arg)


    def GetBackgroundValue(self):
        """GetBackgroundValue(itkLabelStatisticsOpeningImageFilterIUC2IF2 self) -> unsigned char"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_GetBackgroundValue(self)


    def GetLambda(self):
        """
        GetLambda(itkLabelStatisticsOpeningImageFilterIUC2IF2 self) -> double

        Set/Get the threshold
        used to keep or remove the objects. 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_GetLambda(self)


    def SetLambda(self, _arg):
        """SetLambda(itkLabelStatisticsOpeningImageFilterIUC2IF2 self, double const _arg)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_SetLambda(self, _arg)


    def GetReverseOrdering(self):
        """
        GetReverseOrdering(itkLabelStatisticsOpeningImageFilterIUC2IF2 self) -> bool

        Set/Get the
        ordering of the objects. By default, the objects with an attribute
        value smaller than Lamba are removed. Turning ReverseOrdering to true
        make this filter remove the object with an attribute value greater
        than Lambda instead. 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_GetReverseOrdering(self)


    def SetReverseOrdering(self, _arg):
        """SetReverseOrdering(itkLabelStatisticsOpeningImageFilterIUC2IF2 self, bool const _arg)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_SetReverseOrdering(self, _arg)


    def ReverseOrderingOn(self):
        """ReverseOrderingOn(itkLabelStatisticsOpeningImageFilterIUC2IF2 self)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_ReverseOrderingOn(self)


    def ReverseOrderingOff(self):
        """ReverseOrderingOff(itkLabelStatisticsOpeningImageFilterIUC2IF2 self)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_ReverseOrderingOff(self)


    def GetAttribute(self):
        """
        GetAttribute(itkLabelStatisticsOpeningImageFilterIUC2IF2 self) -> unsigned int

        Set/Get the attribute
        to use to select the object to remove. The default is "Mean". 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_GetAttribute(self)


    def SetAttribute(self, *args):
        """
        SetAttribute(itkLabelStatisticsOpeningImageFilterIUC2IF2 self, unsigned int const _arg)
        SetAttribute(itkLabelStatisticsOpeningImageFilterIUC2IF2 self, std::string const & s)
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_SetAttribute(self, *args)


    def SetFeatureImage(self, input):
        """
        SetFeatureImage(itkLabelStatisticsOpeningImageFilterIUC2IF2 self, itkImageF2 input)

        Set the feature
        image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_SetFeatureImage(self, input)


    def GetFeatureImage(self):
        """
        GetFeatureImage(itkLabelStatisticsOpeningImageFilterIUC2IF2 self) -> itkImageF2

        Get the feature
        image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_GetFeatureImage(self)


    def SetInput1(self, input):
        """
        SetInput1(itkLabelStatisticsOpeningImageFilterIUC2IF2 self, itkImageUC2 input)

        Set the input image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_SetInput1(self, input)


    def SetInput2(self, input):
        """
        SetInput2(itkLabelStatisticsOpeningImageFilterIUC2IF2 self, itkImageF2 input)

        Set the feature image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_SetInput2(self, input)

    __swig_destroy__ = _itkLabelStatisticsOpeningImageFilterPython.delete_itkLabelStatisticsOpeningImageFilterIUC2IF2

    def cast(obj):
        """cast(itkLightObject obj) -> itkLabelStatisticsOpeningImageFilterIUC2IF2"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self):
        """GetPointer(itkLabelStatisticsOpeningImageFilterIUC2IF2 self) -> itkLabelStatisticsOpeningImageFilterIUC2IF2"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkLabelStatisticsOpeningImageFilterIUC2IF2

        Create a new object of the class itkLabelStatisticsOpeningImageFilterIUC2IF2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkLabelStatisticsOpeningImageFilterIUC2IF2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkLabelStatisticsOpeningImageFilterIUC2IF2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkLabelStatisticsOpeningImageFilterIUC2IF2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkLabelStatisticsOpeningImageFilterIUC2IF2.Clone = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_Clone, None, itkLabelStatisticsOpeningImageFilterIUC2IF2)
itkLabelStatisticsOpeningImageFilterIUC2IF2.SetBackgroundValue = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_SetBackgroundValue, None, itkLabelStatisticsOpeningImageFilterIUC2IF2)
itkLabelStatisticsOpeningImageFilterIUC2IF2.GetBackgroundValue = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_GetBackgroundValue, None, itkLabelStatisticsOpeningImageFilterIUC2IF2)
itkLabelStatisticsOpeningImageFilterIUC2IF2.GetLambda = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_GetLambda, None, itkLabelStatisticsOpeningImageFilterIUC2IF2)
itkLabelStatisticsOpeningImageFilterIUC2IF2.SetLambda = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_SetLambda, None, itkLabelStatisticsOpeningImageFilterIUC2IF2)
itkLabelStatisticsOpeningImageFilterIUC2IF2.GetReverseOrdering = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_GetReverseOrdering, None, itkLabelStatisticsOpeningImageFilterIUC2IF2)
itkLabelStatisticsOpeningImageFilterIUC2IF2.SetReverseOrdering = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_SetReverseOrdering, None, itkLabelStatisticsOpeningImageFilterIUC2IF2)
itkLabelStatisticsOpeningImageFilterIUC2IF2.ReverseOrderingOn = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_ReverseOrderingOn, None, itkLabelStatisticsOpeningImageFilterIUC2IF2)
itkLabelStatisticsOpeningImageFilterIUC2IF2.ReverseOrderingOff = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_ReverseOrderingOff, None, itkLabelStatisticsOpeningImageFilterIUC2IF2)
itkLabelStatisticsOpeningImageFilterIUC2IF2.GetAttribute = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_GetAttribute, None, itkLabelStatisticsOpeningImageFilterIUC2IF2)
itkLabelStatisticsOpeningImageFilterIUC2IF2.SetAttribute = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_SetAttribute, None, itkLabelStatisticsOpeningImageFilterIUC2IF2)
itkLabelStatisticsOpeningImageFilterIUC2IF2.SetFeatureImage = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_SetFeatureImage, None, itkLabelStatisticsOpeningImageFilterIUC2IF2)
itkLabelStatisticsOpeningImageFilterIUC2IF2.GetFeatureImage = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_GetFeatureImage, None, itkLabelStatisticsOpeningImageFilterIUC2IF2)
itkLabelStatisticsOpeningImageFilterIUC2IF2.SetInput1 = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_SetInput1, None, itkLabelStatisticsOpeningImageFilterIUC2IF2)
itkLabelStatisticsOpeningImageFilterIUC2IF2.SetInput2 = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_SetInput2, None, itkLabelStatisticsOpeningImageFilterIUC2IF2)
itkLabelStatisticsOpeningImageFilterIUC2IF2.GetPointer = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_GetPointer, None, itkLabelStatisticsOpeningImageFilterIUC2IF2)
itkLabelStatisticsOpeningImageFilterIUC2IF2_swigregister = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_swigregister
itkLabelStatisticsOpeningImageFilterIUC2IF2_swigregister(itkLabelStatisticsOpeningImageFilterIUC2IF2)

def itkLabelStatisticsOpeningImageFilterIUC2IF2___New_orig__():
    """itkLabelStatisticsOpeningImageFilterIUC2IF2___New_orig__() -> itkLabelStatisticsOpeningImageFilterIUC2IF2_Pointer"""
    return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2___New_orig__()

def itkLabelStatisticsOpeningImageFilterIUC2IF2_cast(obj):
    """itkLabelStatisticsOpeningImageFilterIUC2IF2_cast(itkLightObject obj) -> itkLabelStatisticsOpeningImageFilterIUC2IF2"""
    return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IF2_cast(obj)

class itkLabelStatisticsOpeningImageFilterIUC2ISS2(itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    """


    remove the objects according to the value of their statistics
    attribute

    LabelStatisticsOpeningImageFilter removes the objects in a labeled
    image with an attribute value smaller or greater than a threshold
    called Lambda. The attributes are the ones of the
    StatisticsLabelObject.

    Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA
    de Jouy-en-Josas, France.  This implementation was taken from the
    Insight Journal paper:https://hdl.handle.net/1926/584 orhttp://www
    .insight-journal.org/browse/publication/176

    See:   StatisticsLabelObject, BinaryStatisticsOpeningImageFilter,
    LabelShapeOpeningImageFilter

    C++ includes: itkLabelStatisticsOpeningImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__():
        """__New_orig__() -> itkLabelStatisticsOpeningImageFilterIUC2ISS2_Pointer"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self):
        """Clone(itkLabelStatisticsOpeningImageFilterIUC2ISS2 self) -> itkLabelStatisticsOpeningImageFilterIUC2ISS2_Pointer"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_Clone(self)

    InputEqualityComparableCheck = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_InputEqualityComparableCheck
    IntConvertibleToInputCheck = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_IntConvertibleToInputCheck
    InputOStreamWritableCheck = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_InputOStreamWritableCheck

    def SetBackgroundValue(self, _arg):
        """
        SetBackgroundValue(itkLabelStatisticsOpeningImageFilterIUC2ISS2 self, unsigned char const _arg)

        Set/Get the
        value used as "background" in the output image. Defaults to
        NumericTraits<PixelType>::NonpositiveMin(). 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_SetBackgroundValue(self, _arg)


    def GetBackgroundValue(self):
        """GetBackgroundValue(itkLabelStatisticsOpeningImageFilterIUC2ISS2 self) -> unsigned char"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_GetBackgroundValue(self)


    def GetLambda(self):
        """
        GetLambda(itkLabelStatisticsOpeningImageFilterIUC2ISS2 self) -> double

        Set/Get the threshold
        used to keep or remove the objects. 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_GetLambda(self)


    def SetLambda(self, _arg):
        """SetLambda(itkLabelStatisticsOpeningImageFilterIUC2ISS2 self, double const _arg)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_SetLambda(self, _arg)


    def GetReverseOrdering(self):
        """
        GetReverseOrdering(itkLabelStatisticsOpeningImageFilterIUC2ISS2 self) -> bool

        Set/Get the
        ordering of the objects. By default, the objects with an attribute
        value smaller than Lamba are removed. Turning ReverseOrdering to true
        make this filter remove the object with an attribute value greater
        than Lambda instead. 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_GetReverseOrdering(self)


    def SetReverseOrdering(self, _arg):
        """SetReverseOrdering(itkLabelStatisticsOpeningImageFilterIUC2ISS2 self, bool const _arg)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_SetReverseOrdering(self, _arg)


    def ReverseOrderingOn(self):
        """ReverseOrderingOn(itkLabelStatisticsOpeningImageFilterIUC2ISS2 self)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_ReverseOrderingOn(self)


    def ReverseOrderingOff(self):
        """ReverseOrderingOff(itkLabelStatisticsOpeningImageFilterIUC2ISS2 self)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_ReverseOrderingOff(self)


    def GetAttribute(self):
        """
        GetAttribute(itkLabelStatisticsOpeningImageFilterIUC2ISS2 self) -> unsigned int

        Set/Get the attribute
        to use to select the object to remove. The default is "Mean". 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_GetAttribute(self)


    def SetAttribute(self, *args):
        """
        SetAttribute(itkLabelStatisticsOpeningImageFilterIUC2ISS2 self, unsigned int const _arg)
        SetAttribute(itkLabelStatisticsOpeningImageFilterIUC2ISS2 self, std::string const & s)
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_SetAttribute(self, *args)


    def SetFeatureImage(self, input):
        """
        SetFeatureImage(itkLabelStatisticsOpeningImageFilterIUC2ISS2 self, itkImageSS2 input)

        Set the feature
        image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_SetFeatureImage(self, input)


    def GetFeatureImage(self):
        """
        GetFeatureImage(itkLabelStatisticsOpeningImageFilterIUC2ISS2 self) -> itkImageSS2

        Get the feature
        image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_GetFeatureImage(self)


    def SetInput1(self, input):
        """
        SetInput1(itkLabelStatisticsOpeningImageFilterIUC2ISS2 self, itkImageUC2 input)

        Set the input image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_SetInput1(self, input)


    def SetInput2(self, input):
        """
        SetInput2(itkLabelStatisticsOpeningImageFilterIUC2ISS2 self, itkImageSS2 input)

        Set the feature image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_SetInput2(self, input)

    __swig_destroy__ = _itkLabelStatisticsOpeningImageFilterPython.delete_itkLabelStatisticsOpeningImageFilterIUC2ISS2

    def cast(obj):
        """cast(itkLightObject obj) -> itkLabelStatisticsOpeningImageFilterIUC2ISS2"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self):
        """GetPointer(itkLabelStatisticsOpeningImageFilterIUC2ISS2 self) -> itkLabelStatisticsOpeningImageFilterIUC2ISS2"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkLabelStatisticsOpeningImageFilterIUC2ISS2

        Create a new object of the class itkLabelStatisticsOpeningImageFilterIUC2ISS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkLabelStatisticsOpeningImageFilterIUC2ISS2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkLabelStatisticsOpeningImageFilterIUC2ISS2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkLabelStatisticsOpeningImageFilterIUC2ISS2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkLabelStatisticsOpeningImageFilterIUC2ISS2.Clone = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_Clone, None, itkLabelStatisticsOpeningImageFilterIUC2ISS2)
itkLabelStatisticsOpeningImageFilterIUC2ISS2.SetBackgroundValue = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_SetBackgroundValue, None, itkLabelStatisticsOpeningImageFilterIUC2ISS2)
itkLabelStatisticsOpeningImageFilterIUC2ISS2.GetBackgroundValue = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_GetBackgroundValue, None, itkLabelStatisticsOpeningImageFilterIUC2ISS2)
itkLabelStatisticsOpeningImageFilterIUC2ISS2.GetLambda = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_GetLambda, None, itkLabelStatisticsOpeningImageFilterIUC2ISS2)
itkLabelStatisticsOpeningImageFilterIUC2ISS2.SetLambda = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_SetLambda, None, itkLabelStatisticsOpeningImageFilterIUC2ISS2)
itkLabelStatisticsOpeningImageFilterIUC2ISS2.GetReverseOrdering = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_GetReverseOrdering, None, itkLabelStatisticsOpeningImageFilterIUC2ISS2)
itkLabelStatisticsOpeningImageFilterIUC2ISS2.SetReverseOrdering = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_SetReverseOrdering, None, itkLabelStatisticsOpeningImageFilterIUC2ISS2)
itkLabelStatisticsOpeningImageFilterIUC2ISS2.ReverseOrderingOn = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_ReverseOrderingOn, None, itkLabelStatisticsOpeningImageFilterIUC2ISS2)
itkLabelStatisticsOpeningImageFilterIUC2ISS2.ReverseOrderingOff = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_ReverseOrderingOff, None, itkLabelStatisticsOpeningImageFilterIUC2ISS2)
itkLabelStatisticsOpeningImageFilterIUC2ISS2.GetAttribute = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_GetAttribute, None, itkLabelStatisticsOpeningImageFilterIUC2ISS2)
itkLabelStatisticsOpeningImageFilterIUC2ISS2.SetAttribute = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_SetAttribute, None, itkLabelStatisticsOpeningImageFilterIUC2ISS2)
itkLabelStatisticsOpeningImageFilterIUC2ISS2.SetFeatureImage = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_SetFeatureImage, None, itkLabelStatisticsOpeningImageFilterIUC2ISS2)
itkLabelStatisticsOpeningImageFilterIUC2ISS2.GetFeatureImage = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_GetFeatureImage, None, itkLabelStatisticsOpeningImageFilterIUC2ISS2)
itkLabelStatisticsOpeningImageFilterIUC2ISS2.SetInput1 = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_SetInput1, None, itkLabelStatisticsOpeningImageFilterIUC2ISS2)
itkLabelStatisticsOpeningImageFilterIUC2ISS2.SetInput2 = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_SetInput2, None, itkLabelStatisticsOpeningImageFilterIUC2ISS2)
itkLabelStatisticsOpeningImageFilterIUC2ISS2.GetPointer = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_GetPointer, None, itkLabelStatisticsOpeningImageFilterIUC2ISS2)
itkLabelStatisticsOpeningImageFilterIUC2ISS2_swigregister = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_swigregister
itkLabelStatisticsOpeningImageFilterIUC2ISS2_swigregister(itkLabelStatisticsOpeningImageFilterIUC2ISS2)

def itkLabelStatisticsOpeningImageFilterIUC2ISS2___New_orig__():
    """itkLabelStatisticsOpeningImageFilterIUC2ISS2___New_orig__() -> itkLabelStatisticsOpeningImageFilterIUC2ISS2_Pointer"""
    return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2___New_orig__()

def itkLabelStatisticsOpeningImageFilterIUC2ISS2_cast(obj):
    """itkLabelStatisticsOpeningImageFilterIUC2ISS2_cast(itkLightObject obj) -> itkLabelStatisticsOpeningImageFilterIUC2ISS2"""
    return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2ISS2_cast(obj)

class itkLabelStatisticsOpeningImageFilterIUC2IUC2(itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    """


    remove the objects according to the value of their statistics
    attribute

    LabelStatisticsOpeningImageFilter removes the objects in a labeled
    image with an attribute value smaller or greater than a threshold
    called Lambda. The attributes are the ones of the
    StatisticsLabelObject.

    Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA
    de Jouy-en-Josas, France.  This implementation was taken from the
    Insight Journal paper:https://hdl.handle.net/1926/584 orhttp://www
    .insight-journal.org/browse/publication/176

    See:   StatisticsLabelObject, BinaryStatisticsOpeningImageFilter,
    LabelShapeOpeningImageFilter

    C++ includes: itkLabelStatisticsOpeningImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__():
        """__New_orig__() -> itkLabelStatisticsOpeningImageFilterIUC2IUC2_Pointer"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self):
        """Clone(itkLabelStatisticsOpeningImageFilterIUC2IUC2 self) -> itkLabelStatisticsOpeningImageFilterIUC2IUC2_Pointer"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_Clone(self)

    InputEqualityComparableCheck = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_InputEqualityComparableCheck
    IntConvertibleToInputCheck = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_IntConvertibleToInputCheck
    InputOStreamWritableCheck = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_InputOStreamWritableCheck

    def SetBackgroundValue(self, _arg):
        """
        SetBackgroundValue(itkLabelStatisticsOpeningImageFilterIUC2IUC2 self, unsigned char const _arg)

        Set/Get the
        value used as "background" in the output image. Defaults to
        NumericTraits<PixelType>::NonpositiveMin(). 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_SetBackgroundValue(self, _arg)


    def GetBackgroundValue(self):
        """GetBackgroundValue(itkLabelStatisticsOpeningImageFilterIUC2IUC2 self) -> unsigned char"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_GetBackgroundValue(self)


    def GetLambda(self):
        """
        GetLambda(itkLabelStatisticsOpeningImageFilterIUC2IUC2 self) -> double

        Set/Get the threshold
        used to keep or remove the objects. 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_GetLambda(self)


    def SetLambda(self, _arg):
        """SetLambda(itkLabelStatisticsOpeningImageFilterIUC2IUC2 self, double const _arg)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_SetLambda(self, _arg)


    def GetReverseOrdering(self):
        """
        GetReverseOrdering(itkLabelStatisticsOpeningImageFilterIUC2IUC2 self) -> bool

        Set/Get the
        ordering of the objects. By default, the objects with an attribute
        value smaller than Lamba are removed. Turning ReverseOrdering to true
        make this filter remove the object with an attribute value greater
        than Lambda instead. 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_GetReverseOrdering(self)


    def SetReverseOrdering(self, _arg):
        """SetReverseOrdering(itkLabelStatisticsOpeningImageFilterIUC2IUC2 self, bool const _arg)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_SetReverseOrdering(self, _arg)


    def ReverseOrderingOn(self):
        """ReverseOrderingOn(itkLabelStatisticsOpeningImageFilterIUC2IUC2 self)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_ReverseOrderingOn(self)


    def ReverseOrderingOff(self):
        """ReverseOrderingOff(itkLabelStatisticsOpeningImageFilterIUC2IUC2 self)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_ReverseOrderingOff(self)


    def GetAttribute(self):
        """
        GetAttribute(itkLabelStatisticsOpeningImageFilterIUC2IUC2 self) -> unsigned int

        Set/Get the attribute
        to use to select the object to remove. The default is "Mean". 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_GetAttribute(self)


    def SetAttribute(self, *args):
        """
        SetAttribute(itkLabelStatisticsOpeningImageFilterIUC2IUC2 self, unsigned int const _arg)
        SetAttribute(itkLabelStatisticsOpeningImageFilterIUC2IUC2 self, std::string const & s)
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_SetAttribute(self, *args)


    def SetFeatureImage(self, input):
        """
        SetFeatureImage(itkLabelStatisticsOpeningImageFilterIUC2IUC2 self, itkImageUC2 input)

        Set the feature
        image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_SetFeatureImage(self, input)


    def GetFeatureImage(self):
        """
        GetFeatureImage(itkLabelStatisticsOpeningImageFilterIUC2IUC2 self) -> itkImageUC2

        Get the feature
        image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_GetFeatureImage(self)


    def SetInput1(self, input):
        """
        SetInput1(itkLabelStatisticsOpeningImageFilterIUC2IUC2 self, itkImageUC2 input)

        Set the input image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_SetInput1(self, input)


    def SetInput2(self, input):
        """
        SetInput2(itkLabelStatisticsOpeningImageFilterIUC2IUC2 self, itkImageUC2 input)

        Set the feature image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_SetInput2(self, input)

    __swig_destroy__ = _itkLabelStatisticsOpeningImageFilterPython.delete_itkLabelStatisticsOpeningImageFilterIUC2IUC2

    def cast(obj):
        """cast(itkLightObject obj) -> itkLabelStatisticsOpeningImageFilterIUC2IUC2"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self):
        """GetPointer(itkLabelStatisticsOpeningImageFilterIUC2IUC2 self) -> itkLabelStatisticsOpeningImageFilterIUC2IUC2"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkLabelStatisticsOpeningImageFilterIUC2IUC2

        Create a new object of the class itkLabelStatisticsOpeningImageFilterIUC2IUC2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkLabelStatisticsOpeningImageFilterIUC2IUC2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkLabelStatisticsOpeningImageFilterIUC2IUC2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkLabelStatisticsOpeningImageFilterIUC2IUC2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkLabelStatisticsOpeningImageFilterIUC2IUC2.Clone = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_Clone, None, itkLabelStatisticsOpeningImageFilterIUC2IUC2)
itkLabelStatisticsOpeningImageFilterIUC2IUC2.SetBackgroundValue = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_SetBackgroundValue, None, itkLabelStatisticsOpeningImageFilterIUC2IUC2)
itkLabelStatisticsOpeningImageFilterIUC2IUC2.GetBackgroundValue = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_GetBackgroundValue, None, itkLabelStatisticsOpeningImageFilterIUC2IUC2)
itkLabelStatisticsOpeningImageFilterIUC2IUC2.GetLambda = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_GetLambda, None, itkLabelStatisticsOpeningImageFilterIUC2IUC2)
itkLabelStatisticsOpeningImageFilterIUC2IUC2.SetLambda = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_SetLambda, None, itkLabelStatisticsOpeningImageFilterIUC2IUC2)
itkLabelStatisticsOpeningImageFilterIUC2IUC2.GetReverseOrdering = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_GetReverseOrdering, None, itkLabelStatisticsOpeningImageFilterIUC2IUC2)
itkLabelStatisticsOpeningImageFilterIUC2IUC2.SetReverseOrdering = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_SetReverseOrdering, None, itkLabelStatisticsOpeningImageFilterIUC2IUC2)
itkLabelStatisticsOpeningImageFilterIUC2IUC2.ReverseOrderingOn = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_ReverseOrderingOn, None, itkLabelStatisticsOpeningImageFilterIUC2IUC2)
itkLabelStatisticsOpeningImageFilterIUC2IUC2.ReverseOrderingOff = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_ReverseOrderingOff, None, itkLabelStatisticsOpeningImageFilterIUC2IUC2)
itkLabelStatisticsOpeningImageFilterIUC2IUC2.GetAttribute = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_GetAttribute, None, itkLabelStatisticsOpeningImageFilterIUC2IUC2)
itkLabelStatisticsOpeningImageFilterIUC2IUC2.SetAttribute = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_SetAttribute, None, itkLabelStatisticsOpeningImageFilterIUC2IUC2)
itkLabelStatisticsOpeningImageFilterIUC2IUC2.SetFeatureImage = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_SetFeatureImage, None, itkLabelStatisticsOpeningImageFilterIUC2IUC2)
itkLabelStatisticsOpeningImageFilterIUC2IUC2.GetFeatureImage = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_GetFeatureImage, None, itkLabelStatisticsOpeningImageFilterIUC2IUC2)
itkLabelStatisticsOpeningImageFilterIUC2IUC2.SetInput1 = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_SetInput1, None, itkLabelStatisticsOpeningImageFilterIUC2IUC2)
itkLabelStatisticsOpeningImageFilterIUC2IUC2.SetInput2 = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_SetInput2, None, itkLabelStatisticsOpeningImageFilterIUC2IUC2)
itkLabelStatisticsOpeningImageFilterIUC2IUC2.GetPointer = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_GetPointer, None, itkLabelStatisticsOpeningImageFilterIUC2IUC2)
itkLabelStatisticsOpeningImageFilterIUC2IUC2_swigregister = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_swigregister
itkLabelStatisticsOpeningImageFilterIUC2IUC2_swigregister(itkLabelStatisticsOpeningImageFilterIUC2IUC2)

def itkLabelStatisticsOpeningImageFilterIUC2IUC2___New_orig__():
    """itkLabelStatisticsOpeningImageFilterIUC2IUC2___New_orig__() -> itkLabelStatisticsOpeningImageFilterIUC2IUC2_Pointer"""
    return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2___New_orig__()

def itkLabelStatisticsOpeningImageFilterIUC2IUC2_cast(obj):
    """itkLabelStatisticsOpeningImageFilterIUC2IUC2_cast(itkLightObject obj) -> itkLabelStatisticsOpeningImageFilterIUC2IUC2"""
    return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC2IUC2_cast(obj)

class itkLabelStatisticsOpeningImageFilterIUC3IF3(itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    """


    remove the objects according to the value of their statistics
    attribute

    LabelStatisticsOpeningImageFilter removes the objects in a labeled
    image with an attribute value smaller or greater than a threshold
    called Lambda. The attributes are the ones of the
    StatisticsLabelObject.

    Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA
    de Jouy-en-Josas, France.  This implementation was taken from the
    Insight Journal paper:https://hdl.handle.net/1926/584 orhttp://www
    .insight-journal.org/browse/publication/176

    See:   StatisticsLabelObject, BinaryStatisticsOpeningImageFilter,
    LabelShapeOpeningImageFilter

    C++ includes: itkLabelStatisticsOpeningImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__():
        """__New_orig__() -> itkLabelStatisticsOpeningImageFilterIUC3IF3_Pointer"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self):
        """Clone(itkLabelStatisticsOpeningImageFilterIUC3IF3 self) -> itkLabelStatisticsOpeningImageFilterIUC3IF3_Pointer"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_Clone(self)

    InputEqualityComparableCheck = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_InputEqualityComparableCheck
    IntConvertibleToInputCheck = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_IntConvertibleToInputCheck
    InputOStreamWritableCheck = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_InputOStreamWritableCheck

    def SetBackgroundValue(self, _arg):
        """
        SetBackgroundValue(itkLabelStatisticsOpeningImageFilterIUC3IF3 self, unsigned char const _arg)

        Set/Get the
        value used as "background" in the output image. Defaults to
        NumericTraits<PixelType>::NonpositiveMin(). 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_SetBackgroundValue(self, _arg)


    def GetBackgroundValue(self):
        """GetBackgroundValue(itkLabelStatisticsOpeningImageFilterIUC3IF3 self) -> unsigned char"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_GetBackgroundValue(self)


    def GetLambda(self):
        """
        GetLambda(itkLabelStatisticsOpeningImageFilterIUC3IF3 self) -> double

        Set/Get the threshold
        used to keep or remove the objects. 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_GetLambda(self)


    def SetLambda(self, _arg):
        """SetLambda(itkLabelStatisticsOpeningImageFilterIUC3IF3 self, double const _arg)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_SetLambda(self, _arg)


    def GetReverseOrdering(self):
        """
        GetReverseOrdering(itkLabelStatisticsOpeningImageFilterIUC3IF3 self) -> bool

        Set/Get the
        ordering of the objects. By default, the objects with an attribute
        value smaller than Lamba are removed. Turning ReverseOrdering to true
        make this filter remove the object with an attribute value greater
        than Lambda instead. 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_GetReverseOrdering(self)


    def SetReverseOrdering(self, _arg):
        """SetReverseOrdering(itkLabelStatisticsOpeningImageFilterIUC3IF3 self, bool const _arg)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_SetReverseOrdering(self, _arg)


    def ReverseOrderingOn(self):
        """ReverseOrderingOn(itkLabelStatisticsOpeningImageFilterIUC3IF3 self)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_ReverseOrderingOn(self)


    def ReverseOrderingOff(self):
        """ReverseOrderingOff(itkLabelStatisticsOpeningImageFilterIUC3IF3 self)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_ReverseOrderingOff(self)


    def GetAttribute(self):
        """
        GetAttribute(itkLabelStatisticsOpeningImageFilterIUC3IF3 self) -> unsigned int

        Set/Get the attribute
        to use to select the object to remove. The default is "Mean". 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_GetAttribute(self)


    def SetAttribute(self, *args):
        """
        SetAttribute(itkLabelStatisticsOpeningImageFilterIUC3IF3 self, unsigned int const _arg)
        SetAttribute(itkLabelStatisticsOpeningImageFilterIUC3IF3 self, std::string const & s)
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_SetAttribute(self, *args)


    def SetFeatureImage(self, input):
        """
        SetFeatureImage(itkLabelStatisticsOpeningImageFilterIUC3IF3 self, itkImageF3 input)

        Set the feature
        image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_SetFeatureImage(self, input)


    def GetFeatureImage(self):
        """
        GetFeatureImage(itkLabelStatisticsOpeningImageFilterIUC3IF3 self) -> itkImageF3

        Get the feature
        image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_GetFeatureImage(self)


    def SetInput1(self, input):
        """
        SetInput1(itkLabelStatisticsOpeningImageFilterIUC3IF3 self, itkImageUC3 input)

        Set the input image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_SetInput1(self, input)


    def SetInput2(self, input):
        """
        SetInput2(itkLabelStatisticsOpeningImageFilterIUC3IF3 self, itkImageF3 input)

        Set the feature image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_SetInput2(self, input)

    __swig_destroy__ = _itkLabelStatisticsOpeningImageFilterPython.delete_itkLabelStatisticsOpeningImageFilterIUC3IF3

    def cast(obj):
        """cast(itkLightObject obj) -> itkLabelStatisticsOpeningImageFilterIUC3IF3"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self):
        """GetPointer(itkLabelStatisticsOpeningImageFilterIUC3IF3 self) -> itkLabelStatisticsOpeningImageFilterIUC3IF3"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkLabelStatisticsOpeningImageFilterIUC3IF3

        Create a new object of the class itkLabelStatisticsOpeningImageFilterIUC3IF3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkLabelStatisticsOpeningImageFilterIUC3IF3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkLabelStatisticsOpeningImageFilterIUC3IF3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkLabelStatisticsOpeningImageFilterIUC3IF3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkLabelStatisticsOpeningImageFilterIUC3IF3.Clone = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_Clone, None, itkLabelStatisticsOpeningImageFilterIUC3IF3)
itkLabelStatisticsOpeningImageFilterIUC3IF3.SetBackgroundValue = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_SetBackgroundValue, None, itkLabelStatisticsOpeningImageFilterIUC3IF3)
itkLabelStatisticsOpeningImageFilterIUC3IF3.GetBackgroundValue = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_GetBackgroundValue, None, itkLabelStatisticsOpeningImageFilterIUC3IF3)
itkLabelStatisticsOpeningImageFilterIUC3IF3.GetLambda = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_GetLambda, None, itkLabelStatisticsOpeningImageFilterIUC3IF3)
itkLabelStatisticsOpeningImageFilterIUC3IF3.SetLambda = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_SetLambda, None, itkLabelStatisticsOpeningImageFilterIUC3IF3)
itkLabelStatisticsOpeningImageFilterIUC3IF3.GetReverseOrdering = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_GetReverseOrdering, None, itkLabelStatisticsOpeningImageFilterIUC3IF3)
itkLabelStatisticsOpeningImageFilterIUC3IF3.SetReverseOrdering = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_SetReverseOrdering, None, itkLabelStatisticsOpeningImageFilterIUC3IF3)
itkLabelStatisticsOpeningImageFilterIUC3IF3.ReverseOrderingOn = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_ReverseOrderingOn, None, itkLabelStatisticsOpeningImageFilterIUC3IF3)
itkLabelStatisticsOpeningImageFilterIUC3IF3.ReverseOrderingOff = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_ReverseOrderingOff, None, itkLabelStatisticsOpeningImageFilterIUC3IF3)
itkLabelStatisticsOpeningImageFilterIUC3IF3.GetAttribute = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_GetAttribute, None, itkLabelStatisticsOpeningImageFilterIUC3IF3)
itkLabelStatisticsOpeningImageFilterIUC3IF3.SetAttribute = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_SetAttribute, None, itkLabelStatisticsOpeningImageFilterIUC3IF3)
itkLabelStatisticsOpeningImageFilterIUC3IF3.SetFeatureImage = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_SetFeatureImage, None, itkLabelStatisticsOpeningImageFilterIUC3IF3)
itkLabelStatisticsOpeningImageFilterIUC3IF3.GetFeatureImage = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_GetFeatureImage, None, itkLabelStatisticsOpeningImageFilterIUC3IF3)
itkLabelStatisticsOpeningImageFilterIUC3IF3.SetInput1 = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_SetInput1, None, itkLabelStatisticsOpeningImageFilterIUC3IF3)
itkLabelStatisticsOpeningImageFilterIUC3IF3.SetInput2 = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_SetInput2, None, itkLabelStatisticsOpeningImageFilterIUC3IF3)
itkLabelStatisticsOpeningImageFilterIUC3IF3.GetPointer = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_GetPointer, None, itkLabelStatisticsOpeningImageFilterIUC3IF3)
itkLabelStatisticsOpeningImageFilterIUC3IF3_swigregister = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_swigregister
itkLabelStatisticsOpeningImageFilterIUC3IF3_swigregister(itkLabelStatisticsOpeningImageFilterIUC3IF3)

def itkLabelStatisticsOpeningImageFilterIUC3IF3___New_orig__():
    """itkLabelStatisticsOpeningImageFilterIUC3IF3___New_orig__() -> itkLabelStatisticsOpeningImageFilterIUC3IF3_Pointer"""
    return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3___New_orig__()

def itkLabelStatisticsOpeningImageFilterIUC3IF3_cast(obj):
    """itkLabelStatisticsOpeningImageFilterIUC3IF3_cast(itkLightObject obj) -> itkLabelStatisticsOpeningImageFilterIUC3IF3"""
    return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IF3_cast(obj)

class itkLabelStatisticsOpeningImageFilterIUC3ISS3(itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    """


    remove the objects according to the value of their statistics
    attribute

    LabelStatisticsOpeningImageFilter removes the objects in a labeled
    image with an attribute value smaller or greater than a threshold
    called Lambda. The attributes are the ones of the
    StatisticsLabelObject.

    Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA
    de Jouy-en-Josas, France.  This implementation was taken from the
    Insight Journal paper:https://hdl.handle.net/1926/584 orhttp://www
    .insight-journal.org/browse/publication/176

    See:   StatisticsLabelObject, BinaryStatisticsOpeningImageFilter,
    LabelShapeOpeningImageFilter

    C++ includes: itkLabelStatisticsOpeningImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__():
        """__New_orig__() -> itkLabelStatisticsOpeningImageFilterIUC3ISS3_Pointer"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self):
        """Clone(itkLabelStatisticsOpeningImageFilterIUC3ISS3 self) -> itkLabelStatisticsOpeningImageFilterIUC3ISS3_Pointer"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_Clone(self)

    InputEqualityComparableCheck = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_InputEqualityComparableCheck
    IntConvertibleToInputCheck = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_IntConvertibleToInputCheck
    InputOStreamWritableCheck = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_InputOStreamWritableCheck

    def SetBackgroundValue(self, _arg):
        """
        SetBackgroundValue(itkLabelStatisticsOpeningImageFilterIUC3ISS3 self, unsigned char const _arg)

        Set/Get the
        value used as "background" in the output image. Defaults to
        NumericTraits<PixelType>::NonpositiveMin(). 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_SetBackgroundValue(self, _arg)


    def GetBackgroundValue(self):
        """GetBackgroundValue(itkLabelStatisticsOpeningImageFilterIUC3ISS3 self) -> unsigned char"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_GetBackgroundValue(self)


    def GetLambda(self):
        """
        GetLambda(itkLabelStatisticsOpeningImageFilterIUC3ISS3 self) -> double

        Set/Get the threshold
        used to keep or remove the objects. 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_GetLambda(self)


    def SetLambda(self, _arg):
        """SetLambda(itkLabelStatisticsOpeningImageFilterIUC3ISS3 self, double const _arg)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_SetLambda(self, _arg)


    def GetReverseOrdering(self):
        """
        GetReverseOrdering(itkLabelStatisticsOpeningImageFilterIUC3ISS3 self) -> bool

        Set/Get the
        ordering of the objects. By default, the objects with an attribute
        value smaller than Lamba are removed. Turning ReverseOrdering to true
        make this filter remove the object with an attribute value greater
        than Lambda instead. 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_GetReverseOrdering(self)


    def SetReverseOrdering(self, _arg):
        """SetReverseOrdering(itkLabelStatisticsOpeningImageFilterIUC3ISS3 self, bool const _arg)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_SetReverseOrdering(self, _arg)


    def ReverseOrderingOn(self):
        """ReverseOrderingOn(itkLabelStatisticsOpeningImageFilterIUC3ISS3 self)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_ReverseOrderingOn(self)


    def ReverseOrderingOff(self):
        """ReverseOrderingOff(itkLabelStatisticsOpeningImageFilterIUC3ISS3 self)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_ReverseOrderingOff(self)


    def GetAttribute(self):
        """
        GetAttribute(itkLabelStatisticsOpeningImageFilterIUC3ISS3 self) -> unsigned int

        Set/Get the attribute
        to use to select the object to remove. The default is "Mean". 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_GetAttribute(self)


    def SetAttribute(self, *args):
        """
        SetAttribute(itkLabelStatisticsOpeningImageFilterIUC3ISS3 self, unsigned int const _arg)
        SetAttribute(itkLabelStatisticsOpeningImageFilterIUC3ISS3 self, std::string const & s)
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_SetAttribute(self, *args)


    def SetFeatureImage(self, input):
        """
        SetFeatureImage(itkLabelStatisticsOpeningImageFilterIUC3ISS3 self, itkImageSS3 input)

        Set the feature
        image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_SetFeatureImage(self, input)


    def GetFeatureImage(self):
        """
        GetFeatureImage(itkLabelStatisticsOpeningImageFilterIUC3ISS3 self) -> itkImageSS3

        Get the feature
        image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_GetFeatureImage(self)


    def SetInput1(self, input):
        """
        SetInput1(itkLabelStatisticsOpeningImageFilterIUC3ISS3 self, itkImageUC3 input)

        Set the input image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_SetInput1(self, input)


    def SetInput2(self, input):
        """
        SetInput2(itkLabelStatisticsOpeningImageFilterIUC3ISS3 self, itkImageSS3 input)

        Set the feature image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_SetInput2(self, input)

    __swig_destroy__ = _itkLabelStatisticsOpeningImageFilterPython.delete_itkLabelStatisticsOpeningImageFilterIUC3ISS3

    def cast(obj):
        """cast(itkLightObject obj) -> itkLabelStatisticsOpeningImageFilterIUC3ISS3"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self):
        """GetPointer(itkLabelStatisticsOpeningImageFilterIUC3ISS3 self) -> itkLabelStatisticsOpeningImageFilterIUC3ISS3"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkLabelStatisticsOpeningImageFilterIUC3ISS3

        Create a new object of the class itkLabelStatisticsOpeningImageFilterIUC3ISS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkLabelStatisticsOpeningImageFilterIUC3ISS3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkLabelStatisticsOpeningImageFilterIUC3ISS3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkLabelStatisticsOpeningImageFilterIUC3ISS3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkLabelStatisticsOpeningImageFilterIUC3ISS3.Clone = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_Clone, None, itkLabelStatisticsOpeningImageFilterIUC3ISS3)
itkLabelStatisticsOpeningImageFilterIUC3ISS3.SetBackgroundValue = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_SetBackgroundValue, None, itkLabelStatisticsOpeningImageFilterIUC3ISS3)
itkLabelStatisticsOpeningImageFilterIUC3ISS3.GetBackgroundValue = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_GetBackgroundValue, None, itkLabelStatisticsOpeningImageFilterIUC3ISS3)
itkLabelStatisticsOpeningImageFilterIUC3ISS3.GetLambda = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_GetLambda, None, itkLabelStatisticsOpeningImageFilterIUC3ISS3)
itkLabelStatisticsOpeningImageFilterIUC3ISS3.SetLambda = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_SetLambda, None, itkLabelStatisticsOpeningImageFilterIUC3ISS3)
itkLabelStatisticsOpeningImageFilterIUC3ISS3.GetReverseOrdering = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_GetReverseOrdering, None, itkLabelStatisticsOpeningImageFilterIUC3ISS3)
itkLabelStatisticsOpeningImageFilterIUC3ISS3.SetReverseOrdering = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_SetReverseOrdering, None, itkLabelStatisticsOpeningImageFilterIUC3ISS3)
itkLabelStatisticsOpeningImageFilterIUC3ISS3.ReverseOrderingOn = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_ReverseOrderingOn, None, itkLabelStatisticsOpeningImageFilterIUC3ISS3)
itkLabelStatisticsOpeningImageFilterIUC3ISS3.ReverseOrderingOff = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_ReverseOrderingOff, None, itkLabelStatisticsOpeningImageFilterIUC3ISS3)
itkLabelStatisticsOpeningImageFilterIUC3ISS3.GetAttribute = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_GetAttribute, None, itkLabelStatisticsOpeningImageFilterIUC3ISS3)
itkLabelStatisticsOpeningImageFilterIUC3ISS3.SetAttribute = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_SetAttribute, None, itkLabelStatisticsOpeningImageFilterIUC3ISS3)
itkLabelStatisticsOpeningImageFilterIUC3ISS3.SetFeatureImage = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_SetFeatureImage, None, itkLabelStatisticsOpeningImageFilterIUC3ISS3)
itkLabelStatisticsOpeningImageFilterIUC3ISS3.GetFeatureImage = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_GetFeatureImage, None, itkLabelStatisticsOpeningImageFilterIUC3ISS3)
itkLabelStatisticsOpeningImageFilterIUC3ISS3.SetInput1 = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_SetInput1, None, itkLabelStatisticsOpeningImageFilterIUC3ISS3)
itkLabelStatisticsOpeningImageFilterIUC3ISS3.SetInput2 = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_SetInput2, None, itkLabelStatisticsOpeningImageFilterIUC3ISS3)
itkLabelStatisticsOpeningImageFilterIUC3ISS3.GetPointer = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_GetPointer, None, itkLabelStatisticsOpeningImageFilterIUC3ISS3)
itkLabelStatisticsOpeningImageFilterIUC3ISS3_swigregister = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_swigregister
itkLabelStatisticsOpeningImageFilterIUC3ISS3_swigregister(itkLabelStatisticsOpeningImageFilterIUC3ISS3)

def itkLabelStatisticsOpeningImageFilterIUC3ISS3___New_orig__():
    """itkLabelStatisticsOpeningImageFilterIUC3ISS3___New_orig__() -> itkLabelStatisticsOpeningImageFilterIUC3ISS3_Pointer"""
    return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3___New_orig__()

def itkLabelStatisticsOpeningImageFilterIUC3ISS3_cast(obj):
    """itkLabelStatisticsOpeningImageFilterIUC3ISS3_cast(itkLightObject obj) -> itkLabelStatisticsOpeningImageFilterIUC3ISS3"""
    return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3ISS3_cast(obj)

class itkLabelStatisticsOpeningImageFilterIUC3IUC3(itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    """


    remove the objects according to the value of their statistics
    attribute

    LabelStatisticsOpeningImageFilter removes the objects in a labeled
    image with an attribute value smaller or greater than a threshold
    called Lambda. The attributes are the ones of the
    StatisticsLabelObject.

    Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA
    de Jouy-en-Josas, France.  This implementation was taken from the
    Insight Journal paper:https://hdl.handle.net/1926/584 orhttp://www
    .insight-journal.org/browse/publication/176

    See:   StatisticsLabelObject, BinaryStatisticsOpeningImageFilter,
    LabelShapeOpeningImageFilter

    C++ includes: itkLabelStatisticsOpeningImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__():
        """__New_orig__() -> itkLabelStatisticsOpeningImageFilterIUC3IUC3_Pointer"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self):
        """Clone(itkLabelStatisticsOpeningImageFilterIUC3IUC3 self) -> itkLabelStatisticsOpeningImageFilterIUC3IUC3_Pointer"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_Clone(self)

    InputEqualityComparableCheck = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_InputEqualityComparableCheck
    IntConvertibleToInputCheck = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_IntConvertibleToInputCheck
    InputOStreamWritableCheck = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_InputOStreamWritableCheck

    def SetBackgroundValue(self, _arg):
        """
        SetBackgroundValue(itkLabelStatisticsOpeningImageFilterIUC3IUC3 self, unsigned char const _arg)

        Set/Get the
        value used as "background" in the output image. Defaults to
        NumericTraits<PixelType>::NonpositiveMin(). 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_SetBackgroundValue(self, _arg)


    def GetBackgroundValue(self):
        """GetBackgroundValue(itkLabelStatisticsOpeningImageFilterIUC3IUC3 self) -> unsigned char"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_GetBackgroundValue(self)


    def GetLambda(self):
        """
        GetLambda(itkLabelStatisticsOpeningImageFilterIUC3IUC3 self) -> double

        Set/Get the threshold
        used to keep or remove the objects. 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_GetLambda(self)


    def SetLambda(self, _arg):
        """SetLambda(itkLabelStatisticsOpeningImageFilterIUC3IUC3 self, double const _arg)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_SetLambda(self, _arg)


    def GetReverseOrdering(self):
        """
        GetReverseOrdering(itkLabelStatisticsOpeningImageFilterIUC3IUC3 self) -> bool

        Set/Get the
        ordering of the objects. By default, the objects with an attribute
        value smaller than Lamba are removed. Turning ReverseOrdering to true
        make this filter remove the object with an attribute value greater
        than Lambda instead. 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_GetReverseOrdering(self)


    def SetReverseOrdering(self, _arg):
        """SetReverseOrdering(itkLabelStatisticsOpeningImageFilterIUC3IUC3 self, bool const _arg)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_SetReverseOrdering(self, _arg)


    def ReverseOrderingOn(self):
        """ReverseOrderingOn(itkLabelStatisticsOpeningImageFilterIUC3IUC3 self)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_ReverseOrderingOn(self)


    def ReverseOrderingOff(self):
        """ReverseOrderingOff(itkLabelStatisticsOpeningImageFilterIUC3IUC3 self)"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_ReverseOrderingOff(self)


    def GetAttribute(self):
        """
        GetAttribute(itkLabelStatisticsOpeningImageFilterIUC3IUC3 self) -> unsigned int

        Set/Get the attribute
        to use to select the object to remove. The default is "Mean". 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_GetAttribute(self)


    def SetAttribute(self, *args):
        """
        SetAttribute(itkLabelStatisticsOpeningImageFilterIUC3IUC3 self, unsigned int const _arg)
        SetAttribute(itkLabelStatisticsOpeningImageFilterIUC3IUC3 self, std::string const & s)
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_SetAttribute(self, *args)


    def SetFeatureImage(self, input):
        """
        SetFeatureImage(itkLabelStatisticsOpeningImageFilterIUC3IUC3 self, itkImageUC3 input)

        Set the feature
        image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_SetFeatureImage(self, input)


    def GetFeatureImage(self):
        """
        GetFeatureImage(itkLabelStatisticsOpeningImageFilterIUC3IUC3 self) -> itkImageUC3

        Get the feature
        image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_GetFeatureImage(self)


    def SetInput1(self, input):
        """
        SetInput1(itkLabelStatisticsOpeningImageFilterIUC3IUC3 self, itkImageUC3 input)

        Set the input image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_SetInput1(self, input)


    def SetInput2(self, input):
        """
        SetInput2(itkLabelStatisticsOpeningImageFilterIUC3IUC3 self, itkImageUC3 input)

        Set the feature image 
        """
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_SetInput2(self, input)

    __swig_destroy__ = _itkLabelStatisticsOpeningImageFilterPython.delete_itkLabelStatisticsOpeningImageFilterIUC3IUC3

    def cast(obj):
        """cast(itkLightObject obj) -> itkLabelStatisticsOpeningImageFilterIUC3IUC3"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self):
        """GetPointer(itkLabelStatisticsOpeningImageFilterIUC3IUC3 self) -> itkLabelStatisticsOpeningImageFilterIUC3IUC3"""
        return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkLabelStatisticsOpeningImageFilterIUC3IUC3

        Create a new object of the class itkLabelStatisticsOpeningImageFilterIUC3IUC3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkLabelStatisticsOpeningImageFilterIUC3IUC3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkLabelStatisticsOpeningImageFilterIUC3IUC3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkLabelStatisticsOpeningImageFilterIUC3IUC3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkLabelStatisticsOpeningImageFilterIUC3IUC3.Clone = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_Clone, None, itkLabelStatisticsOpeningImageFilterIUC3IUC3)
itkLabelStatisticsOpeningImageFilterIUC3IUC3.SetBackgroundValue = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_SetBackgroundValue, None, itkLabelStatisticsOpeningImageFilterIUC3IUC3)
itkLabelStatisticsOpeningImageFilterIUC3IUC3.GetBackgroundValue = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_GetBackgroundValue, None, itkLabelStatisticsOpeningImageFilterIUC3IUC3)
itkLabelStatisticsOpeningImageFilterIUC3IUC3.GetLambda = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_GetLambda, None, itkLabelStatisticsOpeningImageFilterIUC3IUC3)
itkLabelStatisticsOpeningImageFilterIUC3IUC3.SetLambda = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_SetLambda, None, itkLabelStatisticsOpeningImageFilterIUC3IUC3)
itkLabelStatisticsOpeningImageFilterIUC3IUC3.GetReverseOrdering = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_GetReverseOrdering, None, itkLabelStatisticsOpeningImageFilterIUC3IUC3)
itkLabelStatisticsOpeningImageFilterIUC3IUC3.SetReverseOrdering = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_SetReverseOrdering, None, itkLabelStatisticsOpeningImageFilterIUC3IUC3)
itkLabelStatisticsOpeningImageFilterIUC3IUC3.ReverseOrderingOn = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_ReverseOrderingOn, None, itkLabelStatisticsOpeningImageFilterIUC3IUC3)
itkLabelStatisticsOpeningImageFilterIUC3IUC3.ReverseOrderingOff = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_ReverseOrderingOff, None, itkLabelStatisticsOpeningImageFilterIUC3IUC3)
itkLabelStatisticsOpeningImageFilterIUC3IUC3.GetAttribute = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_GetAttribute, None, itkLabelStatisticsOpeningImageFilterIUC3IUC3)
itkLabelStatisticsOpeningImageFilterIUC3IUC3.SetAttribute = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_SetAttribute, None, itkLabelStatisticsOpeningImageFilterIUC3IUC3)
itkLabelStatisticsOpeningImageFilterIUC3IUC3.SetFeatureImage = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_SetFeatureImage, None, itkLabelStatisticsOpeningImageFilterIUC3IUC3)
itkLabelStatisticsOpeningImageFilterIUC3IUC3.GetFeatureImage = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_GetFeatureImage, None, itkLabelStatisticsOpeningImageFilterIUC3IUC3)
itkLabelStatisticsOpeningImageFilterIUC3IUC3.SetInput1 = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_SetInput1, None, itkLabelStatisticsOpeningImageFilterIUC3IUC3)
itkLabelStatisticsOpeningImageFilterIUC3IUC3.SetInput2 = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_SetInput2, None, itkLabelStatisticsOpeningImageFilterIUC3IUC3)
itkLabelStatisticsOpeningImageFilterIUC3IUC3.GetPointer = new_instancemethod(_itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_GetPointer, None, itkLabelStatisticsOpeningImageFilterIUC3IUC3)
itkLabelStatisticsOpeningImageFilterIUC3IUC3_swigregister = _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_swigregister
itkLabelStatisticsOpeningImageFilterIUC3IUC3_swigregister(itkLabelStatisticsOpeningImageFilterIUC3IUC3)

def itkLabelStatisticsOpeningImageFilterIUC3IUC3___New_orig__():
    """itkLabelStatisticsOpeningImageFilterIUC3IUC3___New_orig__() -> itkLabelStatisticsOpeningImageFilterIUC3IUC3_Pointer"""
    return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3___New_orig__()

def itkLabelStatisticsOpeningImageFilterIUC3IUC3_cast(obj):
    """itkLabelStatisticsOpeningImageFilterIUC3IUC3_cast(itkLightObject obj) -> itkLabelStatisticsOpeningImageFilterIUC3IUC3"""
    return _itkLabelStatisticsOpeningImageFilterPython.itkLabelStatisticsOpeningImageFilterIUC3IUC3_cast(obj)



