# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _itkMaximumEntropyThresholdImageFilterPython.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_itkMaximumEntropyThresholdImageFilterPython')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_itkMaximumEntropyThresholdImageFilterPython')
    _itkMaximumEntropyThresholdImageFilterPython = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_itkMaximumEntropyThresholdImageFilterPython', [dirname(__file__)])
        except ImportError:
            import _itkMaximumEntropyThresholdImageFilterPython
            return _itkMaximumEntropyThresholdImageFilterPython
        try:
            _mod = imp.load_module('_itkMaximumEntropyThresholdImageFilterPython', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _itkMaximumEntropyThresholdImageFilterPython = swig_import_helper()
    del swig_import_helper
else:
    import _itkMaximumEntropyThresholdImageFilterPython
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


import itkHistogramThresholdImageFilterPython
import ITKCommonBasePython
import pyBasePython
import itkImagePython
import itkOffsetPython
import itkSizePython
import itkRGBPixelPython
import itkFixedArrayPython
import itkRGBAPixelPython
import itkIndexPython
import itkPointPython
import vnl_vectorPython
import stdcomplexPython
import vnl_matrixPython
import vnl_vector_refPython
import itkVectorPython
import itkSymmetricSecondRankTensorPython
import itkMatrixPython
import vnl_matrix_fixedPython
import itkCovariantVectorPython
import itkImageRegionPython
import itkImageToImageFilterAPython
import itkImageToImageFilterCommonPython
import itkImageSourcePython
import itkImageSourceCommonPython
import itkVectorImagePython
import itkVariableLengthVectorPython
import itkHistogramThresholdCalculatorPython
import itkSimpleDataObjectDecoratorPython
import itkArrayPython
import itkHistogramPython
import itkSamplePython

def itkMaximumEntropyThresholdImageFilterIF3IUC3_New():
  return itkMaximumEntropyThresholdImageFilterIF3IUC3.New()


def itkMaximumEntropyThresholdImageFilterIF2IUC2_New():
  return itkMaximumEntropyThresholdImageFilterIF2IUC2.New()


def itkMaximumEntropyThresholdImageFilterIF3ISS3_New():
  return itkMaximumEntropyThresholdImageFilterIF3ISS3.New()


def itkMaximumEntropyThresholdImageFilterIF2ISS2_New():
  return itkMaximumEntropyThresholdImageFilterIF2ISS2.New()


def itkMaximumEntropyThresholdImageFilterIUC3IUC3_New():
  return itkMaximumEntropyThresholdImageFilterIUC3IUC3.New()


def itkMaximumEntropyThresholdImageFilterIUC2IUC2_New():
  return itkMaximumEntropyThresholdImageFilterIUC2IUC2.New()


def itkMaximumEntropyThresholdImageFilterIUC3ISS3_New():
  return itkMaximumEntropyThresholdImageFilterIUC3ISS3.New()


def itkMaximumEntropyThresholdImageFilterIUC2ISS2_New():
  return itkMaximumEntropyThresholdImageFilterIUC2ISS2.New()


def itkMaximumEntropyThresholdImageFilterISS3IUC3_New():
  return itkMaximumEntropyThresholdImageFilterISS3IUC3.New()


def itkMaximumEntropyThresholdImageFilterISS2IUC2_New():
  return itkMaximumEntropyThresholdImageFilterISS2IUC2.New()


def itkMaximumEntropyThresholdImageFilterISS3ISS3_New():
  return itkMaximumEntropyThresholdImageFilterISS3ISS3.New()


def itkMaximumEntropyThresholdImageFilterISS2ISS2_New():
  return itkMaximumEntropyThresholdImageFilterISS2ISS2.New()

class itkMaximumEntropyThresholdImageFilterIF2ISS2(itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF2ISS2):
    """


    Threshold an image using the MaximumEntropy Threshold.

    This filter creates a binary thresholded image that separates an image
    into foreground and background components. The filter computes the
    threshold using the MaximumEntropyThresholdCalculator and applies that
    threshold to the input image using the BinaryThresholdImageFilter.

    Richard Beare. Department of Medicine, Monash University, Melbourne,
    Australia.

    Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA
    de Jouy-en-Josas, France.  This implementation was taken from the
    Insight Journal paper:https://hdl.handle.net/10380/3279
    orhttp://www.insight-journal.org/browse/publication/811

    See:   HistogramThresholdImageFilter

    C++ includes: itkMaximumEntropyThresholdImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkMaximumEntropyThresholdImageFilterIF2ISS2_Pointer":
        """__New_orig__() -> itkMaximumEntropyThresholdImageFilterIF2ISS2_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF2ISS2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkMaximumEntropyThresholdImageFilterIF2ISS2_Pointer":
        """Clone(itkMaximumEntropyThresholdImageFilterIF2ISS2 self) -> itkMaximumEntropyThresholdImageFilterIF2ISS2_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF2ISS2_Clone(self)

    __swig_destroy__ = _itkMaximumEntropyThresholdImageFilterPython.delete_itkMaximumEntropyThresholdImageFilterIF2ISS2

    def cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterIF2ISS2 *":
        """cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterIF2ISS2"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF2ISS2_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self) -> "itkMaximumEntropyThresholdImageFilterIF2ISS2 *":
        """GetPointer(itkMaximumEntropyThresholdImageFilterIF2ISS2 self) -> itkMaximumEntropyThresholdImageFilterIF2ISS2"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF2ISS2_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkMaximumEntropyThresholdImageFilterIF2ISS2

        Create a new object of the class itkMaximumEntropyThresholdImageFilterIF2ISS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMaximumEntropyThresholdImageFilterIF2ISS2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkMaximumEntropyThresholdImageFilterIF2ISS2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumEntropyThresholdImageFilterIF2ISS2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumEntropyThresholdImageFilterIF2ISS2.Clone = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF2ISS2_Clone, None, itkMaximumEntropyThresholdImageFilterIF2ISS2)
itkMaximumEntropyThresholdImageFilterIF2ISS2.GetPointer = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF2ISS2_GetPointer, None, itkMaximumEntropyThresholdImageFilterIF2ISS2)
itkMaximumEntropyThresholdImageFilterIF2ISS2_swigregister = _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF2ISS2_swigregister
itkMaximumEntropyThresholdImageFilterIF2ISS2_swigregister(itkMaximumEntropyThresholdImageFilterIF2ISS2)

def itkMaximumEntropyThresholdImageFilterIF2ISS2___New_orig__() -> "itkMaximumEntropyThresholdImageFilterIF2ISS2_Pointer":
    """itkMaximumEntropyThresholdImageFilterIF2ISS2___New_orig__() -> itkMaximumEntropyThresholdImageFilterIF2ISS2_Pointer"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF2ISS2___New_orig__()

def itkMaximumEntropyThresholdImageFilterIF2ISS2_cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterIF2ISS2 *":
    """itkMaximumEntropyThresholdImageFilterIF2ISS2_cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterIF2ISS2"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF2ISS2_cast(obj)

class itkMaximumEntropyThresholdImageFilterIF2IUC2(itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF2IUC2):
    """


    Threshold an image using the MaximumEntropy Threshold.

    This filter creates a binary thresholded image that separates an image
    into foreground and background components. The filter computes the
    threshold using the MaximumEntropyThresholdCalculator and applies that
    threshold to the input image using the BinaryThresholdImageFilter.

    Richard Beare. Department of Medicine, Monash University, Melbourne,
    Australia.

    Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA
    de Jouy-en-Josas, France.  This implementation was taken from the
    Insight Journal paper:https://hdl.handle.net/10380/3279
    orhttp://www.insight-journal.org/browse/publication/811

    See:   HistogramThresholdImageFilter

    C++ includes: itkMaximumEntropyThresholdImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkMaximumEntropyThresholdImageFilterIF2IUC2_Pointer":
        """__New_orig__() -> itkMaximumEntropyThresholdImageFilterIF2IUC2_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF2IUC2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkMaximumEntropyThresholdImageFilterIF2IUC2_Pointer":
        """Clone(itkMaximumEntropyThresholdImageFilterIF2IUC2 self) -> itkMaximumEntropyThresholdImageFilterIF2IUC2_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF2IUC2_Clone(self)

    __swig_destroy__ = _itkMaximumEntropyThresholdImageFilterPython.delete_itkMaximumEntropyThresholdImageFilterIF2IUC2

    def cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterIF2IUC2 *":
        """cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterIF2IUC2"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF2IUC2_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self) -> "itkMaximumEntropyThresholdImageFilterIF2IUC2 *":
        """GetPointer(itkMaximumEntropyThresholdImageFilterIF2IUC2 self) -> itkMaximumEntropyThresholdImageFilterIF2IUC2"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF2IUC2_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkMaximumEntropyThresholdImageFilterIF2IUC2

        Create a new object of the class itkMaximumEntropyThresholdImageFilterIF2IUC2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMaximumEntropyThresholdImageFilterIF2IUC2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkMaximumEntropyThresholdImageFilterIF2IUC2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumEntropyThresholdImageFilterIF2IUC2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumEntropyThresholdImageFilterIF2IUC2.Clone = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF2IUC2_Clone, None, itkMaximumEntropyThresholdImageFilterIF2IUC2)
itkMaximumEntropyThresholdImageFilterIF2IUC2.GetPointer = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF2IUC2_GetPointer, None, itkMaximumEntropyThresholdImageFilterIF2IUC2)
itkMaximumEntropyThresholdImageFilterIF2IUC2_swigregister = _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF2IUC2_swigregister
itkMaximumEntropyThresholdImageFilterIF2IUC2_swigregister(itkMaximumEntropyThresholdImageFilterIF2IUC2)

def itkMaximumEntropyThresholdImageFilterIF2IUC2___New_orig__() -> "itkMaximumEntropyThresholdImageFilterIF2IUC2_Pointer":
    """itkMaximumEntropyThresholdImageFilterIF2IUC2___New_orig__() -> itkMaximumEntropyThresholdImageFilterIF2IUC2_Pointer"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF2IUC2___New_orig__()

def itkMaximumEntropyThresholdImageFilterIF2IUC2_cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterIF2IUC2 *":
    """itkMaximumEntropyThresholdImageFilterIF2IUC2_cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterIF2IUC2"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF2IUC2_cast(obj)

class itkMaximumEntropyThresholdImageFilterIF3ISS3(itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF3ISS3):
    """


    Threshold an image using the MaximumEntropy Threshold.

    This filter creates a binary thresholded image that separates an image
    into foreground and background components. The filter computes the
    threshold using the MaximumEntropyThresholdCalculator and applies that
    threshold to the input image using the BinaryThresholdImageFilter.

    Richard Beare. Department of Medicine, Monash University, Melbourne,
    Australia.

    Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA
    de Jouy-en-Josas, France.  This implementation was taken from the
    Insight Journal paper:https://hdl.handle.net/10380/3279
    orhttp://www.insight-journal.org/browse/publication/811

    See:   HistogramThresholdImageFilter

    C++ includes: itkMaximumEntropyThresholdImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkMaximumEntropyThresholdImageFilterIF3ISS3_Pointer":
        """__New_orig__() -> itkMaximumEntropyThresholdImageFilterIF3ISS3_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF3ISS3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkMaximumEntropyThresholdImageFilterIF3ISS3_Pointer":
        """Clone(itkMaximumEntropyThresholdImageFilterIF3ISS3 self) -> itkMaximumEntropyThresholdImageFilterIF3ISS3_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF3ISS3_Clone(self)

    __swig_destroy__ = _itkMaximumEntropyThresholdImageFilterPython.delete_itkMaximumEntropyThresholdImageFilterIF3ISS3

    def cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterIF3ISS3 *":
        """cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterIF3ISS3"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF3ISS3_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self) -> "itkMaximumEntropyThresholdImageFilterIF3ISS3 *":
        """GetPointer(itkMaximumEntropyThresholdImageFilterIF3ISS3 self) -> itkMaximumEntropyThresholdImageFilterIF3ISS3"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF3ISS3_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkMaximumEntropyThresholdImageFilterIF3ISS3

        Create a new object of the class itkMaximumEntropyThresholdImageFilterIF3ISS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMaximumEntropyThresholdImageFilterIF3ISS3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkMaximumEntropyThresholdImageFilterIF3ISS3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumEntropyThresholdImageFilterIF3ISS3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumEntropyThresholdImageFilterIF3ISS3.Clone = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF3ISS3_Clone, None, itkMaximumEntropyThresholdImageFilterIF3ISS3)
itkMaximumEntropyThresholdImageFilterIF3ISS3.GetPointer = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF3ISS3_GetPointer, None, itkMaximumEntropyThresholdImageFilterIF3ISS3)
itkMaximumEntropyThresholdImageFilterIF3ISS3_swigregister = _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF3ISS3_swigregister
itkMaximumEntropyThresholdImageFilterIF3ISS3_swigregister(itkMaximumEntropyThresholdImageFilterIF3ISS3)

def itkMaximumEntropyThresholdImageFilterIF3ISS3___New_orig__() -> "itkMaximumEntropyThresholdImageFilterIF3ISS3_Pointer":
    """itkMaximumEntropyThresholdImageFilterIF3ISS3___New_orig__() -> itkMaximumEntropyThresholdImageFilterIF3ISS3_Pointer"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF3ISS3___New_orig__()

def itkMaximumEntropyThresholdImageFilterIF3ISS3_cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterIF3ISS3 *":
    """itkMaximumEntropyThresholdImageFilterIF3ISS3_cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterIF3ISS3"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF3ISS3_cast(obj)

class itkMaximumEntropyThresholdImageFilterIF3IUC3(itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF3IUC3):
    """


    Threshold an image using the MaximumEntropy Threshold.

    This filter creates a binary thresholded image that separates an image
    into foreground and background components. The filter computes the
    threshold using the MaximumEntropyThresholdCalculator and applies that
    threshold to the input image using the BinaryThresholdImageFilter.

    Richard Beare. Department of Medicine, Monash University, Melbourne,
    Australia.

    Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA
    de Jouy-en-Josas, France.  This implementation was taken from the
    Insight Journal paper:https://hdl.handle.net/10380/3279
    orhttp://www.insight-journal.org/browse/publication/811

    See:   HistogramThresholdImageFilter

    C++ includes: itkMaximumEntropyThresholdImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkMaximumEntropyThresholdImageFilterIF3IUC3_Pointer":
        """__New_orig__() -> itkMaximumEntropyThresholdImageFilterIF3IUC3_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF3IUC3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkMaximumEntropyThresholdImageFilterIF3IUC3_Pointer":
        """Clone(itkMaximumEntropyThresholdImageFilterIF3IUC3 self) -> itkMaximumEntropyThresholdImageFilterIF3IUC3_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF3IUC3_Clone(self)

    __swig_destroy__ = _itkMaximumEntropyThresholdImageFilterPython.delete_itkMaximumEntropyThresholdImageFilterIF3IUC3

    def cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterIF3IUC3 *":
        """cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterIF3IUC3"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF3IUC3_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self) -> "itkMaximumEntropyThresholdImageFilterIF3IUC3 *":
        """GetPointer(itkMaximumEntropyThresholdImageFilterIF3IUC3 self) -> itkMaximumEntropyThresholdImageFilterIF3IUC3"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF3IUC3_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkMaximumEntropyThresholdImageFilterIF3IUC3

        Create a new object of the class itkMaximumEntropyThresholdImageFilterIF3IUC3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMaximumEntropyThresholdImageFilterIF3IUC3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkMaximumEntropyThresholdImageFilterIF3IUC3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumEntropyThresholdImageFilterIF3IUC3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumEntropyThresholdImageFilterIF3IUC3.Clone = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF3IUC3_Clone, None, itkMaximumEntropyThresholdImageFilterIF3IUC3)
itkMaximumEntropyThresholdImageFilterIF3IUC3.GetPointer = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF3IUC3_GetPointer, None, itkMaximumEntropyThresholdImageFilterIF3IUC3)
itkMaximumEntropyThresholdImageFilterIF3IUC3_swigregister = _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF3IUC3_swigregister
itkMaximumEntropyThresholdImageFilterIF3IUC3_swigregister(itkMaximumEntropyThresholdImageFilterIF3IUC3)

def itkMaximumEntropyThresholdImageFilterIF3IUC3___New_orig__() -> "itkMaximumEntropyThresholdImageFilterIF3IUC3_Pointer":
    """itkMaximumEntropyThresholdImageFilterIF3IUC3___New_orig__() -> itkMaximumEntropyThresholdImageFilterIF3IUC3_Pointer"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF3IUC3___New_orig__()

def itkMaximumEntropyThresholdImageFilterIF3IUC3_cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterIF3IUC3 *":
    """itkMaximumEntropyThresholdImageFilterIF3IUC3_cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterIF3IUC3"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIF3IUC3_cast(obj)

class itkMaximumEntropyThresholdImageFilterISS2ISS2(itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS2ISS2):
    """


    Threshold an image using the MaximumEntropy Threshold.

    This filter creates a binary thresholded image that separates an image
    into foreground and background components. The filter computes the
    threshold using the MaximumEntropyThresholdCalculator and applies that
    threshold to the input image using the BinaryThresholdImageFilter.

    Richard Beare. Department of Medicine, Monash University, Melbourne,
    Australia.

    Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA
    de Jouy-en-Josas, France.  This implementation was taken from the
    Insight Journal paper:https://hdl.handle.net/10380/3279
    orhttp://www.insight-journal.org/browse/publication/811

    See:   HistogramThresholdImageFilter

    C++ includes: itkMaximumEntropyThresholdImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkMaximumEntropyThresholdImageFilterISS2ISS2_Pointer":
        """__New_orig__() -> itkMaximumEntropyThresholdImageFilterISS2ISS2_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS2ISS2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkMaximumEntropyThresholdImageFilterISS2ISS2_Pointer":
        """Clone(itkMaximumEntropyThresholdImageFilterISS2ISS2 self) -> itkMaximumEntropyThresholdImageFilterISS2ISS2_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS2ISS2_Clone(self)

    __swig_destroy__ = _itkMaximumEntropyThresholdImageFilterPython.delete_itkMaximumEntropyThresholdImageFilterISS2ISS2

    def cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterISS2ISS2 *":
        """cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterISS2ISS2"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS2ISS2_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self) -> "itkMaximumEntropyThresholdImageFilterISS2ISS2 *":
        """GetPointer(itkMaximumEntropyThresholdImageFilterISS2ISS2 self) -> itkMaximumEntropyThresholdImageFilterISS2ISS2"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS2ISS2_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkMaximumEntropyThresholdImageFilterISS2ISS2

        Create a new object of the class itkMaximumEntropyThresholdImageFilterISS2ISS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMaximumEntropyThresholdImageFilterISS2ISS2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkMaximumEntropyThresholdImageFilterISS2ISS2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumEntropyThresholdImageFilterISS2ISS2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumEntropyThresholdImageFilterISS2ISS2.Clone = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS2ISS2_Clone, None, itkMaximumEntropyThresholdImageFilterISS2ISS2)
itkMaximumEntropyThresholdImageFilterISS2ISS2.GetPointer = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS2ISS2_GetPointer, None, itkMaximumEntropyThresholdImageFilterISS2ISS2)
itkMaximumEntropyThresholdImageFilterISS2ISS2_swigregister = _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS2ISS2_swigregister
itkMaximumEntropyThresholdImageFilterISS2ISS2_swigregister(itkMaximumEntropyThresholdImageFilterISS2ISS2)

def itkMaximumEntropyThresholdImageFilterISS2ISS2___New_orig__() -> "itkMaximumEntropyThresholdImageFilterISS2ISS2_Pointer":
    """itkMaximumEntropyThresholdImageFilterISS2ISS2___New_orig__() -> itkMaximumEntropyThresholdImageFilterISS2ISS2_Pointer"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS2ISS2___New_orig__()

def itkMaximumEntropyThresholdImageFilterISS2ISS2_cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterISS2ISS2 *":
    """itkMaximumEntropyThresholdImageFilterISS2ISS2_cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterISS2ISS2"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS2ISS2_cast(obj)

class itkMaximumEntropyThresholdImageFilterISS2IUC2(itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS2IUC2):
    """


    Threshold an image using the MaximumEntropy Threshold.

    This filter creates a binary thresholded image that separates an image
    into foreground and background components. The filter computes the
    threshold using the MaximumEntropyThresholdCalculator and applies that
    threshold to the input image using the BinaryThresholdImageFilter.

    Richard Beare. Department of Medicine, Monash University, Melbourne,
    Australia.

    Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA
    de Jouy-en-Josas, France.  This implementation was taken from the
    Insight Journal paper:https://hdl.handle.net/10380/3279
    orhttp://www.insight-journal.org/browse/publication/811

    See:   HistogramThresholdImageFilter

    C++ includes: itkMaximumEntropyThresholdImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkMaximumEntropyThresholdImageFilterISS2IUC2_Pointer":
        """__New_orig__() -> itkMaximumEntropyThresholdImageFilterISS2IUC2_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS2IUC2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkMaximumEntropyThresholdImageFilterISS2IUC2_Pointer":
        """Clone(itkMaximumEntropyThresholdImageFilterISS2IUC2 self) -> itkMaximumEntropyThresholdImageFilterISS2IUC2_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS2IUC2_Clone(self)

    __swig_destroy__ = _itkMaximumEntropyThresholdImageFilterPython.delete_itkMaximumEntropyThresholdImageFilterISS2IUC2

    def cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterISS2IUC2 *":
        """cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterISS2IUC2"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS2IUC2_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self) -> "itkMaximumEntropyThresholdImageFilterISS2IUC2 *":
        """GetPointer(itkMaximumEntropyThresholdImageFilterISS2IUC2 self) -> itkMaximumEntropyThresholdImageFilterISS2IUC2"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS2IUC2_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkMaximumEntropyThresholdImageFilterISS2IUC2

        Create a new object of the class itkMaximumEntropyThresholdImageFilterISS2IUC2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMaximumEntropyThresholdImageFilterISS2IUC2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkMaximumEntropyThresholdImageFilterISS2IUC2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumEntropyThresholdImageFilterISS2IUC2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumEntropyThresholdImageFilterISS2IUC2.Clone = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS2IUC2_Clone, None, itkMaximumEntropyThresholdImageFilterISS2IUC2)
itkMaximumEntropyThresholdImageFilterISS2IUC2.GetPointer = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS2IUC2_GetPointer, None, itkMaximumEntropyThresholdImageFilterISS2IUC2)
itkMaximumEntropyThresholdImageFilterISS2IUC2_swigregister = _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS2IUC2_swigregister
itkMaximumEntropyThresholdImageFilterISS2IUC2_swigregister(itkMaximumEntropyThresholdImageFilterISS2IUC2)

def itkMaximumEntropyThresholdImageFilterISS2IUC2___New_orig__() -> "itkMaximumEntropyThresholdImageFilterISS2IUC2_Pointer":
    """itkMaximumEntropyThresholdImageFilterISS2IUC2___New_orig__() -> itkMaximumEntropyThresholdImageFilterISS2IUC2_Pointer"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS2IUC2___New_orig__()

def itkMaximumEntropyThresholdImageFilterISS2IUC2_cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterISS2IUC2 *":
    """itkMaximumEntropyThresholdImageFilterISS2IUC2_cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterISS2IUC2"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS2IUC2_cast(obj)

class itkMaximumEntropyThresholdImageFilterISS3ISS3(itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS3ISS3):
    """


    Threshold an image using the MaximumEntropy Threshold.

    This filter creates a binary thresholded image that separates an image
    into foreground and background components. The filter computes the
    threshold using the MaximumEntropyThresholdCalculator and applies that
    threshold to the input image using the BinaryThresholdImageFilter.

    Richard Beare. Department of Medicine, Monash University, Melbourne,
    Australia.

    Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA
    de Jouy-en-Josas, France.  This implementation was taken from the
    Insight Journal paper:https://hdl.handle.net/10380/3279
    orhttp://www.insight-journal.org/browse/publication/811

    See:   HistogramThresholdImageFilter

    C++ includes: itkMaximumEntropyThresholdImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkMaximumEntropyThresholdImageFilterISS3ISS3_Pointer":
        """__New_orig__() -> itkMaximumEntropyThresholdImageFilterISS3ISS3_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS3ISS3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkMaximumEntropyThresholdImageFilterISS3ISS3_Pointer":
        """Clone(itkMaximumEntropyThresholdImageFilterISS3ISS3 self) -> itkMaximumEntropyThresholdImageFilterISS3ISS3_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS3ISS3_Clone(self)

    __swig_destroy__ = _itkMaximumEntropyThresholdImageFilterPython.delete_itkMaximumEntropyThresholdImageFilterISS3ISS3

    def cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterISS3ISS3 *":
        """cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterISS3ISS3"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS3ISS3_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self) -> "itkMaximumEntropyThresholdImageFilterISS3ISS3 *":
        """GetPointer(itkMaximumEntropyThresholdImageFilterISS3ISS3 self) -> itkMaximumEntropyThresholdImageFilterISS3ISS3"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS3ISS3_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkMaximumEntropyThresholdImageFilterISS3ISS3

        Create a new object of the class itkMaximumEntropyThresholdImageFilterISS3ISS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMaximumEntropyThresholdImageFilterISS3ISS3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkMaximumEntropyThresholdImageFilterISS3ISS3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumEntropyThresholdImageFilterISS3ISS3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumEntropyThresholdImageFilterISS3ISS3.Clone = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS3ISS3_Clone, None, itkMaximumEntropyThresholdImageFilterISS3ISS3)
itkMaximumEntropyThresholdImageFilterISS3ISS3.GetPointer = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS3ISS3_GetPointer, None, itkMaximumEntropyThresholdImageFilterISS3ISS3)
itkMaximumEntropyThresholdImageFilterISS3ISS3_swigregister = _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS3ISS3_swigregister
itkMaximumEntropyThresholdImageFilterISS3ISS3_swigregister(itkMaximumEntropyThresholdImageFilterISS3ISS3)

def itkMaximumEntropyThresholdImageFilterISS3ISS3___New_orig__() -> "itkMaximumEntropyThresholdImageFilterISS3ISS3_Pointer":
    """itkMaximumEntropyThresholdImageFilterISS3ISS3___New_orig__() -> itkMaximumEntropyThresholdImageFilterISS3ISS3_Pointer"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS3ISS3___New_orig__()

def itkMaximumEntropyThresholdImageFilterISS3ISS3_cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterISS3ISS3 *":
    """itkMaximumEntropyThresholdImageFilterISS3ISS3_cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterISS3ISS3"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS3ISS3_cast(obj)

class itkMaximumEntropyThresholdImageFilterISS3IUC3(itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS3IUC3):
    """


    Threshold an image using the MaximumEntropy Threshold.

    This filter creates a binary thresholded image that separates an image
    into foreground and background components. The filter computes the
    threshold using the MaximumEntropyThresholdCalculator and applies that
    threshold to the input image using the BinaryThresholdImageFilter.

    Richard Beare. Department of Medicine, Monash University, Melbourne,
    Australia.

    Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA
    de Jouy-en-Josas, France.  This implementation was taken from the
    Insight Journal paper:https://hdl.handle.net/10380/3279
    orhttp://www.insight-journal.org/browse/publication/811

    See:   HistogramThresholdImageFilter

    C++ includes: itkMaximumEntropyThresholdImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkMaximumEntropyThresholdImageFilterISS3IUC3_Pointer":
        """__New_orig__() -> itkMaximumEntropyThresholdImageFilterISS3IUC3_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS3IUC3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkMaximumEntropyThresholdImageFilterISS3IUC3_Pointer":
        """Clone(itkMaximumEntropyThresholdImageFilterISS3IUC3 self) -> itkMaximumEntropyThresholdImageFilterISS3IUC3_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS3IUC3_Clone(self)

    __swig_destroy__ = _itkMaximumEntropyThresholdImageFilterPython.delete_itkMaximumEntropyThresholdImageFilterISS3IUC3

    def cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterISS3IUC3 *":
        """cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterISS3IUC3"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS3IUC3_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self) -> "itkMaximumEntropyThresholdImageFilterISS3IUC3 *":
        """GetPointer(itkMaximumEntropyThresholdImageFilterISS3IUC3 self) -> itkMaximumEntropyThresholdImageFilterISS3IUC3"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS3IUC3_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkMaximumEntropyThresholdImageFilterISS3IUC3

        Create a new object of the class itkMaximumEntropyThresholdImageFilterISS3IUC3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMaximumEntropyThresholdImageFilterISS3IUC3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkMaximumEntropyThresholdImageFilterISS3IUC3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumEntropyThresholdImageFilterISS3IUC3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumEntropyThresholdImageFilterISS3IUC3.Clone = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS3IUC3_Clone, None, itkMaximumEntropyThresholdImageFilterISS3IUC3)
itkMaximumEntropyThresholdImageFilterISS3IUC3.GetPointer = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS3IUC3_GetPointer, None, itkMaximumEntropyThresholdImageFilterISS3IUC3)
itkMaximumEntropyThresholdImageFilterISS3IUC3_swigregister = _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS3IUC3_swigregister
itkMaximumEntropyThresholdImageFilterISS3IUC3_swigregister(itkMaximumEntropyThresholdImageFilterISS3IUC3)

def itkMaximumEntropyThresholdImageFilterISS3IUC3___New_orig__() -> "itkMaximumEntropyThresholdImageFilterISS3IUC3_Pointer":
    """itkMaximumEntropyThresholdImageFilterISS3IUC3___New_orig__() -> itkMaximumEntropyThresholdImageFilterISS3IUC3_Pointer"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS3IUC3___New_orig__()

def itkMaximumEntropyThresholdImageFilterISS3IUC3_cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterISS3IUC3 *":
    """itkMaximumEntropyThresholdImageFilterISS3IUC3_cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterISS3IUC3"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterISS3IUC3_cast(obj)

class itkMaximumEntropyThresholdImageFilterIUC2ISS2(itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC2ISS2):
    """


    Threshold an image using the MaximumEntropy Threshold.

    This filter creates a binary thresholded image that separates an image
    into foreground and background components. The filter computes the
    threshold using the MaximumEntropyThresholdCalculator and applies that
    threshold to the input image using the BinaryThresholdImageFilter.

    Richard Beare. Department of Medicine, Monash University, Melbourne,
    Australia.

    Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA
    de Jouy-en-Josas, France.  This implementation was taken from the
    Insight Journal paper:https://hdl.handle.net/10380/3279
    orhttp://www.insight-journal.org/browse/publication/811

    See:   HistogramThresholdImageFilter

    C++ includes: itkMaximumEntropyThresholdImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkMaximumEntropyThresholdImageFilterIUC2ISS2_Pointer":
        """__New_orig__() -> itkMaximumEntropyThresholdImageFilterIUC2ISS2_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC2ISS2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkMaximumEntropyThresholdImageFilterIUC2ISS2_Pointer":
        """Clone(itkMaximumEntropyThresholdImageFilterIUC2ISS2 self) -> itkMaximumEntropyThresholdImageFilterIUC2ISS2_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC2ISS2_Clone(self)

    __swig_destroy__ = _itkMaximumEntropyThresholdImageFilterPython.delete_itkMaximumEntropyThresholdImageFilterIUC2ISS2

    def cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterIUC2ISS2 *":
        """cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterIUC2ISS2"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC2ISS2_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self) -> "itkMaximumEntropyThresholdImageFilterIUC2ISS2 *":
        """GetPointer(itkMaximumEntropyThresholdImageFilterIUC2ISS2 self) -> itkMaximumEntropyThresholdImageFilterIUC2ISS2"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC2ISS2_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkMaximumEntropyThresholdImageFilterIUC2ISS2

        Create a new object of the class itkMaximumEntropyThresholdImageFilterIUC2ISS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMaximumEntropyThresholdImageFilterIUC2ISS2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkMaximumEntropyThresholdImageFilterIUC2ISS2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumEntropyThresholdImageFilterIUC2ISS2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumEntropyThresholdImageFilterIUC2ISS2.Clone = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC2ISS2_Clone, None, itkMaximumEntropyThresholdImageFilterIUC2ISS2)
itkMaximumEntropyThresholdImageFilterIUC2ISS2.GetPointer = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC2ISS2_GetPointer, None, itkMaximumEntropyThresholdImageFilterIUC2ISS2)
itkMaximumEntropyThresholdImageFilterIUC2ISS2_swigregister = _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC2ISS2_swigregister
itkMaximumEntropyThresholdImageFilterIUC2ISS2_swigregister(itkMaximumEntropyThresholdImageFilterIUC2ISS2)

def itkMaximumEntropyThresholdImageFilterIUC2ISS2___New_orig__() -> "itkMaximumEntropyThresholdImageFilterIUC2ISS2_Pointer":
    """itkMaximumEntropyThresholdImageFilterIUC2ISS2___New_orig__() -> itkMaximumEntropyThresholdImageFilterIUC2ISS2_Pointer"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC2ISS2___New_orig__()

def itkMaximumEntropyThresholdImageFilterIUC2ISS2_cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterIUC2ISS2 *":
    """itkMaximumEntropyThresholdImageFilterIUC2ISS2_cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterIUC2ISS2"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC2ISS2_cast(obj)

class itkMaximumEntropyThresholdImageFilterIUC2IUC2(itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC2IUC2):
    """


    Threshold an image using the MaximumEntropy Threshold.

    This filter creates a binary thresholded image that separates an image
    into foreground and background components. The filter computes the
    threshold using the MaximumEntropyThresholdCalculator and applies that
    threshold to the input image using the BinaryThresholdImageFilter.

    Richard Beare. Department of Medicine, Monash University, Melbourne,
    Australia.

    Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA
    de Jouy-en-Josas, France.  This implementation was taken from the
    Insight Journal paper:https://hdl.handle.net/10380/3279
    orhttp://www.insight-journal.org/browse/publication/811

    See:   HistogramThresholdImageFilter

    C++ includes: itkMaximumEntropyThresholdImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkMaximumEntropyThresholdImageFilterIUC2IUC2_Pointer":
        """__New_orig__() -> itkMaximumEntropyThresholdImageFilterIUC2IUC2_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC2IUC2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkMaximumEntropyThresholdImageFilterIUC2IUC2_Pointer":
        """Clone(itkMaximumEntropyThresholdImageFilterIUC2IUC2 self) -> itkMaximumEntropyThresholdImageFilterIUC2IUC2_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC2IUC2_Clone(self)

    __swig_destroy__ = _itkMaximumEntropyThresholdImageFilterPython.delete_itkMaximumEntropyThresholdImageFilterIUC2IUC2

    def cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterIUC2IUC2 *":
        """cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterIUC2IUC2"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC2IUC2_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self) -> "itkMaximumEntropyThresholdImageFilterIUC2IUC2 *":
        """GetPointer(itkMaximumEntropyThresholdImageFilterIUC2IUC2 self) -> itkMaximumEntropyThresholdImageFilterIUC2IUC2"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC2IUC2_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkMaximumEntropyThresholdImageFilterIUC2IUC2

        Create a new object of the class itkMaximumEntropyThresholdImageFilterIUC2IUC2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMaximumEntropyThresholdImageFilterIUC2IUC2.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkMaximumEntropyThresholdImageFilterIUC2IUC2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumEntropyThresholdImageFilterIUC2IUC2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumEntropyThresholdImageFilterIUC2IUC2.Clone = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC2IUC2_Clone, None, itkMaximumEntropyThresholdImageFilterIUC2IUC2)
itkMaximumEntropyThresholdImageFilterIUC2IUC2.GetPointer = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC2IUC2_GetPointer, None, itkMaximumEntropyThresholdImageFilterIUC2IUC2)
itkMaximumEntropyThresholdImageFilterIUC2IUC2_swigregister = _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC2IUC2_swigregister
itkMaximumEntropyThresholdImageFilterIUC2IUC2_swigregister(itkMaximumEntropyThresholdImageFilterIUC2IUC2)

def itkMaximumEntropyThresholdImageFilterIUC2IUC2___New_orig__() -> "itkMaximumEntropyThresholdImageFilterIUC2IUC2_Pointer":
    """itkMaximumEntropyThresholdImageFilterIUC2IUC2___New_orig__() -> itkMaximumEntropyThresholdImageFilterIUC2IUC2_Pointer"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC2IUC2___New_orig__()

def itkMaximumEntropyThresholdImageFilterIUC2IUC2_cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterIUC2IUC2 *":
    """itkMaximumEntropyThresholdImageFilterIUC2IUC2_cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterIUC2IUC2"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC2IUC2_cast(obj)

class itkMaximumEntropyThresholdImageFilterIUC3ISS3(itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC3ISS3):
    """


    Threshold an image using the MaximumEntropy Threshold.

    This filter creates a binary thresholded image that separates an image
    into foreground and background components. The filter computes the
    threshold using the MaximumEntropyThresholdCalculator and applies that
    threshold to the input image using the BinaryThresholdImageFilter.

    Richard Beare. Department of Medicine, Monash University, Melbourne,
    Australia.

    Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA
    de Jouy-en-Josas, France.  This implementation was taken from the
    Insight Journal paper:https://hdl.handle.net/10380/3279
    orhttp://www.insight-journal.org/browse/publication/811

    See:   HistogramThresholdImageFilter

    C++ includes: itkMaximumEntropyThresholdImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkMaximumEntropyThresholdImageFilterIUC3ISS3_Pointer":
        """__New_orig__() -> itkMaximumEntropyThresholdImageFilterIUC3ISS3_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC3ISS3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkMaximumEntropyThresholdImageFilterIUC3ISS3_Pointer":
        """Clone(itkMaximumEntropyThresholdImageFilterIUC3ISS3 self) -> itkMaximumEntropyThresholdImageFilterIUC3ISS3_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC3ISS3_Clone(self)

    __swig_destroy__ = _itkMaximumEntropyThresholdImageFilterPython.delete_itkMaximumEntropyThresholdImageFilterIUC3ISS3

    def cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterIUC3ISS3 *":
        """cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterIUC3ISS3"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC3ISS3_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self) -> "itkMaximumEntropyThresholdImageFilterIUC3ISS3 *":
        """GetPointer(itkMaximumEntropyThresholdImageFilterIUC3ISS3 self) -> itkMaximumEntropyThresholdImageFilterIUC3ISS3"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC3ISS3_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkMaximumEntropyThresholdImageFilterIUC3ISS3

        Create a new object of the class itkMaximumEntropyThresholdImageFilterIUC3ISS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMaximumEntropyThresholdImageFilterIUC3ISS3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkMaximumEntropyThresholdImageFilterIUC3ISS3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumEntropyThresholdImageFilterIUC3ISS3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumEntropyThresholdImageFilterIUC3ISS3.Clone = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC3ISS3_Clone, None, itkMaximumEntropyThresholdImageFilterIUC3ISS3)
itkMaximumEntropyThresholdImageFilterIUC3ISS3.GetPointer = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC3ISS3_GetPointer, None, itkMaximumEntropyThresholdImageFilterIUC3ISS3)
itkMaximumEntropyThresholdImageFilterIUC3ISS3_swigregister = _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC3ISS3_swigregister
itkMaximumEntropyThresholdImageFilterIUC3ISS3_swigregister(itkMaximumEntropyThresholdImageFilterIUC3ISS3)

def itkMaximumEntropyThresholdImageFilterIUC3ISS3___New_orig__() -> "itkMaximumEntropyThresholdImageFilterIUC3ISS3_Pointer":
    """itkMaximumEntropyThresholdImageFilterIUC3ISS3___New_orig__() -> itkMaximumEntropyThresholdImageFilterIUC3ISS3_Pointer"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC3ISS3___New_orig__()

def itkMaximumEntropyThresholdImageFilterIUC3ISS3_cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterIUC3ISS3 *":
    """itkMaximumEntropyThresholdImageFilterIUC3ISS3_cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterIUC3ISS3"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC3ISS3_cast(obj)

class itkMaximumEntropyThresholdImageFilterIUC3IUC3(itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC3IUC3):
    """


    Threshold an image using the MaximumEntropy Threshold.

    This filter creates a binary thresholded image that separates an image
    into foreground and background components. The filter computes the
    threshold using the MaximumEntropyThresholdCalculator and applies that
    threshold to the input image using the BinaryThresholdImageFilter.

    Richard Beare. Department of Medicine, Monash University, Melbourne,
    Australia.

    Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA
    de Jouy-en-Josas, France.  This implementation was taken from the
    Insight Journal paper:https://hdl.handle.net/10380/3279
    orhttp://www.insight-journal.org/browse/publication/811

    See:   HistogramThresholdImageFilter

    C++ includes: itkMaximumEntropyThresholdImageFilter.h 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def __New_orig__() -> "itkMaximumEntropyThresholdImageFilterIUC3IUC3_Pointer":
        """__New_orig__() -> itkMaximumEntropyThresholdImageFilterIUC3IUC3_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC3IUC3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)

    def Clone(self) -> "itkMaximumEntropyThresholdImageFilterIUC3IUC3_Pointer":
        """Clone(itkMaximumEntropyThresholdImageFilterIUC3IUC3 self) -> itkMaximumEntropyThresholdImageFilterIUC3IUC3_Pointer"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC3IUC3_Clone(self)

    __swig_destroy__ = _itkMaximumEntropyThresholdImageFilterPython.delete_itkMaximumEntropyThresholdImageFilterIUC3IUC3

    def cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterIUC3IUC3 *":
        """cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterIUC3IUC3"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC3IUC3_cast(obj)

    cast = staticmethod(cast)

    def GetPointer(self) -> "itkMaximumEntropyThresholdImageFilterIUC3IUC3 *":
        """GetPointer(itkMaximumEntropyThresholdImageFilterIUC3IUC3 self) -> itkMaximumEntropyThresholdImageFilterIUC3IUC3"""
        return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC3IUC3_GetPointer(self)


    def New(*args, **kargs):
        """New() -> itkMaximumEntropyThresholdImageFilterIUC3IUC3

        Create a new object of the class itkMaximumEntropyThresholdImageFilterIUC3IUC3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMaximumEntropyThresholdImageFilterIUC3IUC3.New( reader, Threshold=10 )

        is (most of the time) equivalent to:

          obj = itkMaximumEntropyThresholdImageFilterIUC3IUC3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumEntropyThresholdImageFilterIUC3IUC3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumEntropyThresholdImageFilterIUC3IUC3.Clone = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC3IUC3_Clone, None, itkMaximumEntropyThresholdImageFilterIUC3IUC3)
itkMaximumEntropyThresholdImageFilterIUC3IUC3.GetPointer = new_instancemethod(_itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC3IUC3_GetPointer, None, itkMaximumEntropyThresholdImageFilterIUC3IUC3)
itkMaximumEntropyThresholdImageFilterIUC3IUC3_swigregister = _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC3IUC3_swigregister
itkMaximumEntropyThresholdImageFilterIUC3IUC3_swigregister(itkMaximumEntropyThresholdImageFilterIUC3IUC3)

def itkMaximumEntropyThresholdImageFilterIUC3IUC3___New_orig__() -> "itkMaximumEntropyThresholdImageFilterIUC3IUC3_Pointer":
    """itkMaximumEntropyThresholdImageFilterIUC3IUC3___New_orig__() -> itkMaximumEntropyThresholdImageFilterIUC3IUC3_Pointer"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC3IUC3___New_orig__()

def itkMaximumEntropyThresholdImageFilterIUC3IUC3_cast(obj: 'itkLightObject') -> "itkMaximumEntropyThresholdImageFilterIUC3IUC3 *":
    """itkMaximumEntropyThresholdImageFilterIUC3IUC3_cast(itkLightObject obj) -> itkMaximumEntropyThresholdImageFilterIUC3IUC3"""
    return _itkMaximumEntropyThresholdImageFilterPython.itkMaximumEntropyThresholdImageFilterIUC3IUC3_cast(obj)



