
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-04T13:21:30-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "eee4eb7f1f8680e8669eb37cb626fd7c7bfe9ff1",
 "version": "1.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
