---
# This playbook will provision OpenShift resources

- name: allocate openshift output variables
  set_fact:
    topology_outputs_openshift_resources: []

- name: provision openshift resources
  include: provision_openshift_resources.yml
  with_items: "{{ openshift_res_grps }}"
  loop_control:
    loop_var: resource_group
