---
- name: set API server
  set_fact:
    openshift_api_endpoint: "{{ resource_group.api_endpoint }}"

- name: call openshift endpoint
  include: openshift_api_call.yml
  with_items: "{{ resource_group.resources }}"
  loop_control:
    loop_var: resource
