
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-24T11:05:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e8bed450fbb263cf66d9ac5c0fa129bd96c5add",
 "version": "0.4.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
