---
#global settings
my_server_id: 100
replica_batch_size: 1000
batch_retention: '1 day'
copy_max_memory: 300M
my_database:  db_replica
pg_database: db_replication
#copy mode when initialising, it can be file (dumps to out_dir a csv file) or direct (copy the file in memory)
copy_mode: 'file'  
out_dir: /tmp
source_name: 'default'
dest_schema: 'my_schema'


#seconds between each replica loop
sleep_loop: 10 

#Pause the replica for the given amount of seconds if a reindex process is found
pause_on_reindex: Yes
sleep_on_reindex: 30

#list the application names which are supposed to reindex the database
reindex_app_names:
    - 'reindexdb'
    - 'my_custom_reindex'

hexify: 
    - 'blob'
    - 'tinyblob'
    - 'mediumblob'
    - 'longblob'
    - 'binary'
    - 'varbinary'
    - 'geometry'
 
pid_dir: '~/.pg_chameleon/pid/'


log_dir: '~/.pg_chameleon/logs/'
log_level: 'debug'
log_dest: 'stdout'
log_days_keep: 10
#log_dest: 'file'
#log_level: 'info'
#log_level: 'debug'


#mysql connection's charset. 
my_charset: 'utf8'
#postgresql connection's charset. 
pg_charset: 'utf8'
#include tables only
tables_limit:
    

#mysql slave setup
mysql_conn:
    host: localhost
    port: 3306
    user: replication_username
    passwd: never_commit_passwords

#postgres connection
pg_conn:
    host: localhost
    port: 5432
    user: replication_username
    password: never_commit_passwords

# type_override allows the user to override the default type conversion into a different one. 
# override_to specifies the destination type which must be a postgresql type and the type cast should be possible
# override_tables specifies which tables the override apply. If set to "*" then applies to all tables in the replicated schema
# the override applies during the init_replica,sync_tables proces and for each matching DDL (create table/alter table)
type_override:
    "tinyint(1)":
        override_to: boolean
        override_tables:
            - "*"
