language: python
cache: pip

matrix:
  include:
    - { python: '2.7', env: TOXENV=py27 }
    - { python: '3.4', env: TOXENV=py34 }
    - { python: '3.5', env: TOXENV=py35 }
    - { python: '3.6', env: TOXENV=py36 }
    - { python: 'pypy', env: TOXENV=pypy }
    - { python: 'pypy3', env: TOXENV=pypy3 }

    # Report coverage for the latest Python 2 and 3 versions
    - { python: '2.7', env: TOXENV=py27-codecov }
    - { python: '3.6', env: TOXENV=py36-codecov }

# Avoid overriding the default install step,
# so that automatic pip caching works.
#
# See: https://github.com/travis-ci/travis-ci/issues/3239
#
before_script:
  - pip install tox

script:
  - tox
