# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ModelManagementAccountUpdateProperties(Model):
    """The payload for patching the Model Management Account.

    :param tags: Contains resource tags defined as key/value pairs.
    :type tags: dict
    :param sku: The SKU of Model Management Account
    :type sku: :class:`Sku <modelmanagementaccounts.models.Sku>`
    :param description: The description of the Model Management Account.
    :type description: str
    """

    _attribute_map = {
        'tags': {'key': 'tags', 'type': '{str}'},
        'sku': {'key': 'sku', 'type': 'Sku'},
        'description': {'key': 'properties.description', 'type': 'str'},
    }

    def __init__(self, tags=None, sku=None, description=None):
        self.tags = tags
        self.sku = sku
        self.description = description
