# coding: utf-8

"""
    style-api

    This is a API document for Stylens Service

    OpenAPI spec version: 0.0.1
    Contact: master@bluehack.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import stylelens_sdk
from stylelens_sdk.rest import ApiException
from stylelens_sdk.models.get_products_response import GetProductsResponse


class TestGetProductsResponse(unittest.TestCase):
    """ GetProductsResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetProductsResponse(self):
        """
        Test GetProductsResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = stylelens_sdk.models.get_products_response.GetProductsResponse()
        pass


if __name__ == '__main__':
    unittest.main()
