
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-13T08:36:43+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d78cd8064ad1914ddca4ead8f8a16bae2c87e47f",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
