# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toktokkie/ui/qt/qt_designer/ebook_config.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EbookConfig(object):
    def setupUi(self, EbookConfig):
        EbookConfig.setObjectName("EbookConfig")
        EbookConfig.resize(752, 712)
        self.gridLayout = QtWidgets.QGridLayout(EbookConfig)
        self.gridLayout.setObjectName("gridLayout")
        self.series_name_edit = QtWidgets.QLineEdit(EbookConfig)
        self.series_name_edit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.series_name_edit.sizePolicy().hasHeightForWidth())
        self.series_name_edit.setSizePolicy(sizePolicy)
        self.series_name_edit.setMinimumSize(QtCore.QSize(134, 0))
        self.series_name_edit.setFrame(False)
        self.series_name_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.series_name_edit.setObjectName("series_name_edit")
        self.gridLayout.addWidget(self.series_name_edit, 1, 0, 1, 1)
        self.folder_icon_label = QtWidgets.QLabel(EbookConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folder_icon_label.sizePolicy().hasHeightForWidth())
        self.folder_icon_label.setSizePolicy(sizePolicy)
        self.folder_icon_label.setMaximumSize(QtCore.QSize(420, 600))
        self.folder_icon_label.setText("")
        self.folder_icon_label.setPixmap(QtGui.QPixmap("../../../../../../../Downloads/main.jpg"))
        self.folder_icon_label.setScaledContents(True)
        self.folder_icon_label.setAlignment(QtCore.Qt.AlignCenter)
        self.folder_icon_label.setObjectName("folder_icon_label")
        self.gridLayout.addWidget(self.folder_icon_label, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(EbookConfig)
        self.frame.setEnabled(True)
        self.frame.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tags_edit = QtWidgets.QLineEdit(self.frame)
        self.tags_edit.setText("")
        self.tags_edit.setObjectName("tags_edit")
        self.gridLayout_2.addWidget(self.tags_edit, 1, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.author_edit = QtWidgets.QLineEdit(self.frame)
        self.author_edit.setText("")
        self.author_edit.setObjectName("author_edit")
        self.gridLayout_2.addWidget(self.author_edit, 2, 1, 1, 2)
        self.media_type_combo_box = QtWidgets.QComboBox(self.frame)
        self.media_type_combo_box.setObjectName("media_type_combo_box")
        self.gridLayout_2.addWidget(self.media_type_combo_box, 0, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.isbn_edit = QtWidgets.QLineEdit(self.frame)
        self.isbn_edit.setText("")
        self.isbn_edit.setObjectName("isbn_edit")
        self.gridLayout_2.addWidget(self.isbn_edit, 3, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.confirm_changes_button = QtWidgets.QPushButton(self.frame)
        self.confirm_changes_button.setObjectName("confirm_changes_button")
        self.gridLayout_2.addWidget(self.confirm_changes_button, 5, 0, 1, 3)
        self.gridLayout.addWidget(self.frame, 0, 1, 7, 1)
        self.open_directory_button = QtWidgets.QPushButton(EbookConfig)
        self.open_directory_button.setObjectName("open_directory_button")
        self.gridLayout.addWidget(self.open_directory_button, 5, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 0, 1, 1)

        self.retranslateUi(EbookConfig)
        QtCore.QMetaObject.connectSlotsByName(EbookConfig)
        EbookConfig.setTabOrder(self.series_name_edit, self.media_type_combo_box)
        EbookConfig.setTabOrder(self.media_type_combo_box, self.tags_edit)
        EbookConfig.setTabOrder(self.tags_edit, self.author_edit)
        EbookConfig.setTabOrder(self.author_edit, self.isbn_edit)
        EbookConfig.setTabOrder(self.isbn_edit, self.confirm_changes_button)
        EbookConfig.setTabOrder(self.confirm_changes_button, self.open_directory_button)

    def retranslateUi(self, EbookConfig):
        _translate = QtCore.QCoreApplication.translate
        EbookConfig.setWindowTitle(_translate("EbookConfig", "Form"))
        self.series_name_edit.setText(_translate("EbookConfig", "Series Name"))
        self.label_6.setText(_translate("EbookConfig", "Author"))
        self.label_3.setText(_translate("EbookConfig", "Tags"))
        self.label_4.setText(_translate("EbookConfig", "Media Type"))
        self.label_7.setText(_translate("EbookConfig", "ISBN"))
        self.confirm_changes_button.setText(_translate("EbookConfig", "Confirm Changes"))
        self.open_directory_button.setText(_translate("EbookConfig", "Open Directory"))

