# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toktokkie/ui/qt/qt_designer/xdcc_download_manager.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_XDCCDownloadManagerWindow(object):
    def setupUi(self, XDCCDownloadManagerWindow):
        XDCCDownloadManagerWindow.setObjectName("XDCCDownloadManagerWindow")
        XDCCDownloadManagerWindow.resize(1056, 732)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(XDCCDownloadManagerWindow.sizePolicy().hasHeightForWidth())
        XDCCDownloadManagerWindow.setSizePolicy(sizePolicy)
        XDCCDownloadManagerWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(XDCCDownloadManagerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.season_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        self.season_spin_box.setObjectName("season_spin_box")
        self.gridLayout.addWidget(self.season_spin_box, 2, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.move_up_button = QtWidgets.QPushButton(self.centralwidget)
        self.move_up_button.setObjectName("move_up_button")
        self.gridLayout_5.addWidget(self.move_up_button, 1, 0, 1, 1)
        self.move_down_button = QtWidgets.QPushButton(self.centralwidget)
        self.move_down_button.setObjectName("move_down_button")
        self.gridLayout_5.addWidget(self.move_down_button, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 9, 7, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.search_engine_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.search_engine_combo_box.setObjectName("search_engine_combo_box")
        self.gridLayout.addWidget(self.search_engine_combo_box, 11, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 11, 0, 1, 1)
        self.download_button = QtWidgets.QPushButton(self.centralwidget)
        self.download_button.setObjectName("download_button")
        self.gridLayout.addWidget(self.download_button, 11, 7, 1, 1)
        self.auto_rename_check = QtWidgets.QCheckBox(self.centralwidget)
        self.auto_rename_check.setEnabled(True)
        self.auto_rename_check.setChecked(True)
        self.auto_rename_check.setObjectName("auto_rename_check")
        self.gridLayout.addWidget(self.auto_rename_check, 5, 0, 1, 2)
        self.iconize_check = QtWidgets.QCheckBox(self.centralwidget)
        self.iconize_check.setEnabled(True)
        self.iconize_check.setChecked(True)
        self.iconize_check.setTristate(False)
        self.iconize_check.setObjectName("iconize_check")
        self.gridLayout.addWidget(self.iconize_check, 5, 2, 1, 1)
        self.renaming_scheme_combo_box = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.renaming_scheme_combo_box.sizePolicy().hasHeightForWidth())
        self.renaming_scheme_combo_box.setSizePolicy(sizePolicy)
        self.renaming_scheme_combo_box.setMaximumSize(QtCore.QSize(150, 16777215))
        self.renaming_scheme_combo_box.setObjectName("renaming_scheme_combo_box")
        self.gridLayout.addWidget(self.renaming_scheme_combo_box, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem, 5, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.show_name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.show_name_edit.setObjectName("show_name_edit")
        self.gridLayout.addWidget(self.show_name_edit, 1, 1, 1, 4)
        self.directory_browse_button = QtWidgets.QPushButton(self.centralwidget)
        self.directory_browse_button.setObjectName("directory_browse_button")
        self.gridLayout.addWidget(self.directory_browse_button, 0, 1, 1, 1)
        self.episode_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        self.episode_spin_box.setObjectName("episode_spin_box")
        self.gridLayout.addWidget(self.episode_spin_box, 2, 4, 1, 1)
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setObjectName("search_button")
        self.gridLayout.addWidget(self.search_button, 11, 3, 1, 1)
        self.directory_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.directory_edit.setObjectName("directory_edit")
        self.gridLayout.addWidget(self.directory_edit, 0, 2, 1, 3)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.total_progress_bar = QtWidgets.QProgressBar(self.widget)
        self.total_progress_bar.setProperty("value", 0)
        self.total_progress_bar.setInvertedAppearance(True)
        self.total_progress_bar.setObjectName("total_progress_bar")
        self.gridLayout_3.addWidget(self.total_progress_bar, 2, 1, 1, 1)
        self.single_progress_bar = QtWidgets.QProgressBar(self.widget)
        self.single_progress_bar.setProperty("value", 0)
        self.single_progress_bar.setInvertedAppearance(True)
        self.single_progress_bar.setObjectName("single_progress_bar")
        self.gridLayout_3.addWidget(self.single_progress_bar, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 5, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 4, 2, 1, 1)
        self.average_speed_number = QtWidgets.QLCDNumber(self.widget)
        self.average_speed_number.setMinimumSize(QtCore.QSize(0, 40))
        self.average_speed_number.setMaximumSize(QtCore.QSize(16777215, 50))
        self.average_speed_number.setObjectName("average_speed_number")
        self.gridLayout_3.addWidget(self.average_speed_number, 5, 1, 1, 1)
        self.current_speed_number = QtWidgets.QLCDNumber(self.widget)
        self.current_speed_number.setMinimumSize(QtCore.QSize(0, 40))
        self.current_speed_number.setMaximumSize(QtCore.QSize(16777215, 50))
        self.current_speed_number.setObjectName("current_speed_number")
        self.gridLayout_3.addWidget(self.current_speed_number, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 7, 7, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 6, 7, 1)
        self.iconizing_method_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.iconizing_method_combo_box.setObjectName("iconizing_method_combo_box")
        self.gridLayout.addWidget(self.iconizing_method_combo_box, 3, 4, 1, 1)
        self.download_queue = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.download_queue.sizePolicy().hasHeightForWidth())
        self.download_queue.setSizePolicy(sizePolicy)
        self.download_queue.setMaximumSize(QtCore.QSize(433, 16777215))
        self.download_queue.setAlternatingRowColors(True)
        self.download_queue.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.download_queue.setObjectName("download_queue")
        self.gridLayout.addWidget(self.download_queue, 8, 7, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 2, 1, 1)
        self.search_term_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.search_term_edit.setObjectName("search_term_edit")
        self.gridLayout.addWidget(self.search_term_edit, 11, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.gridFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridFrame.sizePolicy().hasHeightForWidth())
        self.gridFrame.setSizePolicy(sizePolicy)
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 3, 0, 1, 1)
        self.add_to_queue_button = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_to_queue_button.sizePolicy().hasHeightForWidth())
        self.add_to_queue_button.setSizePolicy(sizePolicy)
        self.add_to_queue_button.setMaximumSize(QtCore.QSize(40, 16777215))
        self.add_to_queue_button.setObjectName("add_to_queue_button")
        self.gridLayout_4.addWidget(self.add_to_queue_button, 1, 0, 1, 1)
        self.remove_from_queue_button = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_from_queue_button.sizePolicy().hasHeightForWidth())
        self.remove_from_queue_button.setSizePolicy(sizePolicy)
        self.remove_from_queue_button.setMaximumSize(QtCore.QSize(40, 16777215))
        self.remove_from_queue_button.setObjectName("remove_from_queue_button")
        self.gridLayout_4.addWidget(self.remove_from_queue_button, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.gridFrame, 8, 5, 1, 1)
        self.search_result_list = QtWidgets.QTreeWidget(self.centralwidget)
        self.search_result_list.setMinimumSize(QtCore.QSize(512, 300))
        self.search_result_list.setAlternatingRowColors(True)
        self.search_result_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.search_result_list.setObjectName("search_result_list")
        self.gridLayout.addWidget(self.search_result_list, 8, 0, 3, 5)
        XDCCDownloadManagerWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(XDCCDownloadManagerWindow)
        self.statusbar.setObjectName("statusbar")
        XDCCDownloadManagerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(XDCCDownloadManagerWindow)
        QtCore.QMetaObject.connectSlotsByName(XDCCDownloadManagerWindow)

    def retranslateUi(self, XDCCDownloadManagerWindow):
        _translate = QtCore.QCoreApplication.translate
        XDCCDownloadManagerWindow.setWindowTitle(_translate("XDCCDownloadManagerWindow", "XDCC Download Manager"))
        self.move_up_button.setText(_translate("XDCCDownloadManagerWindow", "▲"))
        self.move_down_button.setText(_translate("XDCCDownloadManagerWindow", "▼"))
        self.label_3.setText(_translate("XDCCDownloadManagerWindow", "Season Number"))
        self.label_8.setText(_translate("XDCCDownloadManagerWindow", "Search Term"))
        self.download_button.setText(_translate("XDCCDownloadManagerWindow", "Download"))
        self.auto_rename_check.setText(_translate("XDCCDownloadManagerWindow", "Auto-Rename"))
        self.iconize_check.setText(_translate("XDCCDownloadManagerWindow", "Iconize"))
        self.label_7.setText(_translate("XDCCDownloadManagerWindow", "Starting Episode Number"))
        self.label.setText(_translate("XDCCDownloadManagerWindow", "Target Directory"))
        self.label_2.setText(_translate("XDCCDownloadManagerWindow", "Show Name"))
        self.directory_browse_button.setText(_translate("XDCCDownloadManagerWindow", "Browse"))
        self.search_button.setText(_translate("XDCCDownloadManagerWindow", "Search"))
        self.label_9.setText(_translate("XDCCDownloadManagerWindow", "Single Progress"))
        self.label_6.setText(_translate("XDCCDownloadManagerWindow", "Total Progress"))
        self.label_11.setText(_translate("XDCCDownloadManagerWindow", "Average Speed"))
        self.label_10.setText(_translate("XDCCDownloadManagerWindow", "Current Speed"))
        self.label_5.setText(_translate("XDCCDownloadManagerWindow", "Iconization Method"))
        self.label_4.setText(_translate("XDCCDownloadManagerWindow", "Renaming Scheme"))
        self.add_to_queue_button.setText(_translate("XDCCDownloadManagerWindow", "►"))
        self.remove_from_queue_button.setText(_translate("XDCCDownloadManagerWindow", "◄"))
        self.search_result_list.headerItem().setText(0, _translate("XDCCDownloadManagerWindow", "#"))
        self.search_result_list.headerItem().setText(1, _translate("XDCCDownloadManagerWindow", "Bot"))
        self.search_result_list.headerItem().setText(2, _translate("XDCCDownloadManagerWindow", "Pack"))
        self.search_result_list.headerItem().setText(3, _translate("XDCCDownloadManagerWindow", "Size"))
        self.search_result_list.headerItem().setText(4, _translate("XDCCDownloadManagerWindow", "Filename"))

