# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toktokkie/ui/qt/qt_designer/xdcc_update_configurator.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from __future__ import absolute_import
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_XDCCUpdateConfiguratorWindow(object):
    def setupUi(self, XDCCUpdateConfiguratorWindow):
        XDCCUpdateConfiguratorWindow.setObjectName(u"XDCCUpdateConfiguratorWindow")
        XDCCUpdateConfiguratorWindow.resize(639, 407)
        self.centralwidget = QtWidgets.QWidget(XDCCUpdateConfiguratorWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.naming_scheme_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.naming_scheme_combo_box.setObjectName(u"naming_scheme_combo_box")
        self.gridLayout.addWidget(self.naming_scheme_combo_box, 6, 4, 1, 2)
        self.bot_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.bot_edit.setObjectName(u"bot_edit")
        self.gridLayout.addWidget(self.bot_edit, 3, 4, 1, 2)
        self.new_button = QtWidgets.QPushButton(self.centralwidget)
        self.new_button.setObjectName(u"new_button")
        self.gridLayout.addWidget(self.new_button, 11, 1, 1, 1)
        self.quality_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.quality_combo_box.setObjectName(u"quality_combo_box")
        self.quality_combo_box.addItem(u"")
        self.quality_combo_box.addItem(u"")
        self.quality_combo_box.addItem(u"")
        self.gridLayout.addWidget(self.quality_combo_box, 2, 4, 1, 2)
        self.season_spin_box = QtWidgets.QSpinBox(self.centralwidget)
        self.season_spin_box.setObjectName(u"season_spin_box")
        self.gridLayout.addWidget(self.season_spin_box, 4, 4, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.gridLayout.addWidget(self.label_6, 5, 3, 1, 1)
        self.search_name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.search_name_edit.setObjectName(u"search_name_edit")
        self.gridLayout.addWidget(self.search_name_edit, 1, 4, 1, 2)
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setObjectName(u"save_button")
        self.gridLayout.addWidget(self.save_button, 12, 1, 1, 1)
        self.load_button = QtWidgets.QPushButton(self.centralwidget)
        self.load_button.setObjectName(u"load_button")
        self.gridLayout.addWidget(self.load_button, 12, 0, 1, 1)
        self.delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_button.setObjectName(u"delete_button")
        self.gridLayout.addWidget(self.delete_button, 11, 0, 1, 1)
        self.directory_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.directory_edit.setObjectName(u"directory_edit")
        self.gridLayout.addWidget(self.directory_edit, 0, 4, 1, 2)
        self.series_list = QtWidgets.QListWidget(self.centralwidget)
        self.series_list.setObjectName(u"series_list")
        self.gridLayout.addWidget(self.series_list, 0, 0, 11, 2)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.gridLayout.addWidget(self.label_7, 6, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.gridLayout.addWidget(self.label, 0, 3, 1, 1)
        self.search_engine_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.search_engine_combo_box.setObjectName(u"search_engine_combo_box")
        self.gridLayout.addWidget(self.search_engine_combo_box, 5, 4, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.gridLayout.addWidget(self.label_3, 2, 3, 1, 1)
        self.pattern_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.pattern_combo_box.setObjectName(u"pattern_combo_box")
        self.gridLayout.addWidget(self.pattern_combo_box, 7, 4, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.gridLayout.addWidget(self.label_4, 3, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.gridLayout.addWidget(self.label_5, 4, 3, 1, 1)
        self.confirm_button = QtWidgets.QPushButton(self.centralwidget)
        self.confirm_button.setObjectName(u"confirm_button")
        self.gridLayout.addWidget(self.confirm_button, 12, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.gridLayout.addWidget(self.label_8, 7, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 10, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.gridLayout.addWidget(self.label_9, 8, 3, 1, 1)
        self.episode_offset_spinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.episode_offset_spinbox.setObjectName(u"episode_offset_spinbox")
        self.gridLayout.addWidget(self.episode_offset_spinbox, 8, 4, 1, 2)
        XDCCUpdateConfiguratorWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(XDCCUpdateConfiguratorWindow)
        self.statusbar.setObjectName(u"statusbar")
        XDCCUpdateConfiguratorWindow.setStatusBar(self.statusbar)

        self.retranslateUi(XDCCUpdateConfiguratorWindow)
        QtCore.QMetaObject.connectSlotsByName(XDCCUpdateConfiguratorWindow)

    def retranslateUi(self, XDCCUpdateConfiguratorWindow):
        _translate = QtCore.QCoreApplication.translate
        XDCCUpdateConfiguratorWindow.setWindowTitle(_translate(u"XDCCUpdateConfiguratorWindow", u"XDCC Update Configurator"))
        self.new_button.setText(_translate(u"XDCCUpdateConfiguratorWindow", u"New"))
        self.quality_combo_box.setItemText(0, _translate(u"XDCCUpdateConfiguratorWindow", u"480p"))
        self.quality_combo_box.setItemText(1, _translate(u"XDCCUpdateConfiguratorWindow", u"720p"))
        self.quality_combo_box.setItemText(2, _translate(u"XDCCUpdateConfiguratorWindow", u"1080p"))
        self.label_6.setText(_translate(u"XDCCUpdateConfiguratorWindow", u"Search Engines"))
        self.save_button.setText(_translate(u"XDCCUpdateConfiguratorWindow", u"Save"))
        self.load_button.setText(_translate(u"XDCCUpdateConfiguratorWindow", u"Load"))
        self.delete_button.setText(_translate(u"XDCCUpdateConfiguratorWindow", u"Delete"))
        self.label_7.setText(_translate(u"XDCCUpdateConfiguratorWindow", u"Naming Scheme"))
        self.label.setText(_translate(u"XDCCUpdateConfiguratorWindow", u"Directory"))
        self.label_2.setText(_translate(u"XDCCUpdateConfiguratorWindow", u"Search Name"))
        self.label_3.setText(_translate(u"XDCCUpdateConfiguratorWindow", u"Quality"))
        self.label_4.setText(_translate(u"XDCCUpdateConfiguratorWindow", u"Bot"))
        self.label_5.setText(_translate(u"XDCCUpdateConfiguratorWindow", u"Season"))
        self.confirm_button.setText(_translate(u"XDCCUpdateConfiguratorWindow", u"Confirm Changes"))
        self.label_8.setText(_translate(u"XDCCUpdateConfiguratorWindow", u"Pattern"))
        self.label_9.setText(_translate(u"XDCCUpdateConfiguratorWindow", u"Episode Offset"))

