
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-18T17:42:58+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "3c0701d5e7b90618affec48d98b7ec8ae79240d8",
 "version": "1.0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
