
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "3dd64eec96cb35cb8031ddcc61a53a0fe540dc96",
 "version": "1907"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
