
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-28T13:23:45+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "40b9146ff1a67f0ae9a929de1cc3502053e6c51c",
 "version": "0.59"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
