
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-25T13:25:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b130697ca598079972536fee8af09d9432c9984",
 "version": "0.1.44"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
