
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-12-04T19:32:17+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "97364c7d72a41f1a583d4a28a6e4c3293f410777",
 "version": "0.2.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
