language: python
cache: pip

python:
  - 3.5
  - 3.6
  - 3.7-dev

env:
  - TOXENV=py

stages:
  - test
  - name: deploy
    if: tag IS present

install:
  - pip install tox codecov

script:
  - tox

after_script:
  - codecov

jobs:
  include:
    - env: TOXENV=flake8
      python: 3.6

    - stage: deploy
      script:
        - pip install wheel twine
        - python setup.py sdist bdist_wheel
        - twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
    - stage: deploy
      script:
        - pip install wheel
        - python setup.py sdist bdist_wheel
        - gem install dpl
        - dpl --api-key=$RELEASES_TOKEN --provider=releases --file=dist/* --file_glob=true
