---
- name: "Set os_res_type value"
  set_fact:
    os_res_type: "{{ res_def['type'] | default(res_def['res_type']) }}"
  when: async

- name: "Add resource type to async_types"
  set_fact:
    async_types: "{{ async_types + [os_res_type] }}"
  when: async

- name: "Get the resource name"
  set_fact:
    rsrc_name: "{{ res_def['res_name'] | default(res_def['name']) }}"

- name: "Create name using uhash value"
  set_fact:
    os_resource_name: "{{ rsrc_name + '-' + uhash + '-' }}"

- name: "provision/teardown resources of type {{ res_def['res_type'] | default(res_def['type']) }}"
  include: "provision_{{ res_def['res_type'] | default(res_def['type']) }}.yml"

