steps:
  - label: ":debian: Create Debian File"
    command: "buildkite-scripts/scripts/fpm.sh"
    env:
      DEB_NAME: virtru-devops-shudder
  
  - wait

  - label: ":debian: Upload Debian File"
    command: "buildkite-scripts/scripts/deb-s3.sh"
    env:
      APT_REPO_NAME: shared
      ENVIRONMENT_NAME: "0"
