---
# This playbook will initiate provisioning for the openstack resources groups.
- name: "DEBUG:: rackspace resource group list"
  debug:
    msg: "Currently Provisioning/Deprovisioning the resources under list rx_res_grps {{ rax_res_grps }}"

- name: "declaring output vars"
  set_fact:
    topology_outputs_rax_server: []
    topology_outputs_rax_object: []
    topology_outputs_rax_volume: []
    topology_outputs_rax_heat: []
    topology_outputs_rax_keypair: []

- name: "Initiating  Provisioning/Deprovioning of resources rackspace resource group"
  include: provision_resource_group.yml res_grp={{ item }} 
  with_items:
    - "{{ rax_res_grps }}"
  register: resource_grps_output
  when: state == "present"
