depends = ('ITKPyBase', 'ITKImageStatistics', 'ITKImageIntensity', )
templates = (
  ('HistogramThresholdCalculator', 'itk::HistogramThresholdCalculator', 'itkHistogramThresholdCalculatorHDSS', True, 'itk::Statistics::Histogram< double >, signed short'),
  ('HistogramThresholdCalculator', 'itk::HistogramThresholdCalculator', 'itkHistogramThresholdCalculatorHFSS', True, 'itk::Statistics::Histogram< float >, signed short'),
  ('HistogramThresholdCalculator', 'itk::HistogramThresholdCalculator', 'itkHistogramThresholdCalculatorHDUC', True, 'itk::Statistics::Histogram< double >, unsigned char'),
  ('HistogramThresholdCalculator', 'itk::HistogramThresholdCalculator', 'itkHistogramThresholdCalculatorHFUC', True, 'itk::Statistics::Histogram< float >, unsigned char'),
  ('HistogramThresholdCalculator', 'itk::HistogramThresholdCalculator', 'itkHistogramThresholdCalculatorHDF', True, 'itk::Statistics::Histogram< double >, float'),
  ('HistogramThresholdCalculator', 'itk::HistogramThresholdCalculator', 'itkHistogramThresholdCalculatorHFF', True, 'itk::Statistics::Histogram< float >, float'),
  ('HistogramThresholdImageFilter', 'itk::HistogramThresholdImageFilter', 'itkHistogramThresholdImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('HistogramThresholdImageFilter', 'itk::HistogramThresholdImageFilter', 'itkHistogramThresholdImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('HistogramThresholdImageFilter', 'itk::HistogramThresholdImageFilter', 'itkHistogramThresholdImageFilterISS2IUC2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned char,2 >'),
  ('HistogramThresholdImageFilter', 'itk::HistogramThresholdImageFilter', 'itkHistogramThresholdImageFilterISS3IUC3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned char,3 >'),
  ('HistogramThresholdImageFilter', 'itk::HistogramThresholdImageFilter', 'itkHistogramThresholdImageFilterIUC2ISS2', True, 'itk::Image< unsigned char,2 >, itk::Image< signed short,2 >'),
  ('HistogramThresholdImageFilter', 'itk::HistogramThresholdImageFilter', 'itkHistogramThresholdImageFilterIUC3ISS3', True, 'itk::Image< unsigned char,3 >, itk::Image< signed short,3 >'),
  ('HistogramThresholdImageFilter', 'itk::HistogramThresholdImageFilter', 'itkHistogramThresholdImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('HistogramThresholdImageFilter', 'itk::HistogramThresholdImageFilter', 'itkHistogramThresholdImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('HistogramThresholdImageFilter', 'itk::HistogramThresholdImageFilter', 'itkHistogramThresholdImageFilterIF2ISS2', True, 'itk::Image< float,2 >, itk::Image< signed short,2 >'),
  ('HistogramThresholdImageFilter', 'itk::HistogramThresholdImageFilter', 'itkHistogramThresholdImageFilterIF3ISS3', True, 'itk::Image< float,3 >, itk::Image< signed short,3 >'),
  ('HistogramThresholdImageFilter', 'itk::HistogramThresholdImageFilter', 'itkHistogramThresholdImageFilterIF2IUC2', True, 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('HistogramThresholdImageFilter', 'itk::HistogramThresholdImageFilter', 'itkHistogramThresholdImageFilterIF3IUC3', True, 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterISS2IUC2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned char,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterISS3IUC3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned char,3 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIF2IUC2', True, 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIF3IUC3', True, 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIF2ISS2', True, 'itk::Image< float,2 >, itk::Image< signed short,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIF3ISS3', True, 'itk::Image< float,3 >, itk::Image< signed short,3 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('BinaryThresholdProjectionImageFilter', 'itk::BinaryThresholdProjectionImageFilter', 'itkBinaryThresholdProjectionImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('BinaryThresholdProjectionImageFilter', 'itk::BinaryThresholdProjectionImageFilter', 'itkBinaryThresholdProjectionImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('BinaryThresholdProjectionImageFilter', 'itk::BinaryThresholdProjectionImageFilter', 'itkBinaryThresholdProjectionImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('BinaryThresholdProjectionImageFilter', 'itk::BinaryThresholdProjectionImageFilter', 'itkBinaryThresholdProjectionImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('BinaryThresholdProjectionImageFilter', 'itk::BinaryThresholdProjectionImageFilter', 'itkBinaryThresholdProjectionImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('BinaryThresholdProjectionImageFilter', 'itk::BinaryThresholdProjectionImageFilter', 'itkBinaryThresholdProjectionImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('BinaryThresholdProjectionImageFilter', 'itk::BinaryThresholdProjectionImageFilter', 'itkBinaryThresholdProjectionImageFilterISS3ISS2', True, 'itk::Image< signed short,3 >,itk::Image< signed short,2 >'),
  ('BinaryThresholdProjectionImageFilter', 'itk::BinaryThresholdProjectionImageFilter', 'itkBinaryThresholdProjectionImageFilterIUC3IUC2', True, 'itk::Image< unsigned char,3 >,itk::Image< unsigned char,2 >'),
  ('BinaryThresholdProjectionImageFilter', 'itk::BinaryThresholdProjectionImageFilter', 'itkBinaryThresholdProjectionImageFilterIF3IF2', True, 'itk::Image< float,3 >,itk::Image< float,2 >'),
  ('HuangThresholdCalculator', 'itk::HuangThresholdCalculator', 'itkHuangThresholdCalculatorHDSS', True, 'itk::Statistics::Histogram< double >, signed short'),
  ('HuangThresholdCalculator', 'itk::HuangThresholdCalculator', 'itkHuangThresholdCalculatorHFSS', True, 'itk::Statistics::Histogram< float >, signed short'),
  ('HuangThresholdCalculator', 'itk::HuangThresholdCalculator', 'itkHuangThresholdCalculatorHDUC', True, 'itk::Statistics::Histogram< double >, unsigned char'),
  ('HuangThresholdCalculator', 'itk::HuangThresholdCalculator', 'itkHuangThresholdCalculatorHFUC', True, 'itk::Statistics::Histogram< float >, unsigned char'),
  ('HuangThresholdCalculator', 'itk::HuangThresholdCalculator', 'itkHuangThresholdCalculatorHDF', True, 'itk::Statistics::Histogram< double >, float'),
  ('HuangThresholdCalculator', 'itk::HuangThresholdCalculator', 'itkHuangThresholdCalculatorHFF', True, 'itk::Statistics::Histogram< float >, float'),
  ('HuangThresholdImageFilter', 'itk::HuangThresholdImageFilter', 'itkHuangThresholdImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('HuangThresholdImageFilter', 'itk::HuangThresholdImageFilter', 'itkHuangThresholdImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('HuangThresholdImageFilter', 'itk::HuangThresholdImageFilter', 'itkHuangThresholdImageFilterISS2IUC2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned char,2 >'),
  ('HuangThresholdImageFilter', 'itk::HuangThresholdImageFilter', 'itkHuangThresholdImageFilterISS3IUC3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned char,3 >'),
  ('HuangThresholdImageFilter', 'itk::HuangThresholdImageFilter', 'itkHuangThresholdImageFilterIUC2ISS2', True, 'itk::Image< unsigned char,2 >, itk::Image< signed short,2 >'),
  ('HuangThresholdImageFilter', 'itk::HuangThresholdImageFilter', 'itkHuangThresholdImageFilterIUC3ISS3', True, 'itk::Image< unsigned char,3 >, itk::Image< signed short,3 >'),
  ('HuangThresholdImageFilter', 'itk::HuangThresholdImageFilter', 'itkHuangThresholdImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('HuangThresholdImageFilter', 'itk::HuangThresholdImageFilter', 'itkHuangThresholdImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('HuangThresholdImageFilter', 'itk::HuangThresholdImageFilter', 'itkHuangThresholdImageFilterIF2ISS2', True, 'itk::Image< float,2 >, itk::Image< signed short,2 >'),
  ('HuangThresholdImageFilter', 'itk::HuangThresholdImageFilter', 'itkHuangThresholdImageFilterIF3ISS3', True, 'itk::Image< float,3 >, itk::Image< signed short,3 >'),
  ('HuangThresholdImageFilter', 'itk::HuangThresholdImageFilter', 'itkHuangThresholdImageFilterIF2IUC2', True, 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('HuangThresholdImageFilter', 'itk::HuangThresholdImageFilter', 'itkHuangThresholdImageFilterIF3IUC3', True, 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
  ('IntermodesThresholdCalculator', 'itk::IntermodesThresholdCalculator', 'itkIntermodesThresholdCalculatorHDSS', True, 'itk::Statistics::Histogram< double >, signed short'),
  ('IntermodesThresholdCalculator', 'itk::IntermodesThresholdCalculator', 'itkIntermodesThresholdCalculatorHFSS', True, 'itk::Statistics::Histogram< float >, signed short'),
  ('IntermodesThresholdCalculator', 'itk::IntermodesThresholdCalculator', 'itkIntermodesThresholdCalculatorHDUC', True, 'itk::Statistics::Histogram< double >, unsigned char'),
  ('IntermodesThresholdCalculator', 'itk::IntermodesThresholdCalculator', 'itkIntermodesThresholdCalculatorHFUC', True, 'itk::Statistics::Histogram< float >, unsigned char'),
  ('IntermodesThresholdCalculator', 'itk::IntermodesThresholdCalculator', 'itkIntermodesThresholdCalculatorHDF', True, 'itk::Statistics::Histogram< double >, float'),
  ('IntermodesThresholdCalculator', 'itk::IntermodesThresholdCalculator', 'itkIntermodesThresholdCalculatorHFF', True, 'itk::Statistics::Histogram< float >, float'),
  ('IntermodesThresholdImageFilter', 'itk::IntermodesThresholdImageFilter', 'itkIntermodesThresholdImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('IntermodesThresholdImageFilter', 'itk::IntermodesThresholdImageFilter', 'itkIntermodesThresholdImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('IntermodesThresholdImageFilter', 'itk::IntermodesThresholdImageFilter', 'itkIntermodesThresholdImageFilterISS2IUC2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned char,2 >'),
  ('IntermodesThresholdImageFilter', 'itk::IntermodesThresholdImageFilter', 'itkIntermodesThresholdImageFilterISS3IUC3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned char,3 >'),
  ('IntermodesThresholdImageFilter', 'itk::IntermodesThresholdImageFilter', 'itkIntermodesThresholdImageFilterIUC2ISS2', True, 'itk::Image< unsigned char,2 >, itk::Image< signed short,2 >'),
  ('IntermodesThresholdImageFilter', 'itk::IntermodesThresholdImageFilter', 'itkIntermodesThresholdImageFilterIUC3ISS3', True, 'itk::Image< unsigned char,3 >, itk::Image< signed short,3 >'),
  ('IntermodesThresholdImageFilter', 'itk::IntermodesThresholdImageFilter', 'itkIntermodesThresholdImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('IntermodesThresholdImageFilter', 'itk::IntermodesThresholdImageFilter', 'itkIntermodesThresholdImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('IntermodesThresholdImageFilter', 'itk::IntermodesThresholdImageFilter', 'itkIntermodesThresholdImageFilterIF2ISS2', True, 'itk::Image< float,2 >, itk::Image< signed short,2 >'),
  ('IntermodesThresholdImageFilter', 'itk::IntermodesThresholdImageFilter', 'itkIntermodesThresholdImageFilterIF3ISS3', True, 'itk::Image< float,3 >, itk::Image< signed short,3 >'),
  ('IntermodesThresholdImageFilter', 'itk::IntermodesThresholdImageFilter', 'itkIntermodesThresholdImageFilterIF2IUC2', True, 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('IntermodesThresholdImageFilter', 'itk::IntermodesThresholdImageFilter', 'itkIntermodesThresholdImageFilterIF3IUC3', True, 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
  ('IsoDataThresholdCalculator', 'itk::IsoDataThresholdCalculator', 'itkIsoDataThresholdCalculatorHDSS', True, 'itk::Statistics::Histogram< double >, signed short'),
  ('IsoDataThresholdCalculator', 'itk::IsoDataThresholdCalculator', 'itkIsoDataThresholdCalculatorHFSS', True, 'itk::Statistics::Histogram< float >, signed short'),
  ('IsoDataThresholdCalculator', 'itk::IsoDataThresholdCalculator', 'itkIsoDataThresholdCalculatorHDUC', True, 'itk::Statistics::Histogram< double >, unsigned char'),
  ('IsoDataThresholdCalculator', 'itk::IsoDataThresholdCalculator', 'itkIsoDataThresholdCalculatorHFUC', True, 'itk::Statistics::Histogram< float >, unsigned char'),
  ('IsoDataThresholdCalculator', 'itk::IsoDataThresholdCalculator', 'itkIsoDataThresholdCalculatorHDF', True, 'itk::Statistics::Histogram< double >, float'),
  ('IsoDataThresholdCalculator', 'itk::IsoDataThresholdCalculator', 'itkIsoDataThresholdCalculatorHFF', True, 'itk::Statistics::Histogram< float >, float'),
  ('IsoDataThresholdImageFilter', 'itk::IsoDataThresholdImageFilter', 'itkIsoDataThresholdImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('IsoDataThresholdImageFilter', 'itk::IsoDataThresholdImageFilter', 'itkIsoDataThresholdImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('IsoDataThresholdImageFilter', 'itk::IsoDataThresholdImageFilter', 'itkIsoDataThresholdImageFilterISS2IUC2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned char,2 >'),
  ('IsoDataThresholdImageFilter', 'itk::IsoDataThresholdImageFilter', 'itkIsoDataThresholdImageFilterISS3IUC3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned char,3 >'),
  ('IsoDataThresholdImageFilter', 'itk::IsoDataThresholdImageFilter', 'itkIsoDataThresholdImageFilterIUC2ISS2', True, 'itk::Image< unsigned char,2 >, itk::Image< signed short,2 >'),
  ('IsoDataThresholdImageFilter', 'itk::IsoDataThresholdImageFilter', 'itkIsoDataThresholdImageFilterIUC3ISS3', True, 'itk::Image< unsigned char,3 >, itk::Image< signed short,3 >'),
  ('IsoDataThresholdImageFilter', 'itk::IsoDataThresholdImageFilter', 'itkIsoDataThresholdImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('IsoDataThresholdImageFilter', 'itk::IsoDataThresholdImageFilter', 'itkIsoDataThresholdImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('IsoDataThresholdImageFilter', 'itk::IsoDataThresholdImageFilter', 'itkIsoDataThresholdImageFilterIF2ISS2', True, 'itk::Image< float,2 >, itk::Image< signed short,2 >'),
  ('IsoDataThresholdImageFilter', 'itk::IsoDataThresholdImageFilter', 'itkIsoDataThresholdImageFilterIF3ISS3', True, 'itk::Image< float,3 >, itk::Image< signed short,3 >'),
  ('IsoDataThresholdImageFilter', 'itk::IsoDataThresholdImageFilter', 'itkIsoDataThresholdImageFilterIF2IUC2', True, 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('IsoDataThresholdImageFilter', 'itk::IsoDataThresholdImageFilter', 'itkIsoDataThresholdImageFilterIF3IUC3', True, 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
  ('KappaSigmaThresholdImageFilter', 'itk::KappaSigmaThresholdImageFilter', 'itkKappaSigmaThresholdImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('KappaSigmaThresholdImageFilter', 'itk::KappaSigmaThresholdImageFilter', 'itkKappaSigmaThresholdImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('KappaSigmaThresholdImageFilter', 'itk::KappaSigmaThresholdImageFilter', 'itkKappaSigmaThresholdImageFilterISS2IUC2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned char,2 >'),
  ('KappaSigmaThresholdImageFilter', 'itk::KappaSigmaThresholdImageFilter', 'itkKappaSigmaThresholdImageFilterISS3IUC3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned char,3 >'),
  ('KappaSigmaThresholdImageFilter', 'itk::KappaSigmaThresholdImageFilter', 'itkKappaSigmaThresholdImageFilterIUC2ISS2', True, 'itk::Image< unsigned char,2 >, itk::Image< signed short,2 >'),
  ('KappaSigmaThresholdImageFilter', 'itk::KappaSigmaThresholdImageFilter', 'itkKappaSigmaThresholdImageFilterIUC3ISS3', True, 'itk::Image< unsigned char,3 >, itk::Image< signed short,3 >'),
  ('KappaSigmaThresholdImageFilter', 'itk::KappaSigmaThresholdImageFilter', 'itkKappaSigmaThresholdImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('KappaSigmaThresholdImageFilter', 'itk::KappaSigmaThresholdImageFilter', 'itkKappaSigmaThresholdImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('KappaSigmaThresholdImageFilter', 'itk::KappaSigmaThresholdImageFilter', 'itkKappaSigmaThresholdImageFilterIF2ISS2', True, 'itk::Image< float,2 >, itk::Image< signed short,2 >'),
  ('KappaSigmaThresholdImageFilter', 'itk::KappaSigmaThresholdImageFilter', 'itkKappaSigmaThresholdImageFilterIF3ISS3', True, 'itk::Image< float,3 >, itk::Image< signed short,3 >'),
  ('KappaSigmaThresholdImageFilter', 'itk::KappaSigmaThresholdImageFilter', 'itkKappaSigmaThresholdImageFilterIF2IUC2', True, 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('KappaSigmaThresholdImageFilter', 'itk::KappaSigmaThresholdImageFilter', 'itkKappaSigmaThresholdImageFilterIF3IUC3', True, 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
  ('KittlerIllingworthThresholdCalculator', 'itk::KittlerIllingworthThresholdCalculator', 'itkKittlerIllingworthThresholdCalculatorHDSS', True, 'itk::Statistics::Histogram< double >, signed short'),
  ('KittlerIllingworthThresholdCalculator', 'itk::KittlerIllingworthThresholdCalculator', 'itkKittlerIllingworthThresholdCalculatorHFSS', True, 'itk::Statistics::Histogram< float >, signed short'),
  ('KittlerIllingworthThresholdCalculator', 'itk::KittlerIllingworthThresholdCalculator', 'itkKittlerIllingworthThresholdCalculatorHDUC', True, 'itk::Statistics::Histogram< double >, unsigned char'),
  ('KittlerIllingworthThresholdCalculator', 'itk::KittlerIllingworthThresholdCalculator', 'itkKittlerIllingworthThresholdCalculatorHFUC', True, 'itk::Statistics::Histogram< float >, unsigned char'),
  ('KittlerIllingworthThresholdCalculator', 'itk::KittlerIllingworthThresholdCalculator', 'itkKittlerIllingworthThresholdCalculatorHDF', True, 'itk::Statistics::Histogram< double >, float'),
  ('KittlerIllingworthThresholdCalculator', 'itk::KittlerIllingworthThresholdCalculator', 'itkKittlerIllingworthThresholdCalculatorHFF', True, 'itk::Statistics::Histogram< float >, float'),
  ('KittlerIllingworthThresholdImageFilter', 'itk::KittlerIllingworthThresholdImageFilter', 'itkKittlerIllingworthThresholdImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('KittlerIllingworthThresholdImageFilter', 'itk::KittlerIllingworthThresholdImageFilter', 'itkKittlerIllingworthThresholdImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('KittlerIllingworthThresholdImageFilter', 'itk::KittlerIllingworthThresholdImageFilter', 'itkKittlerIllingworthThresholdImageFilterISS2IUC2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned char,2 >'),
  ('KittlerIllingworthThresholdImageFilter', 'itk::KittlerIllingworthThresholdImageFilter', 'itkKittlerIllingworthThresholdImageFilterISS3IUC3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned char,3 >'),
  ('KittlerIllingworthThresholdImageFilter', 'itk::KittlerIllingworthThresholdImageFilter', 'itkKittlerIllingworthThresholdImageFilterIUC2ISS2', True, 'itk::Image< unsigned char,2 >, itk::Image< signed short,2 >'),
  ('KittlerIllingworthThresholdImageFilter', 'itk::KittlerIllingworthThresholdImageFilter', 'itkKittlerIllingworthThresholdImageFilterIUC3ISS3', True, 'itk::Image< unsigned char,3 >, itk::Image< signed short,3 >'),
  ('KittlerIllingworthThresholdImageFilter', 'itk::KittlerIllingworthThresholdImageFilter', 'itkKittlerIllingworthThresholdImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('KittlerIllingworthThresholdImageFilter', 'itk::KittlerIllingworthThresholdImageFilter', 'itkKittlerIllingworthThresholdImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('KittlerIllingworthThresholdImageFilter', 'itk::KittlerIllingworthThresholdImageFilter', 'itkKittlerIllingworthThresholdImageFilterIF2ISS2', True, 'itk::Image< float,2 >, itk::Image< signed short,2 >'),
  ('KittlerIllingworthThresholdImageFilter', 'itk::KittlerIllingworthThresholdImageFilter', 'itkKittlerIllingworthThresholdImageFilterIF3ISS3', True, 'itk::Image< float,3 >, itk::Image< signed short,3 >'),
  ('KittlerIllingworthThresholdImageFilter', 'itk::KittlerIllingworthThresholdImageFilter', 'itkKittlerIllingworthThresholdImageFilterIF2IUC2', True, 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('KittlerIllingworthThresholdImageFilter', 'itk::KittlerIllingworthThresholdImageFilter', 'itkKittlerIllingworthThresholdImageFilterIF3IUC3', True, 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
  ('LiThresholdCalculator', 'itk::LiThresholdCalculator', 'itkLiThresholdCalculatorHDSS', True, 'itk::Statistics::Histogram< double >, signed short'),
  ('LiThresholdCalculator', 'itk::LiThresholdCalculator', 'itkLiThresholdCalculatorHFSS', True, 'itk::Statistics::Histogram< float >, signed short'),
  ('LiThresholdCalculator', 'itk::LiThresholdCalculator', 'itkLiThresholdCalculatorHDUC', True, 'itk::Statistics::Histogram< double >, unsigned char'),
  ('LiThresholdCalculator', 'itk::LiThresholdCalculator', 'itkLiThresholdCalculatorHFUC', True, 'itk::Statistics::Histogram< float >, unsigned char'),
  ('LiThresholdCalculator', 'itk::LiThresholdCalculator', 'itkLiThresholdCalculatorHDF', True, 'itk::Statistics::Histogram< double >, float'),
  ('LiThresholdCalculator', 'itk::LiThresholdCalculator', 'itkLiThresholdCalculatorHFF', True, 'itk::Statistics::Histogram< float >, float'),
  ('LiThresholdImageFilter', 'itk::LiThresholdImageFilter', 'itkLiThresholdImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('LiThresholdImageFilter', 'itk::LiThresholdImageFilter', 'itkLiThresholdImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('LiThresholdImageFilter', 'itk::LiThresholdImageFilter', 'itkLiThresholdImageFilterISS2IUC2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned char,2 >'),
  ('LiThresholdImageFilter', 'itk::LiThresholdImageFilter', 'itkLiThresholdImageFilterISS3IUC3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned char,3 >'),
  ('LiThresholdImageFilter', 'itk::LiThresholdImageFilter', 'itkLiThresholdImageFilterIUC2ISS2', True, 'itk::Image< unsigned char,2 >, itk::Image< signed short,2 >'),
  ('LiThresholdImageFilter', 'itk::LiThresholdImageFilter', 'itkLiThresholdImageFilterIUC3ISS3', True, 'itk::Image< unsigned char,3 >, itk::Image< signed short,3 >'),
  ('LiThresholdImageFilter', 'itk::LiThresholdImageFilter', 'itkLiThresholdImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('LiThresholdImageFilter', 'itk::LiThresholdImageFilter', 'itkLiThresholdImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('LiThresholdImageFilter', 'itk::LiThresholdImageFilter', 'itkLiThresholdImageFilterIF2ISS2', True, 'itk::Image< float,2 >, itk::Image< signed short,2 >'),
  ('LiThresholdImageFilter', 'itk::LiThresholdImageFilter', 'itkLiThresholdImageFilterIF3ISS3', True, 'itk::Image< float,3 >, itk::Image< signed short,3 >'),
  ('LiThresholdImageFilter', 'itk::LiThresholdImageFilter', 'itkLiThresholdImageFilterIF2IUC2', True, 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('LiThresholdImageFilter', 'itk::LiThresholdImageFilter', 'itkLiThresholdImageFilterIF3IUC3', True, 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
  ('MaximumEntropyThresholdCalculator', 'itk::MaximumEntropyThresholdCalculator', 'itkMaximumEntropyThresholdCalculatorHDSS', True, 'itk::Statistics::Histogram< double >, signed short'),
  ('MaximumEntropyThresholdCalculator', 'itk::MaximumEntropyThresholdCalculator', 'itkMaximumEntropyThresholdCalculatorHFSS', True, 'itk::Statistics::Histogram< float >, signed short'),
  ('MaximumEntropyThresholdCalculator', 'itk::MaximumEntropyThresholdCalculator', 'itkMaximumEntropyThresholdCalculatorHDUC', True, 'itk::Statistics::Histogram< double >, unsigned char'),
  ('MaximumEntropyThresholdCalculator', 'itk::MaximumEntropyThresholdCalculator', 'itkMaximumEntropyThresholdCalculatorHFUC', True, 'itk::Statistics::Histogram< float >, unsigned char'),
  ('MaximumEntropyThresholdCalculator', 'itk::MaximumEntropyThresholdCalculator', 'itkMaximumEntropyThresholdCalculatorHDF', True, 'itk::Statistics::Histogram< double >, float'),
  ('MaximumEntropyThresholdCalculator', 'itk::MaximumEntropyThresholdCalculator', 'itkMaximumEntropyThresholdCalculatorHFF', True, 'itk::Statistics::Histogram< float >, float'),
  ('MaximumEntropyThresholdImageFilter', 'itk::MaximumEntropyThresholdImageFilter', 'itkMaximumEntropyThresholdImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('MaximumEntropyThresholdImageFilter', 'itk::MaximumEntropyThresholdImageFilter', 'itkMaximumEntropyThresholdImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('MaximumEntropyThresholdImageFilter', 'itk::MaximumEntropyThresholdImageFilter', 'itkMaximumEntropyThresholdImageFilterISS2IUC2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned char,2 >'),
  ('MaximumEntropyThresholdImageFilter', 'itk::MaximumEntropyThresholdImageFilter', 'itkMaximumEntropyThresholdImageFilterISS3IUC3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned char,3 >'),
  ('MaximumEntropyThresholdImageFilter', 'itk::MaximumEntropyThresholdImageFilter', 'itkMaximumEntropyThresholdImageFilterIUC2ISS2', True, 'itk::Image< unsigned char,2 >, itk::Image< signed short,2 >'),
  ('MaximumEntropyThresholdImageFilter', 'itk::MaximumEntropyThresholdImageFilter', 'itkMaximumEntropyThresholdImageFilterIUC3ISS3', True, 'itk::Image< unsigned char,3 >, itk::Image< signed short,3 >'),
  ('MaximumEntropyThresholdImageFilter', 'itk::MaximumEntropyThresholdImageFilter', 'itkMaximumEntropyThresholdImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('MaximumEntropyThresholdImageFilter', 'itk::MaximumEntropyThresholdImageFilter', 'itkMaximumEntropyThresholdImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('MaximumEntropyThresholdImageFilter', 'itk::MaximumEntropyThresholdImageFilter', 'itkMaximumEntropyThresholdImageFilterIF2ISS2', True, 'itk::Image< float,2 >, itk::Image< signed short,2 >'),
  ('MaximumEntropyThresholdImageFilter', 'itk::MaximumEntropyThresholdImageFilter', 'itkMaximumEntropyThresholdImageFilterIF3ISS3', True, 'itk::Image< float,3 >, itk::Image< signed short,3 >'),
  ('MaximumEntropyThresholdImageFilter', 'itk::MaximumEntropyThresholdImageFilter', 'itkMaximumEntropyThresholdImageFilterIF2IUC2', True, 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('MaximumEntropyThresholdImageFilter', 'itk::MaximumEntropyThresholdImageFilter', 'itkMaximumEntropyThresholdImageFilterIF3IUC3', True, 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
  ('MomentsThresholdCalculator', 'itk::MomentsThresholdCalculator', 'itkMomentsThresholdCalculatorHDSS', True, 'itk::Statistics::Histogram< double >, signed short'),
  ('MomentsThresholdCalculator', 'itk::MomentsThresholdCalculator', 'itkMomentsThresholdCalculatorHFSS', True, 'itk::Statistics::Histogram< float >, signed short'),
  ('MomentsThresholdCalculator', 'itk::MomentsThresholdCalculator', 'itkMomentsThresholdCalculatorHDUC', True, 'itk::Statistics::Histogram< double >, unsigned char'),
  ('MomentsThresholdCalculator', 'itk::MomentsThresholdCalculator', 'itkMomentsThresholdCalculatorHFUC', True, 'itk::Statistics::Histogram< float >, unsigned char'),
  ('MomentsThresholdCalculator', 'itk::MomentsThresholdCalculator', 'itkMomentsThresholdCalculatorHDF', True, 'itk::Statistics::Histogram< double >, float'),
  ('MomentsThresholdCalculator', 'itk::MomentsThresholdCalculator', 'itkMomentsThresholdCalculatorHFF', True, 'itk::Statistics::Histogram< float >, float'),
  ('MomentsThresholdImageFilter', 'itk::MomentsThresholdImageFilter', 'itkMomentsThresholdImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('MomentsThresholdImageFilter', 'itk::MomentsThresholdImageFilter', 'itkMomentsThresholdImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('MomentsThresholdImageFilter', 'itk::MomentsThresholdImageFilter', 'itkMomentsThresholdImageFilterISS2IUC2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned char,2 >'),
  ('MomentsThresholdImageFilter', 'itk::MomentsThresholdImageFilter', 'itkMomentsThresholdImageFilterISS3IUC3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned char,3 >'),
  ('MomentsThresholdImageFilter', 'itk::MomentsThresholdImageFilter', 'itkMomentsThresholdImageFilterIUC2ISS2', True, 'itk::Image< unsigned char,2 >, itk::Image< signed short,2 >'),
  ('MomentsThresholdImageFilter', 'itk::MomentsThresholdImageFilter', 'itkMomentsThresholdImageFilterIUC3ISS3', True, 'itk::Image< unsigned char,3 >, itk::Image< signed short,3 >'),
  ('MomentsThresholdImageFilter', 'itk::MomentsThresholdImageFilter', 'itkMomentsThresholdImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('MomentsThresholdImageFilter', 'itk::MomentsThresholdImageFilter', 'itkMomentsThresholdImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('MomentsThresholdImageFilter', 'itk::MomentsThresholdImageFilter', 'itkMomentsThresholdImageFilterIF2ISS2', True, 'itk::Image< float,2 >, itk::Image< signed short,2 >'),
  ('MomentsThresholdImageFilter', 'itk::MomentsThresholdImageFilter', 'itkMomentsThresholdImageFilterIF3ISS3', True, 'itk::Image< float,3 >, itk::Image< signed short,3 >'),
  ('MomentsThresholdImageFilter', 'itk::MomentsThresholdImageFilter', 'itkMomentsThresholdImageFilterIF2IUC2', True, 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('MomentsThresholdImageFilter', 'itk::MomentsThresholdImageFilter', 'itkMomentsThresholdImageFilterIF3IUC3', True, 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
  ('OtsuMultipleThresholdsImageFilter', 'itk::OtsuMultipleThresholdsImageFilter', 'itkOtsuMultipleThresholdsImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('OtsuMultipleThresholdsImageFilter', 'itk::OtsuMultipleThresholdsImageFilter', 'itkOtsuMultipleThresholdsImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('OtsuMultipleThresholdsImageFilter', 'itk::OtsuMultipleThresholdsImageFilter', 'itkOtsuMultipleThresholdsImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('OtsuMultipleThresholdsImageFilter', 'itk::OtsuMultipleThresholdsImageFilter', 'itkOtsuMultipleThresholdsImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('OtsuMultipleThresholdsImageFilter', 'itk::OtsuMultipleThresholdsImageFilter', 'itkOtsuMultipleThresholdsImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('OtsuMultipleThresholdsImageFilter', 'itk::OtsuMultipleThresholdsImageFilter', 'itkOtsuMultipleThresholdsImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('OtsuThresholdCalculator', 'itk::OtsuThresholdCalculator', 'itkOtsuThresholdCalculatorHDSS', True, 'itk::Statistics::Histogram< double >, signed short'),
  ('OtsuThresholdCalculator', 'itk::OtsuThresholdCalculator', 'itkOtsuThresholdCalculatorHFSS', True, 'itk::Statistics::Histogram< float >, signed short'),
  ('OtsuThresholdCalculator', 'itk::OtsuThresholdCalculator', 'itkOtsuThresholdCalculatorHDUC', True, 'itk::Statistics::Histogram< double >, unsigned char'),
  ('OtsuThresholdCalculator', 'itk::OtsuThresholdCalculator', 'itkOtsuThresholdCalculatorHFUC', True, 'itk::Statistics::Histogram< float >, unsigned char'),
  ('OtsuThresholdCalculator', 'itk::OtsuThresholdCalculator', 'itkOtsuThresholdCalculatorHDF', True, 'itk::Statistics::Histogram< double >, float'),
  ('OtsuThresholdCalculator', 'itk::OtsuThresholdCalculator', 'itkOtsuThresholdCalculatorHFF', True, 'itk::Statistics::Histogram< float >, float'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterISS2IUC2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned char,2 >'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterISS3IUC3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned char,3 >'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterIUC2ISS2', True, 'itk::Image< unsigned char,2 >, itk::Image< signed short,2 >'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterIUC3ISS3', True, 'itk::Image< unsigned char,3 >, itk::Image< signed short,3 >'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterIF2ISS2', True, 'itk::Image< float,2 >, itk::Image< signed short,2 >'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterIF3ISS3', True, 'itk::Image< float,3 >, itk::Image< signed short,3 >'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterIF2IUC2', True, 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterIF3IUC3', True, 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
  ('RenyiEntropyThresholdCalculator', 'itk::RenyiEntropyThresholdCalculator', 'itkRenyiEntropyThresholdCalculatorHDSS', True, 'itk::Statistics::Histogram< double >, signed short'),
  ('RenyiEntropyThresholdCalculator', 'itk::RenyiEntropyThresholdCalculator', 'itkRenyiEntropyThresholdCalculatorHFSS', True, 'itk::Statistics::Histogram< float >, signed short'),
  ('RenyiEntropyThresholdCalculator', 'itk::RenyiEntropyThresholdCalculator', 'itkRenyiEntropyThresholdCalculatorHDUC', True, 'itk::Statistics::Histogram< double >, unsigned char'),
  ('RenyiEntropyThresholdCalculator', 'itk::RenyiEntropyThresholdCalculator', 'itkRenyiEntropyThresholdCalculatorHFUC', True, 'itk::Statistics::Histogram< float >, unsigned char'),
  ('RenyiEntropyThresholdCalculator', 'itk::RenyiEntropyThresholdCalculator', 'itkRenyiEntropyThresholdCalculatorHDF', True, 'itk::Statistics::Histogram< double >, float'),
  ('RenyiEntropyThresholdCalculator', 'itk::RenyiEntropyThresholdCalculator', 'itkRenyiEntropyThresholdCalculatorHFF', True, 'itk::Statistics::Histogram< float >, float'),
  ('RenyiEntropyThresholdImageFilter', 'itk::RenyiEntropyThresholdImageFilter', 'itkRenyiEntropyThresholdImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('RenyiEntropyThresholdImageFilter', 'itk::RenyiEntropyThresholdImageFilter', 'itkRenyiEntropyThresholdImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('RenyiEntropyThresholdImageFilter', 'itk::RenyiEntropyThresholdImageFilter', 'itkRenyiEntropyThresholdImageFilterISS2IUC2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned char,2 >'),
  ('RenyiEntropyThresholdImageFilter', 'itk::RenyiEntropyThresholdImageFilter', 'itkRenyiEntropyThresholdImageFilterISS3IUC3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned char,3 >'),
  ('RenyiEntropyThresholdImageFilter', 'itk::RenyiEntropyThresholdImageFilter', 'itkRenyiEntropyThresholdImageFilterIUC2ISS2', True, 'itk::Image< unsigned char,2 >, itk::Image< signed short,2 >'),
  ('RenyiEntropyThresholdImageFilter', 'itk::RenyiEntropyThresholdImageFilter', 'itkRenyiEntropyThresholdImageFilterIUC3ISS3', True, 'itk::Image< unsigned char,3 >, itk::Image< signed short,3 >'),
  ('RenyiEntropyThresholdImageFilter', 'itk::RenyiEntropyThresholdImageFilter', 'itkRenyiEntropyThresholdImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('RenyiEntropyThresholdImageFilter', 'itk::RenyiEntropyThresholdImageFilter', 'itkRenyiEntropyThresholdImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('RenyiEntropyThresholdImageFilter', 'itk::RenyiEntropyThresholdImageFilter', 'itkRenyiEntropyThresholdImageFilterIF2ISS2', True, 'itk::Image< float,2 >, itk::Image< signed short,2 >'),
  ('RenyiEntropyThresholdImageFilter', 'itk::RenyiEntropyThresholdImageFilter', 'itkRenyiEntropyThresholdImageFilterIF3ISS3', True, 'itk::Image< float,3 >, itk::Image< signed short,3 >'),
  ('RenyiEntropyThresholdImageFilter', 'itk::RenyiEntropyThresholdImageFilter', 'itkRenyiEntropyThresholdImageFilterIF2IUC2', True, 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('RenyiEntropyThresholdImageFilter', 'itk::RenyiEntropyThresholdImageFilter', 'itkRenyiEntropyThresholdImageFilterIF3IUC3', True, 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
  ('ShanbhagThresholdCalculator', 'itk::ShanbhagThresholdCalculator', 'itkShanbhagThresholdCalculatorHDSS', True, 'itk::Statistics::Histogram< double >, signed short'),
  ('ShanbhagThresholdCalculator', 'itk::ShanbhagThresholdCalculator', 'itkShanbhagThresholdCalculatorHFSS', True, 'itk::Statistics::Histogram< float >, signed short'),
  ('ShanbhagThresholdCalculator', 'itk::ShanbhagThresholdCalculator', 'itkShanbhagThresholdCalculatorHDUC', True, 'itk::Statistics::Histogram< double >, unsigned char'),
  ('ShanbhagThresholdCalculator', 'itk::ShanbhagThresholdCalculator', 'itkShanbhagThresholdCalculatorHFUC', True, 'itk::Statistics::Histogram< float >, unsigned char'),
  ('ShanbhagThresholdCalculator', 'itk::ShanbhagThresholdCalculator', 'itkShanbhagThresholdCalculatorHDF', True, 'itk::Statistics::Histogram< double >, float'),
  ('ShanbhagThresholdCalculator', 'itk::ShanbhagThresholdCalculator', 'itkShanbhagThresholdCalculatorHFF', True, 'itk::Statistics::Histogram< float >, float'),
  ('ShanbhagThresholdImageFilter', 'itk::ShanbhagThresholdImageFilter', 'itkShanbhagThresholdImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('ShanbhagThresholdImageFilter', 'itk::ShanbhagThresholdImageFilter', 'itkShanbhagThresholdImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('ShanbhagThresholdImageFilter', 'itk::ShanbhagThresholdImageFilter', 'itkShanbhagThresholdImageFilterISS2IUC2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned char,2 >'),
  ('ShanbhagThresholdImageFilter', 'itk::ShanbhagThresholdImageFilter', 'itkShanbhagThresholdImageFilterISS3IUC3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned char,3 >'),
  ('ShanbhagThresholdImageFilter', 'itk::ShanbhagThresholdImageFilter', 'itkShanbhagThresholdImageFilterIUC2ISS2', True, 'itk::Image< unsigned char,2 >, itk::Image< signed short,2 >'),
  ('ShanbhagThresholdImageFilter', 'itk::ShanbhagThresholdImageFilter', 'itkShanbhagThresholdImageFilterIUC3ISS3', True, 'itk::Image< unsigned char,3 >, itk::Image< signed short,3 >'),
  ('ShanbhagThresholdImageFilter', 'itk::ShanbhagThresholdImageFilter', 'itkShanbhagThresholdImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('ShanbhagThresholdImageFilter', 'itk::ShanbhagThresholdImageFilter', 'itkShanbhagThresholdImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('ShanbhagThresholdImageFilter', 'itk::ShanbhagThresholdImageFilter', 'itkShanbhagThresholdImageFilterIF2ISS2', True, 'itk::Image< float,2 >, itk::Image< signed short,2 >'),
  ('ShanbhagThresholdImageFilter', 'itk::ShanbhagThresholdImageFilter', 'itkShanbhagThresholdImageFilterIF3ISS3', True, 'itk::Image< float,3 >, itk::Image< signed short,3 >'),
  ('ShanbhagThresholdImageFilter', 'itk::ShanbhagThresholdImageFilter', 'itkShanbhagThresholdImageFilterIF2IUC2', True, 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('ShanbhagThresholdImageFilter', 'itk::ShanbhagThresholdImageFilter', 'itkShanbhagThresholdImageFilterIF3IUC3', True, 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
  ('ThresholdImageFilter', 'itk::ThresholdImageFilter', 'itkThresholdImageFilterISS2', True, 'itk::Image< signed short,2 >'),
  ('ThresholdImageFilter', 'itk::ThresholdImageFilter', 'itkThresholdImageFilterISS3', True, 'itk::Image< signed short,3 >'),
  ('ThresholdImageFilter', 'itk::ThresholdImageFilter', 'itkThresholdImageFilterIUC2', True, 'itk::Image< unsigned char,2 >'),
  ('ThresholdImageFilter', 'itk::ThresholdImageFilter', 'itkThresholdImageFilterIUC3', True, 'itk::Image< unsigned char,3 >'),
  ('ThresholdImageFilter', 'itk::ThresholdImageFilter', 'itkThresholdImageFilterIF2', True, 'itk::Image< float,2 >'),
  ('ThresholdImageFilter', 'itk::ThresholdImageFilter', 'itkThresholdImageFilterIF3', True, 'itk::Image< float,3 >'),
  ('ThresholdLabelerImageFilter', 'itk::ThresholdLabelerImageFilter', 'itkThresholdLabelerImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('ThresholdLabelerImageFilter', 'itk::ThresholdLabelerImageFilter', 'itkThresholdLabelerImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('ThresholdLabelerImageFilter', 'itk::ThresholdLabelerImageFilter', 'itkThresholdLabelerImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('ThresholdLabelerImageFilter', 'itk::ThresholdLabelerImageFilter', 'itkThresholdLabelerImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('ThresholdLabelerImageFilter', 'itk::ThresholdLabelerImageFilter', 'itkThresholdLabelerImageFilterIF2IF2', True, 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('ThresholdLabelerImageFilter', 'itk::ThresholdLabelerImageFilter', 'itkThresholdLabelerImageFilterIF3IF3', True, 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('TriangleThresholdCalculator', 'itk::TriangleThresholdCalculator', 'itkTriangleThresholdCalculatorHDSS', True, 'itk::Statistics::Histogram< double >, signed short'),
  ('TriangleThresholdCalculator', 'itk::TriangleThresholdCalculator', 'itkTriangleThresholdCalculatorHFSS', True, 'itk::Statistics::Histogram< float >, signed short'),
  ('TriangleThresholdCalculator', 'itk::TriangleThresholdCalculator', 'itkTriangleThresholdCalculatorHDUC', True, 'itk::Statistics::Histogram< double >, unsigned char'),
  ('TriangleThresholdCalculator', 'itk::TriangleThresholdCalculator', 'itkTriangleThresholdCalculatorHFUC', True, 'itk::Statistics::Histogram< float >, unsigned char'),
  ('TriangleThresholdCalculator', 'itk::TriangleThresholdCalculator', 'itkTriangleThresholdCalculatorHDF', True, 'itk::Statistics::Histogram< double >, float'),
  ('TriangleThresholdCalculator', 'itk::TriangleThresholdCalculator', 'itkTriangleThresholdCalculatorHFF', True, 'itk::Statistics::Histogram< float >, float'),
  ('TriangleThresholdImageFilter', 'itk::TriangleThresholdImageFilter', 'itkTriangleThresholdImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('TriangleThresholdImageFilter', 'itk::TriangleThresholdImageFilter', 'itkTriangleThresholdImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('TriangleThresholdImageFilter', 'itk::TriangleThresholdImageFilter', 'itkTriangleThresholdImageFilterISS2IUC2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned char,2 >'),
  ('TriangleThresholdImageFilter', 'itk::TriangleThresholdImageFilter', 'itkTriangleThresholdImageFilterISS3IUC3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned char,3 >'),
  ('TriangleThresholdImageFilter', 'itk::TriangleThresholdImageFilter', 'itkTriangleThresholdImageFilterIUC2ISS2', True, 'itk::Image< unsigned char,2 >, itk::Image< signed short,2 >'),
  ('TriangleThresholdImageFilter', 'itk::TriangleThresholdImageFilter', 'itkTriangleThresholdImageFilterIUC3ISS3', True, 'itk::Image< unsigned char,3 >, itk::Image< signed short,3 >'),
  ('TriangleThresholdImageFilter', 'itk::TriangleThresholdImageFilter', 'itkTriangleThresholdImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('TriangleThresholdImageFilter', 'itk::TriangleThresholdImageFilter', 'itkTriangleThresholdImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('TriangleThresholdImageFilter', 'itk::TriangleThresholdImageFilter', 'itkTriangleThresholdImageFilterIF2ISS2', True, 'itk::Image< float,2 >, itk::Image< signed short,2 >'),
  ('TriangleThresholdImageFilter', 'itk::TriangleThresholdImageFilter', 'itkTriangleThresholdImageFilterIF3ISS3', True, 'itk::Image< float,3 >, itk::Image< signed short,3 >'),
  ('TriangleThresholdImageFilter', 'itk::TriangleThresholdImageFilter', 'itkTriangleThresholdImageFilterIF2IUC2', True, 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('TriangleThresholdImageFilter', 'itk::TriangleThresholdImageFilter', 'itkTriangleThresholdImageFilterIF3IUC3', True, 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
  ('YenThresholdCalculator', 'itk::YenThresholdCalculator', 'itkYenThresholdCalculatorHDSS', True, 'itk::Statistics::Histogram< double >, signed short'),
  ('YenThresholdCalculator', 'itk::YenThresholdCalculator', 'itkYenThresholdCalculatorHFSS', True, 'itk::Statistics::Histogram< float >, signed short'),
  ('YenThresholdCalculator', 'itk::YenThresholdCalculator', 'itkYenThresholdCalculatorHDUC', True, 'itk::Statistics::Histogram< double >, unsigned char'),
  ('YenThresholdCalculator', 'itk::YenThresholdCalculator', 'itkYenThresholdCalculatorHFUC', True, 'itk::Statistics::Histogram< float >, unsigned char'),
  ('YenThresholdCalculator', 'itk::YenThresholdCalculator', 'itkYenThresholdCalculatorHDF', True, 'itk::Statistics::Histogram< double >, float'),
  ('YenThresholdCalculator', 'itk::YenThresholdCalculator', 'itkYenThresholdCalculatorHFF', True, 'itk::Statistics::Histogram< float >, float'),
  ('YenThresholdImageFilter', 'itk::YenThresholdImageFilter', 'itkYenThresholdImageFilterISS2ISS2', True, 'itk::Image< signed short,2 >, itk::Image< signed short,2 >'),
  ('YenThresholdImageFilter', 'itk::YenThresholdImageFilter', 'itkYenThresholdImageFilterISS3ISS3', True, 'itk::Image< signed short,3 >, itk::Image< signed short,3 >'),
  ('YenThresholdImageFilter', 'itk::YenThresholdImageFilter', 'itkYenThresholdImageFilterISS2IUC2', True, 'itk::Image< signed short,2 >, itk::Image< unsigned char,2 >'),
  ('YenThresholdImageFilter', 'itk::YenThresholdImageFilter', 'itkYenThresholdImageFilterISS3IUC3', True, 'itk::Image< signed short,3 >, itk::Image< unsigned char,3 >'),
  ('YenThresholdImageFilter', 'itk::YenThresholdImageFilter', 'itkYenThresholdImageFilterIUC2ISS2', True, 'itk::Image< unsigned char,2 >, itk::Image< signed short,2 >'),
  ('YenThresholdImageFilter', 'itk::YenThresholdImageFilter', 'itkYenThresholdImageFilterIUC3ISS3', True, 'itk::Image< unsigned char,3 >, itk::Image< signed short,3 >'),
  ('YenThresholdImageFilter', 'itk::YenThresholdImageFilter', 'itkYenThresholdImageFilterIUC2IUC2', True, 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('YenThresholdImageFilter', 'itk::YenThresholdImageFilter', 'itkYenThresholdImageFilterIUC3IUC3', True, 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('YenThresholdImageFilter', 'itk::YenThresholdImageFilter', 'itkYenThresholdImageFilterIF2ISS2', True, 'itk::Image< float,2 >, itk::Image< signed short,2 >'),
  ('YenThresholdImageFilter', 'itk::YenThresholdImageFilter', 'itkYenThresholdImageFilterIF3ISS3', True, 'itk::Image< float,3 >, itk::Image< signed short,3 >'),
  ('YenThresholdImageFilter', 'itk::YenThresholdImageFilter', 'itkYenThresholdImageFilterIF2IUC2', True, 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('YenThresholdImageFilter', 'itk::YenThresholdImageFilter', 'itkYenThresholdImageFilterIF3IUC3', True, 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
)
