language: python
sudo: false
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6
install:
    - pip install coverage coveralls
    - pip install freezegun mock
    - pip install --no-deps -e .
script:
    - coverage run -m gtimelog.tests
after_success:
    - coveralls
notifications:
    email: false
